// @generated by ipxact-codegen; do not edit by hand.
// Source schema: crates/ipxact/schema/1685-2022/index.xsd

#![allow(dead_code, unused_mut, unused_variables, clippy::all)]

pub mod quick_xml_deserialize;
pub mod quick_xml_serialize;
pub type AbstractorElement = AbstractorTypeXsdType;
#[derive(Clone, Debug, PartialEq)]
pub enum AbstractorModeTypeXsdType {
    Initiator,
    Target,
    Direct,
    System,
}
impl ::xsd_parser_types::quick_xml::SerializeBytes for AbstractorModeTypeXsdType {
    fn serialize_bytes(
        &self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Result<Option<::std::borrow::Cow<'_, str>>, ::xsd_parser_types::quick_xml::Error> {
        match self {
            Self::Initiator => Ok(Some(::std::borrow::Cow::Borrowed("initiator"))),
            Self::Target => Ok(Some(::std::borrow::Cow::Borrowed("target"))),
            Self::Direct => Ok(Some(::std::borrow::Cow::Borrowed("direct"))),
            Self::System => Ok(Some(::std::borrow::Cow::Borrowed("system"))),
        }
    }
}
impl xsd_parser_types::quick_xml::WithSerializeToBytes for AbstractorModeTypeXsdType {}
impl ::xsd_parser_types::quick_xml::DeserializeBytes for AbstractorModeTypeXsdType {
    fn deserialize_bytes(
        helper: &mut ::xsd_parser_types::quick_xml::DeserializeHelper,
        bytes: &[u8],
    ) -> Result<Self, ::xsd_parser_types::quick_xml::Error> {
        match bytes {
            b"initiator" => Ok(Self::Initiator),
            b"target" => Ok(Self::Target),
            b"direct" => Ok(Self::Direct),
            b"system" => Ok(Self::System),
            x => Err(::xsd_parser_types::quick_xml::Error::from(
                ::xsd_parser_types::quick_xml::ErrorKind::UnknownOrInvalidValue(
                    ::xsd_parser_types::quick_xml::RawByteStr::from_slice(x),
                ),
            )),
        }
    }
}
impl xsd_parser_types::quick_xml::WithDeserializerFromBytes for AbstractorModeTypeXsdType {}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractorTypeXsdType {
    pub id: Option<super::Id>,
    pub content: AbstractorTypeXsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractorTypeXsdTypeContent {
    pub document_name_group: AbstractorDocumentNameGroupXsdType,
    pub abstractor_mode: AbstractorTypeAbstractorModeElement,
    pub bus_type: super::identifier::LibraryRefTypeXsdType,
    pub abstractor_interfaces: AbstractorTypeAbstractorInterfacesElement,
    pub model: Option<super::model::AbstractorModelTypeXsdType>,
    pub abstractor_generators: Option<super::generator::AbstractorGeneratorsElement>,
    pub choices: Option<super::auto_configure::ChoicesElement>,
    pub file_sets: Option<super::file::FileSetsElement>,
    pub parameters: Option<super::common_structures::ParametersElement>,
    pub assertions: Option<super::common_structures::AssertionsElement>,
    pub vendor_extensions: Option<super::common_structures::VendorExtensionsElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for AbstractorTypeXsdType {
    type Serializer<'x> = quick_xml_serialize::AbstractorTypeXsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::AbstractorTypeXsdTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::AbstractorTypeXsdTypeSerializerState::Init__),
            name: name.unwrap_or("ipxact:abstractorType"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for AbstractorTypeXsdTypeContent {
    type Serializer<'x> = quick_xml_serialize::AbstractorTypeXsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::AbstractorTypeXsdTypeContentSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::AbstractorTypeXsdTypeContentSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for AbstractorTypeXsdType {
    type Deserializer = Box<quick_xml_deserialize::AbstractorTypeXsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for AbstractorTypeXsdTypeContent {
    type Deserializer = Box<quick_xml_deserialize::AbstractorTypeXsdTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractorDocumentNameGroupXsdType {
    pub content: AbstractorDocumentNameGroupXsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractorDocumentNameGroupXsdTypeContent {
    pub versioned_identifier: AbstractorVersionedIdentifierXsdType,
    pub display_name: Option<super::StringXsdType>,
    pub short_description: Option<super::common_structures::ShortDescriptionElement>,
    pub description: Option<super::common_structures::DescriptionElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for AbstractorDocumentNameGroupXsdType {
    type Serializer<'x> = quick_xml_serialize::AbstractorDocumentNameGroupXsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::AbstractorDocumentNameGroupXsdTypeSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::AbstractorDocumentNameGroupXsdTypeSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for AbstractorDocumentNameGroupXsdTypeContent {
    type Serializer<'x> =
        quick_xml_serialize::AbstractorDocumentNameGroupXsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractorDocumentNameGroupXsdTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractorDocumentNameGroupXsdTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for AbstractorDocumentNameGroupXsdType {
    type Deserializer = Box<quick_xml_deserialize::AbstractorDocumentNameGroupXsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for AbstractorDocumentNameGroupXsdTypeContent {
    type Deserializer =
        Box<quick_xml_deserialize::AbstractorDocumentNameGroupXsdTypeContentDeserializer>;
}
pub type AbstractorTypeAbstractorModeElement = AbstractorTypeAbstractorModeElementType;
pub type AbstractorTypeAbstractorInterfacesElement = AbstractorTypeAbstractorInterfacesElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractorVersionedIdentifierXsdType {
    pub content: AbstractorVersionedIdentifierXsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractorVersionedIdentifierXsdTypeContent {
    pub vendor: super::NameXsdType,
    pub library: super::NameXsdType,
    pub name: super::NmtokenXsdType,
    pub version: super::NmtokenXsdType,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for AbstractorVersionedIdentifierXsdType {
    type Serializer<'x> = quick_xml_serialize::AbstractorVersionedIdentifierXsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractorVersionedIdentifierXsdTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractorVersionedIdentifierXsdTypeSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for AbstractorVersionedIdentifierXsdTypeContent {
    type Serializer<'x> =
        quick_xml_serialize::AbstractorVersionedIdentifierXsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractorVersionedIdentifierXsdTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractorVersionedIdentifierXsdTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for AbstractorVersionedIdentifierXsdType {
    type Deserializer =
        Box<quick_xml_deserialize::AbstractorVersionedIdentifierXsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractorVersionedIdentifierXsdTypeContent
{
    type Deserializer =
        Box<quick_xml_deserialize::AbstractorVersionedIdentifierXsdTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractorTypeAbstractorModeElementType {
    pub group: Option<super::NameXsdType>,
    pub content: AbstractorModeTypeXsdType,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for AbstractorTypeAbstractorModeElementType {
    type Serializer<'x> =
        quick_xml_serialize::AbstractorTypeAbstractorModeElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::AbstractorTypeAbstractorModeElementTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractorTypeAbstractorModeElementTypeSerializerState::Init__,
            ),
            name: name.unwrap_or("ipxact:AbstractorTypeAbstractorMode"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for AbstractorTypeAbstractorModeElementType {
    type Deserializer =
        Box<quick_xml_deserialize::AbstractorTypeAbstractorModeElementTypeDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractorTypeAbstractorInterfacesElementType {
    pub content: AbstractorTypeAbstractorInterfacesElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractorTypeAbstractorInterfacesElementTypeContent {
    pub abstractor_interface: [super::bus_interface::AbstractorBusInterfaceTypeXsdType; 2usize],
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractorTypeAbstractorInterfacesElementType
{
    type Serializer<'x> =
        quick_xml_serialize::AbstractorTypeAbstractorInterfacesElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::AbstractorTypeAbstractorInterfacesElementTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractorTypeAbstractorInterfacesElementTypeSerializerState::Init__,
            ),
            name: name.unwrap_or("ipxact:AbstractorTypeAbstractorInterfaces"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractorTypeAbstractorInterfacesElementTypeContent
{
    type Serializer<'x> =
        quick_xml_serialize::AbstractorTypeAbstractorInterfacesElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractorTypeAbstractorInterfacesElementTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractorTypeAbstractorInterfacesElementTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractorTypeAbstractorInterfacesElementType
{
    type Deserializer =
        Box<quick_xml_deserialize::AbstractorTypeAbstractorInterfacesElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractorTypeAbstractorInterfacesElementTypeContent
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractorTypeAbstractorInterfacesElementTypeContentDeserializer,
    >;
}
