// @generated by ipxact-codegen; do not edit by hand.
// Source schema: crates/ipxact/schema/1685-2022/index.xsd

#![allow(dead_code, unused_mut, unused_variables, clippy::all)]

use xsd_parser_types::quick_xml::Serializer as _;
#[derive(Debug)]
pub struct AbstractorTypeXsdTypeSerializer<'ser> {
    pub(super) value: &'ser super::AbstractorTypeXsdType,
    pub(super) state: Box<AbstractorTypeXsdTypeSerializerState<'ser>>,
    pub(super) name: &'ser str,
    pub(super) is_root: bool,
}
#[derive(Debug)]
pub(super) enum AbstractorTypeXsdTypeSerializerState<'ser> {
    Init__,
    Content__(
        <super::AbstractorTypeXsdTypeContent as ::xsd_parser_types::quick_xml::WithSerializer>::Serializer<
            'ser,
        >,
    ),
    End__,
    Done__,
    Phantom__(&'ser ()),
}
impl<'ser> AbstractorTypeXsdTypeSerializer<'ser> {
    fn next_event(
        &mut self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Result<
        Option<::xsd_parser_types::quick_xml::Event<'ser>>,
        ::xsd_parser_types::quick_xml::Error,
    > {
        loop {
            match &mut *self.state {
                AbstractorTypeXsdTypeSerializerState::Init__ => {
                    *self.state = AbstractorTypeXsdTypeSerializerState::Content__(
                        ::xsd_parser_types::quick_xml::WithSerializer::serializer(
                            &self.value.content,
                            None,
                            false,
                        )?,
                    );
                    let mut bytes = ::xsd_parser_types::quick_xml::BytesStart::new(self.name);
                    helper.begin_ns_scope();
                    if self.is_root {
                        helper.write_xmlns(
                            &mut bytes,
                            Some(&super::super::PREFIX_IPXACT),
                            &super::super::NS_IPXACT,
                        );
                    }
                    helper.write_attrib_opt(&mut bytes, "id", &self.value.id)?;
                    return Ok(Some(::xsd_parser_types::quick_xml::Event::Start(bytes)));
                }
                AbstractorTypeXsdTypeSerializerState::Content__(x) => {
                    match x.next(helper).transpose()? {
                        Some(event) => return Ok(Some(event)),
                        None => *self.state = AbstractorTypeXsdTypeSerializerState::End__,
                    }
                }
                AbstractorTypeXsdTypeSerializerState::End__ => {
                    *self.state = AbstractorTypeXsdTypeSerializerState::Done__;
                    helper.end_ns_scope();
                    return Ok(Some(::xsd_parser_types::quick_xml::Event::End(
                        ::xsd_parser_types::quick_xml::BytesEnd::new(self.name),
                    )));
                }
                AbstractorTypeXsdTypeSerializerState::Done__ => return Ok(None),
                AbstractorTypeXsdTypeSerializerState::Phantom__(_) => unreachable!(),
            }
        }
    }
}
impl<'ser> ::xsd_parser_types::quick_xml::Serializer<'ser>
    for AbstractorTypeXsdTypeSerializer<'ser>
{
    fn next(
        &mut self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Option<
        Result<::xsd_parser_types::quick_xml::Event<'ser>, ::xsd_parser_types::quick_xml::Error>,
    > {
        match self.next_event(helper) {
            Ok(Some(event)) => Some(Ok(event)),
            Ok(None) => None,
            Err(error) => {
                *self.state = AbstractorTypeXsdTypeSerializerState::Done__;
                Some(Err(error))
            }
        }
    }
}
#[derive(Debug)]
pub struct AbstractorTypeXsdTypeContentSerializer<'ser> {
    pub(super) value: &'ser super::AbstractorTypeXsdTypeContent,
    pub(super) state: Box<AbstractorTypeXsdTypeContentSerializerState<'ser>>,
}
#[derive(Debug)]
pub(super) enum AbstractorTypeXsdTypeContentSerializerState<'ser> {
    Init__,
    DocumentNameGroup(
        <super::AbstractorDocumentNameGroupXsdType as ::xsd_parser_types::quick_xml::WithSerializer>::Serializer<
            'ser,
        >,
    ),
    AbstractorMode(
        <super::AbstractorTypeAbstractorModeElement as ::xsd_parser_types::quick_xml::WithSerializer>::Serializer<
            'ser,
        >,
    ),
    BusType(
        <super::super::identifier::LibraryRefTypeXsdType as ::xsd_parser_types::quick_xml::WithSerializer>::Serializer<
            'ser,
        >,
    ),
    AbstractorInterfaces(
        <super::AbstractorTypeAbstractorInterfacesElement as ::xsd_parser_types::quick_xml::WithSerializer>::Serializer<
            'ser,
        >,
    ),
    Model(
        ::xsd_parser_types::quick_xml::IterSerializer<
            'ser,
            Option<&'ser super::super::model::AbstractorModelTypeXsdType>,
            super::super::model::AbstractorModelTypeXsdType,
        >,
    ),
    AbstractorGenerators(
        ::xsd_parser_types::quick_xml::IterSerializer<
            'ser,
            Option<&'ser super::super::generator::AbstractorGeneratorsElement>,
            super::super::generator::AbstractorGeneratorsElement,
        >,
    ),
    Choices(
        ::xsd_parser_types::quick_xml::IterSerializer<
            'ser,
            Option<&'ser super::super::auto_configure::ChoicesElement>,
            super::super::auto_configure::ChoicesElement,
        >,
    ),
    FileSets(
        ::xsd_parser_types::quick_xml::IterSerializer<
            'ser,
            Option<&'ser super::super::file::FileSetsElement>,
            super::super::file::FileSetsElement,
        >,
    ),
    Parameters(
        ::xsd_parser_types::quick_xml::IterSerializer<
            'ser,
            Option<&'ser super::super::common_structures::ParametersElement>,
            super::super::common_structures::ParametersElement,
        >,
    ),
    Assertions(
        ::xsd_parser_types::quick_xml::IterSerializer<
            'ser,
            Option<&'ser super::super::common_structures::AssertionsElement>,
            super::super::common_structures::AssertionsElement,
        >,
    ),
    VendorExtensions(
        ::xsd_parser_types::quick_xml::IterSerializer<
            'ser,
            Option<&'ser super::super::common_structures::VendorExtensionsElement>,
            super::super::common_structures::VendorExtensionsElement,
        >,
    ),
    Done__,
    Phantom__(&'ser ()),
}
impl<'ser> AbstractorTypeXsdTypeContentSerializer<'ser> {
    fn next_event(
        &mut self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Result<
        Option<::xsd_parser_types::quick_xml::Event<'ser>>,
        ::xsd_parser_types::quick_xml::Error,
    > {
        loop {
            match &mut *self.state {
                AbstractorTypeXsdTypeContentSerializerState::Init__ => {
                    *self.state = AbstractorTypeXsdTypeContentSerializerState::DocumentNameGroup(
                        ::xsd_parser_types::quick_xml::WithSerializer::serializer(
                            &self.value.document_name_group,
                            Some("documentNameGroup"),
                            false,
                        )?,
                    );
                }
                AbstractorTypeXsdTypeContentSerializerState::DocumentNameGroup(x) => {
                    match x.next(helper).transpose()? {
                        Some(event) => return Ok(Some(event)),
                        None => {
                            *self.state =
                                AbstractorTypeXsdTypeContentSerializerState::AbstractorMode(
                                    ::xsd_parser_types::quick_xml::WithSerializer::serializer(
                                        &self.value.abstractor_mode,
                                        Some("ipxact:abstractorMode"),
                                        false,
                                    )?,
                                );
                        }
                    }
                }
                AbstractorTypeXsdTypeContentSerializerState::AbstractorMode(x) => {
                    match x.next(helper).transpose()? {
                        Some(event) => return Ok(Some(event)),
                        None => {
                            *self.state = AbstractorTypeXsdTypeContentSerializerState::BusType(
                                ::xsd_parser_types::quick_xml::WithSerializer::serializer(
                                    &self.value.bus_type,
                                    Some("ipxact:busType"),
                                    false,
                                )?,
                            );
                        }
                    }
                }
                AbstractorTypeXsdTypeContentSerializerState::BusType(x) => {
                    match x.next(helper).transpose()? {
                        Some(event) => return Ok(Some(event)),
                        None => {
                            *self.state =
                                AbstractorTypeXsdTypeContentSerializerState::AbstractorInterfaces(
                                    ::xsd_parser_types::quick_xml::WithSerializer::serializer(
                                        &self.value.abstractor_interfaces,
                                        Some("ipxact:abstractorInterfaces"),
                                        false,
                                    )?,
                                );
                        }
                    }
                }
                AbstractorTypeXsdTypeContentSerializerState::AbstractorInterfaces(x) => {
                    match x.next(helper).transpose()? {
                        Some(event) => return Ok(Some(event)),
                        None => {
                            *self.state = AbstractorTypeXsdTypeContentSerializerState::Model(
                                ::xsd_parser_types::quick_xml::IterSerializer::new(
                                    self.value.model.as_ref(),
                                    Some("ipxact:model"),
                                    false,
                                ),
                            );
                        }
                    }
                }
                AbstractorTypeXsdTypeContentSerializerState::Model(x) => {
                    match x.next(helper).transpose()? {
                        Some(event) => return Ok(Some(event)),
                        None => {
                            *self.state =
                                AbstractorTypeXsdTypeContentSerializerState::AbstractorGenerators(
                                    ::xsd_parser_types::quick_xml::IterSerializer::new(
                                        self.value.abstractor_generators.as_ref(),
                                        Some("ipxact:abstractorGenerators"),
                                        false,
                                    ),
                                );
                        }
                    }
                }
                AbstractorTypeXsdTypeContentSerializerState::AbstractorGenerators(x) => {
                    match x.next(helper).transpose()? {
                        Some(event) => return Ok(Some(event)),
                        None => {
                            *self.state = AbstractorTypeXsdTypeContentSerializerState::Choices(
                                ::xsd_parser_types::quick_xml::IterSerializer::new(
                                    self.value.choices.as_ref(),
                                    Some("ipxact:choices"),
                                    false,
                                ),
                            );
                        }
                    }
                }
                AbstractorTypeXsdTypeContentSerializerState::Choices(x) => {
                    match x.next(helper).transpose()? {
                        Some(event) => return Ok(Some(event)),
                        None => {
                            *self.state = AbstractorTypeXsdTypeContentSerializerState::FileSets(
                                ::xsd_parser_types::quick_xml::IterSerializer::new(
                                    self.value.file_sets.as_ref(),
                                    Some("ipxact:fileSets"),
                                    false,
                                ),
                            );
                        }
                    }
                }
                AbstractorTypeXsdTypeContentSerializerState::FileSets(x) => {
                    match x.next(helper).transpose()? {
                        Some(event) => return Ok(Some(event)),
                        None => {
                            *self.state = AbstractorTypeXsdTypeContentSerializerState::Parameters(
                                ::xsd_parser_types::quick_xml::IterSerializer::new(
                                    self.value.parameters.as_ref(),
                                    Some("ipxact:parameters"),
                                    false,
                                ),
                            );
                        }
                    }
                }
                AbstractorTypeXsdTypeContentSerializerState::Parameters(x) => {
                    match x.next(helper).transpose()? {
                        Some(event) => return Ok(Some(event)),
                        None => {
                            *self.state = AbstractorTypeXsdTypeContentSerializerState::Assertions(
                                ::xsd_parser_types::quick_xml::IterSerializer::new(
                                    self.value.assertions.as_ref(),
                                    Some("ipxact:assertions"),
                                    false,
                                ),
                            );
                        }
                    }
                }
                AbstractorTypeXsdTypeContentSerializerState::Assertions(x) => {
                    match x.next(helper).transpose()? {
                        Some(event) => return Ok(Some(event)),
                        None => {
                            *self.state =
                                AbstractorTypeXsdTypeContentSerializerState::VendorExtensions(
                                    ::xsd_parser_types::quick_xml::IterSerializer::new(
                                        self.value.vendor_extensions.as_ref(),
                                        Some("ipxact:vendorExtensions"),
                                        false,
                                    ),
                                );
                        }
                    }
                }
                AbstractorTypeXsdTypeContentSerializerState::VendorExtensions(x) => {
                    match x.next(helper).transpose()? {
                        Some(event) => return Ok(Some(event)),
                        None => {
                            *self.state = AbstractorTypeXsdTypeContentSerializerState::Done__;
                        }
                    }
                }
                AbstractorTypeXsdTypeContentSerializerState::Done__ => return Ok(None),
                AbstractorTypeXsdTypeContentSerializerState::Phantom__(_) => {
                    unreachable!()
                }
            }
        }
    }
}
impl<'ser> ::xsd_parser_types::quick_xml::Serializer<'ser>
    for AbstractorTypeXsdTypeContentSerializer<'ser>
{
    fn next(
        &mut self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Option<
        Result<::xsd_parser_types::quick_xml::Event<'ser>, ::xsd_parser_types::quick_xml::Error>,
    > {
        match self.next_event(helper) {
            Ok(Some(event)) => Some(Ok(event)),
            Ok(None) => None,
            Err(error) => {
                *self.state = AbstractorTypeXsdTypeContentSerializerState::Done__;
                Some(Err(error))
            }
        }
    }
}
#[derive(Debug)]
pub struct AbstractorDocumentNameGroupXsdTypeSerializer<'ser> {
    pub(super) value: &'ser super::AbstractorDocumentNameGroupXsdType,
    pub(super) state: Box<AbstractorDocumentNameGroupXsdTypeSerializerState<'ser>>,
}
#[derive(Debug)]
pub(super) enum AbstractorDocumentNameGroupXsdTypeSerializerState<'ser> {
    Init__,
    Content__(
        <super::AbstractorDocumentNameGroupXsdTypeContent as ::xsd_parser_types::quick_xml::WithSerializer>::Serializer<
            'ser,
        >,
    ),
    Done__,
    Phantom__(&'ser ()),
}
impl<'ser> AbstractorDocumentNameGroupXsdTypeSerializer<'ser> {
    fn next_event(
        &mut self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Result<
        Option<::xsd_parser_types::quick_xml::Event<'ser>>,
        ::xsd_parser_types::quick_xml::Error,
    > {
        loop {
            match &mut *self.state {
                AbstractorDocumentNameGroupXsdTypeSerializerState::Init__ => {
                    *self.state = AbstractorDocumentNameGroupXsdTypeSerializerState::Content__(
                        ::xsd_parser_types::quick_xml::WithSerializer::serializer(
                            &self.value.content,
                            None,
                            false,
                        )?,
                    );
                }
                AbstractorDocumentNameGroupXsdTypeSerializerState::Content__(x) => {
                    match x.next(helper).transpose()? {
                        Some(event) => return Ok(Some(event)),
                        None => {
                            *self.state = AbstractorDocumentNameGroupXsdTypeSerializerState::Done__;
                        }
                    }
                }
                AbstractorDocumentNameGroupXsdTypeSerializerState::Done__ => {
                    return Ok(None);
                }
                AbstractorDocumentNameGroupXsdTypeSerializerState::Phantom__(_) => {
                    unreachable!()
                }
            }
        }
    }
}
impl<'ser> ::xsd_parser_types::quick_xml::Serializer<'ser>
    for AbstractorDocumentNameGroupXsdTypeSerializer<'ser>
{
    fn next(
        &mut self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Option<
        Result<::xsd_parser_types::quick_xml::Event<'ser>, ::xsd_parser_types::quick_xml::Error>,
    > {
        match self.next_event(helper) {
            Ok(Some(event)) => Some(Ok(event)),
            Ok(None) => None,
            Err(error) => {
                *self.state = AbstractorDocumentNameGroupXsdTypeSerializerState::Done__;
                Some(Err(error))
            }
        }
    }
}
#[derive(Debug)]
pub struct AbstractorDocumentNameGroupXsdTypeContentSerializer<'ser> {
    pub(super) value: &'ser super::AbstractorDocumentNameGroupXsdTypeContent,
    pub(super) state: Box<AbstractorDocumentNameGroupXsdTypeContentSerializerState<'ser>>,
}
#[derive(Debug)]
pub(super) enum AbstractorDocumentNameGroupXsdTypeContentSerializerState<'ser> {
    Init__,
    VersionedIdentifier(
        <super::AbstractorVersionedIdentifierXsdType as ::xsd_parser_types::quick_xml::WithSerializer>::Serializer<
            'ser,
        >,
    ),
    DisplayName(
        ::xsd_parser_types::quick_xml::IterSerializer<
            'ser,
            Option<&'ser super::super::StringXsdType>,
            super::super::StringXsdType,
        >,
    ),
    ShortDescription(
        ::xsd_parser_types::quick_xml::IterSerializer<
            'ser,
            Option<&'ser super::super::common_structures::ShortDescriptionElement>,
            super::super::common_structures::ShortDescriptionElement,
        >,
    ),
    Description(
        ::xsd_parser_types::quick_xml::IterSerializer<
            'ser,
            Option<&'ser super::super::common_structures::DescriptionElement>,
            super::super::common_structures::DescriptionElement,
        >,
    ),
    Done__,
    Phantom__(&'ser ()),
}
impl<'ser> AbstractorDocumentNameGroupXsdTypeContentSerializer<'ser> {
    fn next_event(
        &mut self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Result<
        Option<::xsd_parser_types::quick_xml::Event<'ser>>,
        ::xsd_parser_types::quick_xml::Error,
    > {
        loop {
            match &mut *self.state {
                AbstractorDocumentNameGroupXsdTypeContentSerializerState::Init__ => {
                    *self.state = AbstractorDocumentNameGroupXsdTypeContentSerializerState::VersionedIdentifier(
                        ::xsd_parser_types::quick_xml::WithSerializer::serializer(
                            &self.value.versioned_identifier,
                            Some("versionedIdentifier"),
                            false,
                        )?,
                    );
                }
                AbstractorDocumentNameGroupXsdTypeContentSerializerState::VersionedIdentifier(
                    x,
                ) => match x.next(helper).transpose()? {
                    Some(event) => return Ok(Some(event)),
                    None => {
                        *self.state =
                            AbstractorDocumentNameGroupXsdTypeContentSerializerState::DisplayName(
                                ::xsd_parser_types::quick_xml::IterSerializer::new(
                                    self.value.display_name.as_ref(),
                                    Some("ipxact:displayName"),
                                    false,
                                ),
                            );
                    }
                },
                AbstractorDocumentNameGroupXsdTypeContentSerializerState::DisplayName(x) => {
                    match x.next(helper).transpose()? {
                        Some(event) => return Ok(Some(event)),
                        None => {
                            *self.state = AbstractorDocumentNameGroupXsdTypeContentSerializerState::ShortDescription(
                                ::xsd_parser_types::quick_xml::IterSerializer::new(
                                    self.value.short_description.as_ref(),
                                    Some("ipxact:shortDescription"),
                                    false,
                                ),
                            );
                        }
                    }
                }
                AbstractorDocumentNameGroupXsdTypeContentSerializerState::ShortDescription(x) => {
                    match x.next(helper).transpose()? {
                        Some(event) => return Ok(Some(event)),
                        None => {
                            *self.state = AbstractorDocumentNameGroupXsdTypeContentSerializerState::Description(
                                ::xsd_parser_types::quick_xml::IterSerializer::new(
                                    self.value.description.as_ref(),
                                    Some("ipxact:description"),
                                    false,
                                ),
                            );
                        }
                    }
                }
                AbstractorDocumentNameGroupXsdTypeContentSerializerState::Description(x) => {
                    match x.next(helper).transpose()? {
                        Some(event) => return Ok(Some(event)),
                        None => {
                            *self.state =
                                AbstractorDocumentNameGroupXsdTypeContentSerializerState::Done__;
                        }
                    }
                }
                AbstractorDocumentNameGroupXsdTypeContentSerializerState::Done__ => {
                    return Ok(None);
                }
                AbstractorDocumentNameGroupXsdTypeContentSerializerState::Phantom__(_) => {
                    unreachable!()
                }
            }
        }
    }
}
impl<'ser> ::xsd_parser_types::quick_xml::Serializer<'ser>
    for AbstractorDocumentNameGroupXsdTypeContentSerializer<'ser>
{
    fn next(
        &mut self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Option<
        Result<::xsd_parser_types::quick_xml::Event<'ser>, ::xsd_parser_types::quick_xml::Error>,
    > {
        match self.next_event(helper) {
            Ok(Some(event)) => Some(Ok(event)),
            Ok(None) => None,
            Err(error) => {
                *self.state = AbstractorDocumentNameGroupXsdTypeContentSerializerState::Done__;
                Some(Err(error))
            }
        }
    }
}
#[derive(Debug)]
pub struct AbstractorVersionedIdentifierXsdTypeSerializer<'ser> {
    pub(super) value: &'ser super::AbstractorVersionedIdentifierXsdType,
    pub(super) state: Box<AbstractorVersionedIdentifierXsdTypeSerializerState<'ser>>,
}
#[derive(Debug)]
pub(super) enum AbstractorVersionedIdentifierXsdTypeSerializerState<'ser> {
    Init__,
    Content__(
        <super::AbstractorVersionedIdentifierXsdTypeContent as ::xsd_parser_types::quick_xml::WithSerializer>::Serializer<
            'ser,
        >,
    ),
    Done__,
    Phantom__(&'ser ()),
}
impl<'ser> AbstractorVersionedIdentifierXsdTypeSerializer<'ser> {
    fn next_event(
        &mut self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Result<
        Option<::xsd_parser_types::quick_xml::Event<'ser>>,
        ::xsd_parser_types::quick_xml::Error,
    > {
        loop {
            match &mut *self.state {
                AbstractorVersionedIdentifierXsdTypeSerializerState::Init__ => {
                    *self.state = AbstractorVersionedIdentifierXsdTypeSerializerState::Content__(
                        ::xsd_parser_types::quick_xml::WithSerializer::serializer(
                            &self.value.content,
                            None,
                            false,
                        )?,
                    );
                }
                AbstractorVersionedIdentifierXsdTypeSerializerState::Content__(x) => {
                    match x.next(helper).transpose()? {
                        Some(event) => return Ok(Some(event)),
                        None => {
                            *self.state =
                                AbstractorVersionedIdentifierXsdTypeSerializerState::Done__;
                        }
                    }
                }
                AbstractorVersionedIdentifierXsdTypeSerializerState::Done__ => {
                    return Ok(None);
                }
                AbstractorVersionedIdentifierXsdTypeSerializerState::Phantom__(_) => {
                    unreachable!()
                }
            }
        }
    }
}
impl<'ser> ::xsd_parser_types::quick_xml::Serializer<'ser>
    for AbstractorVersionedIdentifierXsdTypeSerializer<'ser>
{
    fn next(
        &mut self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Option<
        Result<::xsd_parser_types::quick_xml::Event<'ser>, ::xsd_parser_types::quick_xml::Error>,
    > {
        match self.next_event(helper) {
            Ok(Some(event)) => Some(Ok(event)),
            Ok(None) => None,
            Err(error) => {
                *self.state = AbstractorVersionedIdentifierXsdTypeSerializerState::Done__;
                Some(Err(error))
            }
        }
    }
}
#[derive(Debug)]
pub struct AbstractorVersionedIdentifierXsdTypeContentSerializer<'ser> {
    pub(super) value: &'ser super::AbstractorVersionedIdentifierXsdTypeContent,
    pub(super) state: Box<AbstractorVersionedIdentifierXsdTypeContentSerializerState<'ser>>,
}
#[derive(Debug)]
pub(super) enum AbstractorVersionedIdentifierXsdTypeContentSerializerState<'ser> {
    Init__,
    Vendor(
        <super::super::NameXsdType as ::xsd_parser_types::quick_xml::WithSerializer>::Serializer<
            'ser,
        >,
    ),
    Library(
        <super::super::NameXsdType as ::xsd_parser_types::quick_xml::WithSerializer>::Serializer<
            'ser,
        >,
    ),
    Name(
        <super::super::NmtokenXsdType as ::xsd_parser_types::quick_xml::WithSerializer>::Serializer<
            'ser,
        >,
    ),
    Version(
        <super::super::NmtokenXsdType as ::xsd_parser_types::quick_xml::WithSerializer>::Serializer<
            'ser,
        >,
    ),
    Done__,
    Phantom__(&'ser ()),
}
impl<'ser> AbstractorVersionedIdentifierXsdTypeContentSerializer<'ser> {
    fn next_event(
        &mut self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Result<
        Option<::xsd_parser_types::quick_xml::Event<'ser>>,
        ::xsd_parser_types::quick_xml::Error,
    > {
        loop {
            match &mut *self.state {
                AbstractorVersionedIdentifierXsdTypeContentSerializerState::Init__ => {
                    *self.state =
                        AbstractorVersionedIdentifierXsdTypeContentSerializerState::Vendor(
                            ::xsd_parser_types::quick_xml::WithSerializer::serializer(
                                &self.value.vendor,
                                Some("ipxact:vendor"),
                                false,
                            )?,
                        );
                }
                AbstractorVersionedIdentifierXsdTypeContentSerializerState::Vendor(x) => {
                    match x.next(helper).transpose()? {
                        Some(event) => return Ok(Some(event)),
                        None => {
                            *self.state =
                                AbstractorVersionedIdentifierXsdTypeContentSerializerState::Library(
                                    ::xsd_parser_types::quick_xml::WithSerializer::serializer(
                                        &self.value.library,
                                        Some("ipxact:library"),
                                        false,
                                    )?,
                                );
                        }
                    }
                }
                AbstractorVersionedIdentifierXsdTypeContentSerializerState::Library(x) => {
                    match x.next(helper).transpose()? {
                        Some(event) => return Ok(Some(event)),
                        None => {
                            *self.state =
                                AbstractorVersionedIdentifierXsdTypeContentSerializerState::Name(
                                    ::xsd_parser_types::quick_xml::WithSerializer::serializer(
                                        &self.value.name,
                                        Some("ipxact:name"),
                                        false,
                                    )?,
                                );
                        }
                    }
                }
                AbstractorVersionedIdentifierXsdTypeContentSerializerState::Name(x) => {
                    match x.next(helper).transpose()? {
                        Some(event) => return Ok(Some(event)),
                        None => {
                            *self.state =
                                AbstractorVersionedIdentifierXsdTypeContentSerializerState::Version(
                                    ::xsd_parser_types::quick_xml::WithSerializer::serializer(
                                        &self.value.version,
                                        Some("ipxact:version"),
                                        false,
                                    )?,
                                );
                        }
                    }
                }
                AbstractorVersionedIdentifierXsdTypeContentSerializerState::Version(x) => {
                    match x.next(helper).transpose()? {
                        Some(event) => return Ok(Some(event)),
                        None => {
                            *self.state =
                                AbstractorVersionedIdentifierXsdTypeContentSerializerState::Done__;
                        }
                    }
                }
                AbstractorVersionedIdentifierXsdTypeContentSerializerState::Done__ => {
                    return Ok(None);
                }
                AbstractorVersionedIdentifierXsdTypeContentSerializerState::Phantom__(_) => {
                    unreachable!()
                }
            }
        }
    }
}
impl<'ser> ::xsd_parser_types::quick_xml::Serializer<'ser>
    for AbstractorVersionedIdentifierXsdTypeContentSerializer<'ser>
{
    fn next(
        &mut self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Option<
        Result<::xsd_parser_types::quick_xml::Event<'ser>, ::xsd_parser_types::quick_xml::Error>,
    > {
        match self.next_event(helper) {
            Ok(Some(event)) => Some(Ok(event)),
            Ok(None) => None,
            Err(error) => {
                *self.state = AbstractorVersionedIdentifierXsdTypeContentSerializerState::Done__;
                Some(Err(error))
            }
        }
    }
}
#[derive(Debug)]
pub struct AbstractorTypeAbstractorModeElementTypeSerializer<'ser> {
    pub(super) value: &'ser super::AbstractorTypeAbstractorModeElementType,
    pub(super) state: Box<AbstractorTypeAbstractorModeElementTypeSerializerState<'ser>>,
    pub(super) name: &'ser str,
    pub(super) is_root: bool,
}
#[derive(Debug)]
pub(super) enum AbstractorTypeAbstractorModeElementTypeSerializerState<'ser> {
    Init__,
    Content__(
        <super::AbstractorModeTypeXsdType as ::xsd_parser_types::quick_xml::WithSerializer>::Serializer<
            'ser,
        >,
    ),
    End__,
    Done__,
    Phantom__(&'ser ()),
}
impl<'ser> AbstractorTypeAbstractorModeElementTypeSerializer<'ser> {
    fn next_event(
        &mut self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Result<
        Option<::xsd_parser_types::quick_xml::Event<'ser>>,
        ::xsd_parser_types::quick_xml::Error,
    > {
        loop {
            match &mut *self.state {
                AbstractorTypeAbstractorModeElementTypeSerializerState::Init__ => {
                    *self.state = AbstractorTypeAbstractorModeElementTypeSerializerState::Content__(
                        ::xsd_parser_types::quick_xml::WithSerializer::serializer(
                            &self.value.content,
                            None,
                            false,
                        )?,
                    );
                    let mut bytes = ::xsd_parser_types::quick_xml::BytesStart::new(self.name);
                    helper.begin_ns_scope();
                    if self.is_root {
                        helper.write_xmlns(
                            &mut bytes,
                            Some(&super::super::PREFIX_IPXACT),
                            &super::super::NS_IPXACT,
                        );
                    }
                    helper.write_attrib_opt(&mut bytes, "group", &self.value.group)?;
                    return Ok(Some(::xsd_parser_types::quick_xml::Event::Start(bytes)));
                }
                AbstractorTypeAbstractorModeElementTypeSerializerState::Content__(x) => {
                    match x.next(helper).transpose()? {
                        Some(event) => return Ok(Some(event)),
                        None => {
                            *self.state =
                                AbstractorTypeAbstractorModeElementTypeSerializerState::End__;
                        }
                    }
                }
                AbstractorTypeAbstractorModeElementTypeSerializerState::End__ => {
                    *self.state = AbstractorTypeAbstractorModeElementTypeSerializerState::Done__;
                    helper.end_ns_scope();
                    return Ok(Some(::xsd_parser_types::quick_xml::Event::End(
                        ::xsd_parser_types::quick_xml::BytesEnd::new(self.name),
                    )));
                }
                AbstractorTypeAbstractorModeElementTypeSerializerState::Done__ => {
                    return Ok(None);
                }
                AbstractorTypeAbstractorModeElementTypeSerializerState::Phantom__(_) => {
                    unreachable!()
                }
            }
        }
    }
}
impl<'ser> ::xsd_parser_types::quick_xml::Serializer<'ser>
    for AbstractorTypeAbstractorModeElementTypeSerializer<'ser>
{
    fn next(
        &mut self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Option<
        Result<::xsd_parser_types::quick_xml::Event<'ser>, ::xsd_parser_types::quick_xml::Error>,
    > {
        match self.next_event(helper) {
            Ok(Some(event)) => Some(Ok(event)),
            Ok(None) => None,
            Err(error) => {
                *self.state = AbstractorTypeAbstractorModeElementTypeSerializerState::Done__;
                Some(Err(error))
            }
        }
    }
}
#[derive(Debug)]
pub struct AbstractorTypeAbstractorInterfacesElementTypeSerializer<'ser> {
    pub(super) value: &'ser super::AbstractorTypeAbstractorInterfacesElementType,
    pub(super) state: Box<AbstractorTypeAbstractorInterfacesElementTypeSerializerState<'ser>>,
    pub(super) name: &'ser str,
    pub(super) is_root: bool,
}
#[derive(Debug)]
pub(super) enum AbstractorTypeAbstractorInterfacesElementTypeSerializerState<'ser> {
    Init__,
    Content__(
        <super::AbstractorTypeAbstractorInterfacesElementTypeContent as ::xsd_parser_types::quick_xml::WithSerializer>::Serializer<
            'ser,
        >,
    ),
    End__,
    Done__,
    Phantom__(&'ser ()),
}
impl<'ser> AbstractorTypeAbstractorInterfacesElementTypeSerializer<'ser> {
    fn next_event(
        &mut self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Result<
        Option<::xsd_parser_types::quick_xml::Event<'ser>>,
        ::xsd_parser_types::quick_xml::Error,
    > {
        loop {
            match &mut *self.state {
                AbstractorTypeAbstractorInterfacesElementTypeSerializerState::Init__ => {
                    *self.state =
                        AbstractorTypeAbstractorInterfacesElementTypeSerializerState::Content__(
                            ::xsd_parser_types::quick_xml::WithSerializer::serializer(
                                &self.value.content,
                                None,
                                false,
                            )?,
                        );
                    let mut bytes = ::xsd_parser_types::quick_xml::BytesStart::new(self.name);
                    helper.begin_ns_scope();
                    if self.is_root {
                        helper.write_xmlns(
                            &mut bytes,
                            Some(&super::super::PREFIX_IPXACT),
                            &super::super::NS_IPXACT,
                        );
                    }
                    return Ok(Some(::xsd_parser_types::quick_xml::Event::Start(bytes)));
                }
                AbstractorTypeAbstractorInterfacesElementTypeSerializerState::Content__(x) => {
                    match x.next(helper).transpose()? {
                        Some(event) => return Ok(Some(event)),
                        None => {
                            *self.state =
                                AbstractorTypeAbstractorInterfacesElementTypeSerializerState::End__;
                        }
                    }
                }
                AbstractorTypeAbstractorInterfacesElementTypeSerializerState::End__ => {
                    *self.state =
                        AbstractorTypeAbstractorInterfacesElementTypeSerializerState::Done__;
                    helper.end_ns_scope();
                    return Ok(Some(::xsd_parser_types::quick_xml::Event::End(
                        ::xsd_parser_types::quick_xml::BytesEnd::new(self.name),
                    )));
                }
                AbstractorTypeAbstractorInterfacesElementTypeSerializerState::Done__ => {
                    return Ok(None);
                }
                AbstractorTypeAbstractorInterfacesElementTypeSerializerState::Phantom__(_) => {
                    unreachable!()
                }
            }
        }
    }
}
impl<'ser> ::xsd_parser_types::quick_xml::Serializer<'ser>
    for AbstractorTypeAbstractorInterfacesElementTypeSerializer<'ser>
{
    fn next(
        &mut self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Option<
        Result<::xsd_parser_types::quick_xml::Event<'ser>, ::xsd_parser_types::quick_xml::Error>,
    > {
        match self.next_event(helper) {
            Ok(Some(event)) => Some(Ok(event)),
            Ok(None) => None,
            Err(error) => {
                *self.state = AbstractorTypeAbstractorInterfacesElementTypeSerializerState::Done__;
                Some(Err(error))
            }
        }
    }
}
#[derive(Debug)]
pub struct AbstractorTypeAbstractorInterfacesElementTypeContentSerializer<'ser> {
    pub(super) value: &'ser super::AbstractorTypeAbstractorInterfacesElementTypeContent,
    pub(super) state:
        Box<AbstractorTypeAbstractorInterfacesElementTypeContentSerializerState<'ser>>,
}
#[derive(Debug)]
pub(super) enum AbstractorTypeAbstractorInterfacesElementTypeContentSerializerState<'ser> {
    Init__,
    AbstractorInterface(
        ::xsd_parser_types::quick_xml::IterSerializer<
            'ser,
            &'ser [super::super::bus_interface::AbstractorBusInterfaceTypeXsdType],
            super::super::bus_interface::AbstractorBusInterfaceTypeXsdType,
        >,
    ),
    Done__,
    Phantom__(&'ser ()),
}
impl<'ser> AbstractorTypeAbstractorInterfacesElementTypeContentSerializer<'ser> {
    fn next_event(
        &mut self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Result<
        Option<::xsd_parser_types::quick_xml::Event<'ser>>,
        ::xsd_parser_types::quick_xml::Error,
    > {
        loop {
            match &mut *self.state {
                AbstractorTypeAbstractorInterfacesElementTypeContentSerializerState::Init__ => {
                    *self.state = AbstractorTypeAbstractorInterfacesElementTypeContentSerializerState::AbstractorInterface(
                        ::xsd_parser_types::quick_xml::IterSerializer::new(
                            &self.value.abstractor_interface[..],
                            Some("ipxact:abstractorInterface"),
                            false,
                        ),
                    );
                }
                AbstractorTypeAbstractorInterfacesElementTypeContentSerializerState::AbstractorInterface(
                    x,
                ) => {
                    match x.next(helper).transpose()? {
                        Some(event) => return Ok(Some(event)),
                        None => {
                            *self.state = AbstractorTypeAbstractorInterfacesElementTypeContentSerializerState::Done__;
                        }
                    }
                }
                AbstractorTypeAbstractorInterfacesElementTypeContentSerializerState::Done__ => {
                    return Ok(None);
                }
                AbstractorTypeAbstractorInterfacesElementTypeContentSerializerState::Phantom__(
                    _,
                ) => unreachable!(),
            }
        }
    }
}
impl<'ser> ::xsd_parser_types::quick_xml::Serializer<'ser>
    for AbstractorTypeAbstractorInterfacesElementTypeContentSerializer<'ser>
{
    fn next(
        &mut self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Option<
        Result<::xsd_parser_types::quick_xml::Event<'ser>, ::xsd_parser_types::quick_xml::Error>,
    > {
        match self.next_event(helper) {
            Ok(Some(event)) => Some(Ok(event)),
            Ok(None) => None,
            Err(error) => {
                *self.state =
                    AbstractorTypeAbstractorInterfacesElementTypeContentSerializerState::Done__;
                Some(Err(error))
            }
        }
    }
}
