// @generated by ipxact-codegen; do not edit by hand.
// Source schema: crates/ipxact/schema/1685-2022/index.xsd

#![allow(dead_code, unused_mut, unused_variables, clippy::all)]

pub mod quick_xml_deserialize;
pub mod quick_xml_serialize;
use xsd_parser_types::xml::AnyAttributes;
pub type AbstractionDefinitionElement = AbstractionDefinitionElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionElementType {
    pub id: Option<super::Id>,
    pub content: AbstractionDefinitionElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionElementTypeContent {
    pub document_name_group: AbstractionDefinitionDocumentNameGroupXsdType,
    pub bus_type: super::identifier::LibraryRefTypeXsdType,
    pub extends: Option<super::identifier::LibraryRefTypeXsdType>,
    pub ports: AbstractionDefinitionPortsElement,
    pub choices: Option<super::auto_configure::ChoicesElement>,
    pub parameters: Option<super::common_structures::ParametersElement>,
    pub assertions: Option<super::common_structures::AssertionsElement>,
    pub vendor_extensions: Option<super::common_structures::VendorExtensionsElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for AbstractionDefinitionElementType {
    type Serializer<'x> = quick_xml_serialize::AbstractionDefinitionElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(
            quick_xml_serialize::AbstractionDefinitionElementTypeSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::AbstractionDefinitionElementTypeSerializerState::Init__,
                ),
                name: name.unwrap_or("ipxact:abstractionDefinition"),
                is_root,
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for AbstractionDefinitionElementTypeContent {
    type Serializer<'x> =
        quick_xml_serialize::AbstractionDefinitionElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionElementTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionElementTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for AbstractionDefinitionElementType {
    type Deserializer = Box<quick_xml_deserialize::AbstractionDefinitionElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for AbstractionDefinitionElementTypeContent {
    type Deserializer =
        Box<quick_xml_deserialize::AbstractionDefinitionElementTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub enum DirectionXsdType {
    In,
    Out,
    Inout,
}
impl ::xsd_parser_types::quick_xml::SerializeBytes for DirectionXsdType {
    fn serialize_bytes(
        &self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Result<Option<::std::borrow::Cow<'_, str>>, ::xsd_parser_types::quick_xml::Error> {
        match self {
            Self::In => Ok(Some(::std::borrow::Cow::Borrowed("in"))),
            Self::Out => Ok(Some(::std::borrow::Cow::Borrowed("out"))),
            Self::Inout => Ok(Some(::std::borrow::Cow::Borrowed("inout"))),
        }
    }
}
impl xsd_parser_types::quick_xml::WithSerializeToBytes for DirectionXsdType {}
impl ::xsd_parser_types::quick_xml::DeserializeBytes for DirectionXsdType {
    fn deserialize_bytes(
        helper: &mut ::xsd_parser_types::quick_xml::DeserializeHelper,
        bytes: &[u8],
    ) -> Result<Self, ::xsd_parser_types::quick_xml::Error> {
        match bytes {
            b"in" => Ok(Self::In),
            b"out" => Ok(Self::Out),
            b"inout" => Ok(Self::Inout),
            x => Err(::xsd_parser_types::quick_xml::Error::from(
                ::xsd_parser_types::quick_xml::ErrorKind::UnknownOrInvalidValue(
                    ::xsd_parser_types::quick_xml::RawByteStr::from_slice(x),
                ),
            )),
        }
    }
}
impl xsd_parser_types::quick_xml::WithDeserializerFromBytes for DirectionXsdType {}
pub type PacketsElement = super::port::PortPacketsTypeXsdType;
pub type PresenceElement = PresenceTypeXsdType;
#[derive(Clone, Debug, PartialEq)]
pub enum PresenceTypeXsdType {
    Required,
    Illegal,
    Optional,
}
impl ::xsd_parser_types::quick_xml::SerializeBytes for PresenceTypeXsdType {
    fn serialize_bytes(
        &self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Result<Option<::std::borrow::Cow<'_, str>>, ::xsd_parser_types::quick_xml::Error> {
        match self {
            Self::Required => Ok(Some(::std::borrow::Cow::Borrowed("required"))),
            Self::Illegal => Ok(Some(::std::borrow::Cow::Borrowed("illegal"))),
            Self::Optional => Ok(Some(::std::borrow::Cow::Borrowed("optional"))),
        }
    }
}
impl xsd_parser_types::quick_xml::WithSerializeToBytes for PresenceTypeXsdType {}
impl ::xsd_parser_types::quick_xml::DeserializeBytes for PresenceTypeXsdType {
    fn deserialize_bytes(
        helper: &mut ::xsd_parser_types::quick_xml::DeserializeHelper,
        bytes: &[u8],
    ) -> Result<Self, ::xsd_parser_types::quick_xml::Error> {
        match bytes {
            b"required" => Ok(Self::Required),
            b"illegal" => Ok(Self::Illegal),
            b"optional" => Ok(Self::Optional),
            x => Err(::xsd_parser_types::quick_xml::Error::from(
                ::xsd_parser_types::quick_xml::ErrorKind::UnknownOrInvalidValue(
                    ::xsd_parser_types::quick_xml::RawByteStr::from_slice(x),
                ),
            )),
        }
    }
}
impl xsd_parser_types::quick_xml::WithDeserializerFromBytes for PresenceTypeXsdType {}
pub type WireElement = WireElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct WireElementType {
    pub content: WireElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct WireElementTypeContent {
    pub qualifier: Option<super::common_structures::QualifierTypeXsdType>,
    pub on_system: Vec<WireOnSystemElement>,
    pub on_initiator: Option<WireOnInitiatorElement>,
    pub on_target: Option<WireOnTargetElement>,
    pub content_131: Option<WireContent131XsdType>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for WireElementType {
    type Serializer<'x> = quick_xml_serialize::WireElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::WireElementTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::WireElementTypeSerializerState::Init__),
            name: name.unwrap_or("ipxact:wire"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for WireElementTypeContent {
    type Serializer<'x> = quick_xml_serialize::WireElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::WireElementTypeContentSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::WireElementTypeContentSerializerState::Init__),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for WireElementType {
    type Deserializer = Box<quick_xml_deserialize::WireElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for WireElementTypeContent {
    type Deserializer = Box<quick_xml_deserialize::WireElementTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionDocumentNameGroupXsdType {
    pub content: AbstractionDefinitionDocumentNameGroupXsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionDocumentNameGroupXsdTypeContent {
    pub versioned_identifier: AbstractionDefinitionVersionedIdentifierXsdType,
    pub display_name: Option<super::StringXsdType>,
    pub short_description: Option<super::common_structures::ShortDescriptionElement>,
    pub description: Option<super::common_structures::DescriptionElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionDocumentNameGroupXsdType
{
    type Serializer<'x> =
        quick_xml_serialize::AbstractionDefinitionDocumentNameGroupXsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionDocumentNameGroupXsdTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionDocumentNameGroupXsdTypeSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionDocumentNameGroupXsdTypeContent
{
    type Serializer<'x> =
        quick_xml_serialize::AbstractionDefinitionDocumentNameGroupXsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionDocumentNameGroupXsdTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionDocumentNameGroupXsdTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionDocumentNameGroupXsdType
{
    type Deserializer =
        Box<quick_xml_deserialize::AbstractionDefinitionDocumentNameGroupXsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionDocumentNameGroupXsdTypeContent
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionDocumentNameGroupXsdTypeContentDeserializer,
    >;
}
pub type AbstractionDefinitionPortsElement = AbstractionDefinitionPortsElementType;
pub type WireOnSystemElement = WireOnSystemElementType;
pub type WireOnInitiatorElement = WireOnInitiatorElementType;
pub type WireOnTargetElement = WireOnTargetElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct WireContent131XsdType {
    pub content: WireContent131XsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub enum WireContent131XsdTypeContent {
    DefaultValue(Box<super::simple_types::UnsignedBitVectorExpressionXsdType>),
    RequiresDriver(Box<super::signal_drivers::RequiresDriverElement>),
}
impl ::xsd_parser_types::quick_xml::WithSerializer for WireContent131XsdType {
    type Serializer<'x> = quick_xml_serialize::WireContent131XsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::WireContent131XsdTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::WireContent131XsdTypeSerializerState::Init__),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for WireContent131XsdTypeContent {
    type Serializer<'x> = quick_xml_serialize::WireContent131XsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::WireContent131XsdTypeContentSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::WireContent131XsdTypeContentSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for WireContent131XsdType {
    type Deserializer = Box<quick_xml_deserialize::WireContent131XsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for WireContent131XsdTypeContent {
    type Deserializer = Box<quick_xml_deserialize::WireContent131XsdTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionVersionedIdentifierXsdType {
    pub content: AbstractionDefinitionVersionedIdentifierXsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionVersionedIdentifierXsdTypeContent {
    pub vendor: super::NameXsdType,
    pub library: super::NameXsdType,
    pub name: super::NmtokenXsdType,
    pub version: super::NmtokenXsdType,
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionVersionedIdentifierXsdType
{
    type Serializer<'x> =
        quick_xml_serialize::AbstractionDefinitionVersionedIdentifierXsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionVersionedIdentifierXsdTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionVersionedIdentifierXsdTypeSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionVersionedIdentifierXsdTypeContent
{
    type Serializer<'x> =
        quick_xml_serialize::AbstractionDefinitionVersionedIdentifierXsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionVersionedIdentifierXsdTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionVersionedIdentifierXsdTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionVersionedIdentifierXsdType
{
    type Deserializer =
        Box<quick_xml_deserialize::AbstractionDefinitionVersionedIdentifierXsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionVersionedIdentifierXsdTypeContent
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionVersionedIdentifierXsdTypeContentDeserializer,
    >;
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsElementType {
    pub content: AbstractionDefinitionPortsElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsElementTypeContent {
    pub port: Vec<AbstractionDefinitionPortsPortElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for AbstractionDefinitionPortsElementType {
    type Serializer<'x> = quick_xml_serialize::AbstractionDefinitionPortsElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::AbstractionDefinitionPortsElementTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsElementTypeSerializerState::Init__,
            ),
            name: name.unwrap_or("ipxact:AbstractionDefinitionPorts"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsElementTypeContent
{
    type Serializer<'x> =
        quick_xml_serialize::AbstractionDefinitionPortsElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionPortsElementTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsElementTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for AbstractionDefinitionPortsElementType {
    type Deserializer =
        Box<quick_xml_deserialize::AbstractionDefinitionPortsElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsElementTypeContent
{
    type Deserializer =
        Box<quick_xml_deserialize::AbstractionDefinitionPortsElementTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct WireOnSystemElementType {
    pub id: Option<super::Id>,
    pub content: WireOnSystemElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct WireOnSystemElementTypeContent {
    pub group: super::NameXsdType,
    pub wire_port: WireOnSystemWirePortXsdType,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for WireOnSystemElementType {
    type Serializer<'x> = quick_xml_serialize::WireOnSystemElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::WireOnSystemElementTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::WireOnSystemElementTypeSerializerState::Init__),
            name: name.unwrap_or("ipxact:WireOnSystem"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for WireOnSystemElementTypeContent {
    type Serializer<'x> = quick_xml_serialize::WireOnSystemElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::WireOnSystemElementTypeContentSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::WireOnSystemElementTypeContentSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for WireOnSystemElementType {
    type Deserializer = Box<quick_xml_deserialize::WireOnSystemElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for WireOnSystemElementTypeContent {
    type Deserializer = Box<quick_xml_deserialize::WireOnSystemElementTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct WireOnInitiatorElementType {
    pub content: WireOnInitiatorElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct WireOnInitiatorElementTypeContent {
    pub presence: Option<PresenceElement>,
    pub width: Option<WidthElement>,
    pub direction: Option<DirectionXsdType>,
    pub content_128: Option<WireOnInitiatorContent128XsdType>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for WireOnInitiatorElementType {
    type Serializer<'x> = quick_xml_serialize::WireOnInitiatorElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::WireOnInitiatorElementTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::WireOnInitiatorElementTypeSerializerState::Init__),
            name: name.unwrap_or("ipxact:WireOnInitiator"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for WireOnInitiatorElementTypeContent {
    type Serializer<'x> = quick_xml_serialize::WireOnInitiatorElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::WireOnInitiatorElementTypeContentSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::WireOnInitiatorElementTypeContentSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for WireOnInitiatorElementType {
    type Deserializer = Box<quick_xml_deserialize::WireOnInitiatorElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for WireOnInitiatorElementTypeContent {
    type Deserializer = Box<quick_xml_deserialize::WireOnInitiatorElementTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct WireOnTargetElementType {
    pub content: WireOnTargetElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct WireOnTargetElementTypeContent {
    pub presence: Option<PresenceElement>,
    pub width: Option<WidthElement>,
    pub direction: Option<DirectionXsdType>,
    pub content_129: Option<WireOnTargetContent129XsdType>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for WireOnTargetElementType {
    type Serializer<'x> = quick_xml_serialize::WireOnTargetElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::WireOnTargetElementTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::WireOnTargetElementTypeSerializerState::Init__),
            name: name.unwrap_or("ipxact:WireOnTarget"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for WireOnTargetElementTypeContent {
    type Serializer<'x> = quick_xml_serialize::WireOnTargetElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::WireOnTargetElementTypeContentSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::WireOnTargetElementTypeContentSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for WireOnTargetElementType {
    type Deserializer = Box<quick_xml_deserialize::WireOnTargetElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for WireOnTargetElementTypeContent {
    type Deserializer = Box<quick_xml_deserialize::WireOnTargetElementTypeContentDeserializer>;
}
pub type AbstractionDefinitionPortsPortElement = AbstractionDefinitionPortsPortElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct WireOnSystemWirePortXsdType {
    pub content: WireOnSystemWirePortXsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct WireOnSystemWirePortXsdTypeContent {
    pub presence: Option<PresenceElement>,
    pub width: Option<WidthElement>,
    pub direction: Option<DirectionXsdType>,
    pub content_127: Option<WireOnSystemContent127XsdType>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for WireOnSystemWirePortXsdType {
    type Serializer<'x> = quick_xml_serialize::WireOnSystemWirePortXsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::WireOnSystemWirePortXsdTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::WireOnSystemWirePortXsdTypeSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for WireOnSystemWirePortXsdTypeContent {
    type Serializer<'x> = quick_xml_serialize::WireOnSystemWirePortXsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::WireOnSystemWirePortXsdTypeContentSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::WireOnSystemWirePortXsdTypeContentSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for WireOnSystemWirePortXsdType {
    type Deserializer = Box<quick_xml_deserialize::WireOnSystemWirePortXsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for WireOnSystemWirePortXsdTypeContent {
    type Deserializer = Box<quick_xml_deserialize::WireOnSystemWirePortXsdTypeContentDeserializer>;
}
pub type WidthElement = WidthElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct WireOnInitiatorContent128XsdType {
    pub content: WireOnInitiatorContent128XsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct WireOnInitiatorContent128XsdTypeContent {
    pub mode_constraints: super::constraints::AbstractionDefPortConstraintsTypeXsdType,
    pub mirrored_mode_constraints:
        Option<super::constraints::AbstractionDefPortConstraintsTypeXsdType>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for WireOnInitiatorContent128XsdType {
    type Serializer<'x> = quick_xml_serialize::WireOnInitiatorContent128XsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::WireOnInitiatorContent128XsdTypeSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::WireOnInitiatorContent128XsdTypeSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for WireOnInitiatorContent128XsdTypeContent {
    type Serializer<'x> =
        quick_xml_serialize::WireOnInitiatorContent128XsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::WireOnInitiatorContent128XsdTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::WireOnInitiatorContent128XsdTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for WireOnInitiatorContent128XsdType {
    type Deserializer = Box<quick_xml_deserialize::WireOnInitiatorContent128XsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for WireOnInitiatorContent128XsdTypeContent {
    type Deserializer =
        Box<quick_xml_deserialize::WireOnInitiatorContent128XsdTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct WireOnTargetContent129XsdType {
    pub content: WireOnTargetContent129XsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct WireOnTargetContent129XsdTypeContent {
    pub mode_constraints: super::constraints::AbstractionDefPortConstraintsTypeXsdType,
    pub mirrored_mode_constraints:
        Option<super::constraints::AbstractionDefPortConstraintsTypeXsdType>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for WireOnTargetContent129XsdType {
    type Serializer<'x> = quick_xml_serialize::WireOnTargetContent129XsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::WireOnTargetContent129XsdTypeSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::WireOnTargetContent129XsdTypeSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for WireOnTargetContent129XsdTypeContent {
    type Serializer<'x> = quick_xml_serialize::WireOnTargetContent129XsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::WireOnTargetContent129XsdTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::WireOnTargetContent129XsdTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for WireOnTargetContent129XsdType {
    type Deserializer = Box<quick_xml_deserialize::WireOnTargetContent129XsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for WireOnTargetContent129XsdTypeContent {
    type Deserializer =
        Box<quick_xml_deserialize::WireOnTargetContent129XsdTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortElementType {
    pub id: Option<super::Id>,
    pub content: AbstractionDefinitionPortsPortElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortElementTypeContent {
    pub logical_name: super::NameXsdType,
    pub display_name: Option<super::common_structures::DisplayNameElement>,
    pub short_description: Option<super::common_structures::ShortDescriptionElement>,
    pub description: Option<super::common_structures::DescriptionElement>,
    pub match_: Option<super::BooleanXsdType>,
    pub content_122: AbstractionDefinitionPortsPortContent122XsdType,
    pub vendor_extensions: Option<super::common_structures::VendorExtensionsElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for AbstractionDefinitionPortsPortElementType {
    type Serializer<'x> =
        quick_xml_serialize::AbstractionDefinitionPortsPortElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortElementTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortElementTypeSerializerState::Init__,
            ),
            name: name.unwrap_or("ipxact:AbstractionDefinitionPortsPort"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortElementTypeContent
{
    type Serializer<'x> =
        quick_xml_serialize::AbstractionDefinitionPortsPortElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortElementTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortElementTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for AbstractionDefinitionPortsPortElementType {
    type Deserializer =
        Box<quick_xml_deserialize::AbstractionDefinitionPortsPortElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortElementTypeContent
{
    type Deserializer =
        Box<quick_xml_deserialize::AbstractionDefinitionPortsPortElementTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct WireOnSystemContent127XsdType {
    pub content: WireOnSystemContent127XsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct WireOnSystemContent127XsdTypeContent {
    pub mode_constraints: super::constraints::AbstractionDefPortConstraintsTypeXsdType,
    pub mirrored_mode_constraints:
        Option<super::constraints::AbstractionDefPortConstraintsTypeXsdType>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for WireOnSystemContent127XsdType {
    type Serializer<'x> = quick_xml_serialize::WireOnSystemContent127XsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::WireOnSystemContent127XsdTypeSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::WireOnSystemContent127XsdTypeSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for WireOnSystemContent127XsdTypeContent {
    type Serializer<'x> = quick_xml_serialize::WireOnSystemContent127XsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::WireOnSystemContent127XsdTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::WireOnSystemContent127XsdTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for WireOnSystemContent127XsdType {
    type Deserializer = Box<quick_xml_deserialize::WireOnSystemContent127XsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for WireOnSystemContent127XsdTypeContent {
    type Deserializer =
        Box<quick_xml_deserialize::WireOnSystemContent127XsdTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct WidthElementType {
    pub any_attribute: AnyAttributes,
    pub minimum: Option<super::IntXsdType>,
    pub maximum: Option<super::IntXsdType>,
    pub all_bits: super::BooleanXsdType,
    pub content: super::simple_types::WidthContent118XsdType,
}
impl WidthElementType {
    #[must_use]
    pub fn default_all_bits() -> super::BooleanXsdType {
        false
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for WidthElementType {
    type Serializer<'x> = quick_xml_serialize::WidthElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::WidthElementTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::WidthElementTypeSerializerState::Init__),
            name: name.unwrap_or("ipxact:Width"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for WidthElementType {
    type Deserializer = Box<quick_xml_deserialize::WidthElementTypeDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortContent122XsdType {
    pub content: AbstractionDefinitionPortsPortContent122XsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortContent122XsdTypeContent {
    pub content_123: AbstractionDefinitionPortsPortContent123XsdType,
    pub packets: Option<PacketsElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortContent122XsdType
{
    type Serializer<'x> =
        quick_xml_serialize::AbstractionDefinitionPortsPortContent122XsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortContent122XsdTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortContent122XsdTypeSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortContent122XsdTypeContent
{
    type Serializer<'x> =
        quick_xml_serialize::AbstractionDefinitionPortsPortContent122XsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortContent122XsdTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortContent122XsdTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortContent122XsdType
{
    type Deserializer =
        Box<quick_xml_deserialize::AbstractionDefinitionPortsPortContent122XsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortContent122XsdTypeContent
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortContent122XsdTypeContentDeserializer,
    >;
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortContent123XsdType {
    pub content: AbstractionDefinitionPortsPortContent123XsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub enum AbstractionDefinitionPortsPortContent123XsdTypeContent {
    Wire(Box<WireElement>),
    Transactional(Box<AbstractionDefinitionPortsPortTransactionalElement>),
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortContent123XsdType
{
    type Serializer<'x> =
        quick_xml_serialize::AbstractionDefinitionPortsPortContent123XsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortContent123XsdTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortContent123XsdTypeSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortContent123XsdTypeContent
{
    type Serializer<'x> =
        quick_xml_serialize::AbstractionDefinitionPortsPortContent123XsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortContent123XsdTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortContent123XsdTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortContent123XsdType
{
    type Deserializer =
        Box<quick_xml_deserialize::AbstractionDefinitionPortsPortContent123XsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortContent123XsdTypeContent
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortContent123XsdTypeContentDeserializer,
    >;
}
pub type AbstractionDefinitionPortsPortTransactionalElement =
    AbstractionDefinitionPortsPortTransactionalElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortTransactionalElementType {
    pub content: AbstractionDefinitionPortsPortTransactionalElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortTransactionalElementTypeContent {
    pub qualifier: Option<super::common_structures::QualifierTypeXsdType>,
    pub on_system: Vec<AbstractionDefinitionPortsPortTransactionalOnSystemElement>,
    pub on_initiator: Option<AbstractionDefinitionPortsPortTransactionalOnInitiatorElement>,
    pub on_target: Option<AbstractionDefinitionPortsPortTransactionalOnTargetElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortTransactionalElementType
{
    type Serializer<'x> =
        quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalElementTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalElementTypeSerializerState::Init__,
            ),
            name: name.unwrap_or("ipxact:AbstractionDefinitionPortsPortTransactional"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortTransactionalElementTypeContent
{
    type Serializer<'x> = quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalElementTypeContentSerializer<
        'x,
    >;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalElementTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalElementTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortTransactionalElementType
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortTransactionalElementTypeDeserializer,
    >;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortTransactionalElementTypeContent
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortTransactionalElementTypeContentDeserializer,
    >;
}
pub type AbstractionDefinitionPortsPortTransactionalOnSystemElement =
    AbstractionDefinitionPortsPortTransactionalOnSystemElementType;
pub type AbstractionDefinitionPortsPortTransactionalOnInitiatorElement =
    AbstractionDefinitionPortsPortTransactionalOnInitiatorElementType;
pub type AbstractionDefinitionPortsPortTransactionalOnTargetElement =
    AbstractionDefinitionPortsPortTransactionalOnTargetElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortTransactionalOnSystemElementType {
    pub id: Option<super::Id>,
    pub content: AbstractionDefinitionPortsPortTransactionalOnSystemElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortTransactionalOnSystemElementTypeContent {
    pub group: super::NameXsdType,
    pub transactional_port:
        AbstractionDefinitionPortsPortTransactionalOnSystemTransactionalPortXsdType,
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortTransactionalOnSystemElementType
{
    type Serializer<'x> = quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnSystemElementTypeSerializer<
        'x,
    >;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnSystemElementTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnSystemElementTypeSerializerState::Init__,
            ),
            name: name
                .unwrap_or("ipxact:AbstractionDefinitionPortsPortTransactionalOnSystem"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortTransactionalOnSystemElementTypeContent
{
    type Serializer<'x> = quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnSystemElementTypeContentSerializer<
        'x,
    >;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnSystemElementTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnSystemElementTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortTransactionalOnSystemElementType
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortTransactionalOnSystemElementTypeDeserializer,
    >;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortTransactionalOnSystemElementTypeContent
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortTransactionalOnSystemElementTypeContentDeserializer,
    >;
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortTransactionalOnInitiatorElementType {
    pub content: AbstractionDefinitionPortsPortTransactionalOnInitiatorElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortTransactionalOnInitiatorElementTypeContent {
    pub presence: Option<PresenceElement>,
    pub initiative: Option<InitiativeElement>,
    pub kind: Option<super::port::KindElement>,
    pub bus_width: Option<super::simple_types::UnsignedPositiveIntExpressionXsdType>,
    pub protocol: Option<super::port::ProtocolElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortTransactionalOnInitiatorElementType
{
    type Serializer<'x> = quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnInitiatorElementTypeSerializer<
        'x,
    >;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnInitiatorElementTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnInitiatorElementTypeSerializerState::Init__,
            ),
            name: name
                .unwrap_or(
                    "ipxact:AbstractionDefinitionPortsPortTransactionalOnInitiator",
                ),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortTransactionalOnInitiatorElementTypeContent
{
    type Serializer<'x> = quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnInitiatorElementTypeContentSerializer<
        'x,
    >;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnInitiatorElementTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnInitiatorElementTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortTransactionalOnInitiatorElementType
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortTransactionalOnInitiatorElementTypeDeserializer,
    >;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortTransactionalOnInitiatorElementTypeContent
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortTransactionalOnInitiatorElementTypeContentDeserializer,
    >;
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortTransactionalOnTargetElementType {
    pub content: AbstractionDefinitionPortsPortTransactionalOnTargetElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortTransactionalOnTargetElementTypeContent {
    pub presence: Option<PresenceElement>,
    pub initiative: Option<InitiativeElement>,
    pub kind: Option<super::port::KindElement>,
    pub bus_width: Option<super::simple_types::UnsignedPositiveIntExpressionXsdType>,
    pub protocol: Option<super::port::ProtocolElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortTransactionalOnTargetElementType
{
    type Serializer<'x> = quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnTargetElementTypeSerializer<
        'x,
    >;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnTargetElementTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnTargetElementTypeSerializerState::Init__,
            ),
            name: name
                .unwrap_or("ipxact:AbstractionDefinitionPortsPortTransactionalOnTarget"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortTransactionalOnTargetElementTypeContent
{
    type Serializer<'x> = quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnTargetElementTypeContentSerializer<
        'x,
    >;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnTargetElementTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnTargetElementTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortTransactionalOnTargetElementType
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortTransactionalOnTargetElementTypeDeserializer,
    >;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortTransactionalOnTargetElementTypeContent
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortTransactionalOnTargetElementTypeContentDeserializer,
    >;
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortTransactionalOnSystemTransactionalPortXsdType {
    pub content: AbstractionDefinitionPortsPortTransactionalOnSystemTransactionalPortXsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortTransactionalOnSystemTransactionalPortXsdTypeContent {
    pub presence: Option<PresenceElement>,
    pub initiative: Option<InitiativeElement>,
    pub kind: Option<super::port::KindElement>,
    pub bus_width: Option<super::simple_types::UnsignedPositiveIntExpressionXsdType>,
    pub protocol: Option<super::port::ProtocolElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortTransactionalOnSystemTransactionalPortXsdType
{
    type Serializer<'x> = quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnSystemTransactionalPortXsdTypeSerializer<
        'x,
    >;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnSystemTransactionalPortXsdTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnSystemTransactionalPortXsdTypeSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortTransactionalOnSystemTransactionalPortXsdTypeContent
{
    type Serializer<'x> = quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnSystemTransactionalPortXsdTypeContentSerializer<
        'x,
    >;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnSystemTransactionalPortXsdTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnSystemTransactionalPortXsdTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortTransactionalOnSystemTransactionalPortXsdType
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortTransactionalOnSystemTransactionalPortXsdTypeDeserializer,
    >;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortTransactionalOnSystemTransactionalPortXsdTypeContent
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortTransactionalOnSystemTransactionalPortXsdTypeContentDeserializer,
    >;
}
pub type InitiativeElement = InitiativeElementType;
#[derive(Clone, Debug, PartialEq)]
pub enum InitiativeElementType {
    Requires,
    Provides,
    Both,
}
impl ::xsd_parser_types::quick_xml::SerializeBytes for InitiativeElementType {
    fn serialize_bytes(
        &self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Result<Option<::std::borrow::Cow<'_, str>>, ::xsd_parser_types::quick_xml::Error> {
        match self {
            Self::Requires => Ok(Some(::std::borrow::Cow::Borrowed("requires"))),
            Self::Provides => Ok(Some(::std::borrow::Cow::Borrowed("provides"))),
            Self::Both => Ok(Some(::std::borrow::Cow::Borrowed("both"))),
        }
    }
}
impl xsd_parser_types::quick_xml::WithSerializeToBytes for InitiativeElementType {}
impl ::xsd_parser_types::quick_xml::DeserializeBytes for InitiativeElementType {
    fn deserialize_bytes(
        helper: &mut ::xsd_parser_types::quick_xml::DeserializeHelper,
        bytes: &[u8],
    ) -> Result<Self, ::xsd_parser_types::quick_xml::Error> {
        match bytes {
            b"requires" => Ok(Self::Requires),
            b"provides" => Ok(Self::Provides),
            b"both" => Ok(Self::Both),
            x => Err(::xsd_parser_types::quick_xml::Error::from(
                ::xsd_parser_types::quick_xml::ErrorKind::UnknownOrInvalidValue(
                    ::xsd_parser_types::quick_xml::RawByteStr::from_slice(x),
                ),
            )),
        }
    }
}
impl xsd_parser_types::quick_xml::WithDeserializerFromBytes for InitiativeElementType {}
