// @generated by ipxact-codegen; do not edit by hand.
// Source schema: crates/ipxact/schema/1685-2009/index.xsd

#![allow(dead_code, unused_mut, unused_variables, clippy::all)]

pub mod quick_xml_deserialize;
pub mod quick_xml_serialize;
pub type DesignElement = DesignElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct DesignElementType {
    pub content: DesignElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct DesignElementTypeContent {
    pub versioned_identifier: DesignVersionedIdentifierXsdType,
    pub component_instances: Option<super::sub_instances::ComponentInstancesElement>,
    pub interconnections: Option<super::sub_instances::InterconnectionsElement>,
    pub ad_hoc_connections: Option<super::sub_instances::AdHocConnectionsElement>,
    pub hier_connections: Option<DesignHierConnectionsElement>,
    pub description: Option<super::common_structures::DescriptionElement>,
    pub vendor_extensions: Option<super::common_structures::VendorExtensionsElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for DesignElementType {
    type Serializer<'x> = quick_xml_serialize::DesignElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::DesignElementTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::DesignElementTypeSerializerState::Init__),
            name: name.unwrap_or("spirit:design"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for DesignElementTypeContent {
    type Serializer<'x> = quick_xml_serialize::DesignElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::DesignElementTypeContentSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::DesignElementTypeContentSerializerState::Init__),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for DesignElementType {
    type Deserializer = Box<quick_xml_deserialize::DesignElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for DesignElementTypeContent {
    type Deserializer = Box<quick_xml_deserialize::DesignElementTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct DesignVersionedIdentifierXsdType {
    pub content: DesignVersionedIdentifierXsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct DesignVersionedIdentifierXsdTypeContent {
    pub vendor: super::NameXsdType,
    pub library: super::NameXsdType,
    pub name: super::NmtokenXsdType,
    pub version: super::NmtokenXsdType,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for DesignVersionedIdentifierXsdType {
    type Serializer<'x> = quick_xml_serialize::DesignVersionedIdentifierXsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::DesignVersionedIdentifierXsdTypeSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::DesignVersionedIdentifierXsdTypeSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for DesignVersionedIdentifierXsdTypeContent {
    type Serializer<'x> =
        quick_xml_serialize::DesignVersionedIdentifierXsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::DesignVersionedIdentifierXsdTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::DesignVersionedIdentifierXsdTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for DesignVersionedIdentifierXsdType {
    type Deserializer = Box<quick_xml_deserialize::DesignVersionedIdentifierXsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for DesignVersionedIdentifierXsdTypeContent {
    type Deserializer =
        Box<quick_xml_deserialize::DesignVersionedIdentifierXsdTypeContentDeserializer>;
}
pub type DesignHierConnectionsElement = DesignHierConnectionsElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct DesignHierConnectionsElementType {
    pub content: DesignHierConnectionsElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct DesignHierConnectionsElementTypeContent {
    pub hier_connection: Vec<DesignHierConnectionsHierConnectionElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for DesignHierConnectionsElementType {
    type Serializer<'x> = quick_xml_serialize::DesignHierConnectionsElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(
            quick_xml_serialize::DesignHierConnectionsElementTypeSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::DesignHierConnectionsElementTypeSerializerState::Init__,
                ),
                name: name.unwrap_or("spirit:DesignHierConnections"),
                is_root,
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for DesignHierConnectionsElementTypeContent {
    type Serializer<'x> =
        quick_xml_serialize::DesignHierConnectionsElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::DesignHierConnectionsElementTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::DesignHierConnectionsElementTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for DesignHierConnectionsElementType {
    type Deserializer = Box<quick_xml_deserialize::DesignHierConnectionsElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for DesignHierConnectionsElementTypeContent {
    type Deserializer =
        Box<quick_xml_deserialize::DesignHierConnectionsElementTypeContentDeserializer>;
}
pub type DesignHierConnectionsHierConnectionElement =
    DesignHierConnectionsHierConnectionElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct DesignHierConnectionsHierConnectionElementType {
    pub interface_ref: super::NameXsdType,
    pub content: DesignHierConnectionsHierConnectionElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct DesignHierConnectionsHierConnectionElementTypeContent {
    pub interface: super::sub_instances::InterfaceXsdType,
    pub vendor_extensions: Option<super::common_structures::VendorExtensionsElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for DesignHierConnectionsHierConnectionElementType
{
    type Serializer<'x> =
        quick_xml_serialize::DesignHierConnectionsHierConnectionElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::DesignHierConnectionsHierConnectionElementTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::DesignHierConnectionsHierConnectionElementTypeSerializerState::Init__,
            ),
            name: name.unwrap_or("spirit:DesignHierConnectionsHierConnection"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for DesignHierConnectionsHierConnectionElementTypeContent
{
    type Serializer<'x> =
        quick_xml_serialize::DesignHierConnectionsHierConnectionElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::DesignHierConnectionsHierConnectionElementTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::DesignHierConnectionsHierConnectionElementTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for DesignHierConnectionsHierConnectionElementType
{
    type Deserializer =
        Box<quick_xml_deserialize::DesignHierConnectionsHierConnectionElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for DesignHierConnectionsHierConnectionElementTypeContent
{
    type Deserializer = Box<
        quick_xml_deserialize::DesignHierConnectionsHierConnectionElementTypeContentDeserializer,
    >;
}
