// @generated by ipxact-codegen; do not edit by hand.
// Source schema: crates/ipxact/schema/1.4/index.xsd

#![allow(dead_code, unused_mut, unused_variables, clippy::all)]

pub mod quick_xml_deserialize;
pub mod quick_xml_serialize;
pub type AbstractorGeneratorElement = InstanceGeneratorTypeXsdType;
pub type AbstractorGeneratorsElement = AbstractorGeneratorsElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractorGeneratorsElementType {
    pub content: AbstractorGeneratorsElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractorGeneratorsElementTypeContent {
    pub abstractor_generator: Vec<AbstractorGeneratorElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for AbstractorGeneratorsElementType {
    type Serializer<'x> = quick_xml_serialize::AbstractorGeneratorsElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(
            quick_xml_serialize::AbstractorGeneratorsElementTypeSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::AbstractorGeneratorsElementTypeSerializerState::Init__,
                ),
                name: name.unwrap_or("spirit:abstractorGenerators"),
                is_root,
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for AbstractorGeneratorsElementTypeContent {
    type Serializer<'x> = quick_xml_serialize::AbstractorGeneratorsElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractorGeneratorsElementTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractorGeneratorsElementTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for AbstractorGeneratorsElementType {
    type Deserializer = Box<quick_xml_deserialize::AbstractorGeneratorsElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for AbstractorGeneratorsElementTypeContent {
    type Deserializer =
        Box<quick_xml_deserialize::AbstractorGeneratorsElementTypeContentDeserializer>;
}
pub type ComponentGeneratorElement = ComponentGeneratorElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct ComponentGeneratorElementType {
    pub hidden: super::BooleanXsdType,
    pub scope: InstanceGeneratorTypeScopeXsdType,
    pub content: ComponentGeneratorElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct ComponentGeneratorElementTypeContent {
    pub name_group: GeneratorNameGroupXsdType,
    pub phase: Option<PhaseElement>,
    pub parameters: Option<super::common_structures::ParametersElement>,
    pub api_type: Option<GeneratorTypeApiTypeElement>,
    pub transport_methods: Option<GeneratorTypeTransportMethodsElement>,
    pub generator_exe: super::file::SpiritUriXsdType,
    pub vendor_extensions: Option<super::common_structures::VendorExtensionsElement>,
    pub group: Vec<super::NameXsdType>,
}
impl ComponentGeneratorElementType {
    #[must_use]
    pub fn default_hidden() -> super::BooleanXsdType {
        false
    }
    #[must_use]
    pub fn default_scope() -> InstanceGeneratorTypeScopeXsdType {
        InstanceGeneratorTypeScopeXsdType::Instance
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for ComponentGeneratorElementType {
    type Serializer<'x> = quick_xml_serialize::ComponentGeneratorElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(
            quick_xml_serialize::ComponentGeneratorElementTypeSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::ComponentGeneratorElementTypeSerializerState::Init__,
                ),
                name: name.unwrap_or("spirit:componentGenerator"),
                is_root,
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for ComponentGeneratorElementTypeContent {
    type Serializer<'x> = quick_xml_serialize::ComponentGeneratorElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::ComponentGeneratorElementTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::ComponentGeneratorElementTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for ComponentGeneratorElementType {
    type Deserializer = Box<quick_xml_deserialize::ComponentGeneratorElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for ComponentGeneratorElementTypeContent {
    type Deserializer =
        Box<quick_xml_deserialize::ComponentGeneratorElementTypeContentDeserializer>;
}
pub type ComponentGeneratorsElement = ComponentGeneratorsElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct ComponentGeneratorsElementType {
    pub content: ComponentGeneratorsElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct ComponentGeneratorsElementTypeContent {
    pub component_generator: Vec<ComponentGeneratorElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for ComponentGeneratorsElementType {
    type Serializer<'x> = quick_xml_serialize::ComponentGeneratorsElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(
            quick_xml_serialize::ComponentGeneratorsElementTypeSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::ComponentGeneratorsElementTypeSerializerState::Init__,
                ),
                name: name.unwrap_or("spirit:componentGenerators"),
                is_root,
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for ComponentGeneratorsElementTypeContent {
    type Serializer<'x> = quick_xml_serialize::ComponentGeneratorsElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::ComponentGeneratorsElementTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::ComponentGeneratorsElementTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for ComponentGeneratorsElementType {
    type Deserializer = Box<quick_xml_deserialize::ComponentGeneratorsElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for ComponentGeneratorsElementTypeContent {
    type Deserializer =
        Box<quick_xml_deserialize::ComponentGeneratorsElementTypeContentDeserializer>;
}
pub type GeneratorElement = GeneratorElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct GeneratorElementType {
    pub hidden: super::BooleanXsdType,
    pub content: GeneratorElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct GeneratorElementTypeContent {
    pub name_group: GeneratorNameGroupXsdType,
    pub phase: Option<PhaseElement>,
    pub parameters: Option<super::common_structures::ParametersElement>,
    pub api_type: Option<GeneratorTypeApiTypeElement>,
    pub transport_methods: Option<GeneratorTypeTransportMethodsElement>,
    pub generator_exe: super::file::SpiritUriXsdType,
    pub vendor_extensions: Option<super::common_structures::VendorExtensionsElement>,
}
impl GeneratorElementType {
    #[must_use]
    pub fn default_hidden() -> super::BooleanXsdType {
        false
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for GeneratorElementType {
    type Serializer<'x> = quick_xml_serialize::GeneratorElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::GeneratorElementTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::GeneratorElementTypeSerializerState::Init__),
            name: name.unwrap_or("spirit:generator"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for GeneratorElementTypeContent {
    type Serializer<'x> = quick_xml_serialize::GeneratorElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::GeneratorElementTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::GeneratorElementTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for GeneratorElementType {
    type Deserializer = Box<quick_xml_deserialize::GeneratorElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for GeneratorElementTypeContent {
    type Deserializer = Box<quick_xml_deserialize::GeneratorElementTypeContentDeserializer>;
}
pub type GeneratorChainElement = GeneratorChainElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct GeneratorChainElementType {
    pub hidden: super::BooleanXsdType,
    pub content: GeneratorChainElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct GeneratorChainElementTypeContent {
    pub versioned_identifier: GeneratorChainVersionedIdentifierXsdType,
    pub content_60: Vec<GeneratorChainContent60XsdType>,
    pub chain_group: Vec<super::NameXsdType>,
    pub display_name: Option<super::StringXsdType>,
    pub description: Option<super::StringXsdType>,
    pub choices: Option<super::auto_configure::ChoicesElement>,
    pub vendor_extensions: Option<super::common_structures::VendorExtensionsElement>,
}
impl GeneratorChainElementType {
    #[must_use]
    pub fn default_hidden() -> super::BooleanXsdType {
        false
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for GeneratorChainElementType {
    type Serializer<'x> = quick_xml_serialize::GeneratorChainElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::GeneratorChainElementTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::GeneratorChainElementTypeSerializerState::Init__),
            name: name.unwrap_or("spirit:generatorChain"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for GeneratorChainElementTypeContent {
    type Serializer<'x> = quick_xml_serialize::GeneratorChainElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::GeneratorChainElementTypeContentSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::GeneratorChainElementTypeContentSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for GeneratorChainElementType {
    type Deserializer = Box<quick_xml_deserialize::GeneratorChainElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for GeneratorChainElementTypeContent {
    type Deserializer = Box<quick_xml_deserialize::GeneratorChainElementTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct GeneratorSelectorTypeXsdType {
    pub content: GeneratorSelectorTypeXsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct GeneratorSelectorTypeXsdTypeContent {
    pub group_selector: GroupSelectorElement,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for GeneratorSelectorTypeXsdType {
    type Serializer<'x> = quick_xml_serialize::GeneratorSelectorTypeXsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(
            quick_xml_serialize::GeneratorSelectorTypeXsdTypeSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::GeneratorSelectorTypeXsdTypeSerializerState::Init__,
                ),
                name: name.unwrap_or("spirit:generatorSelectorType"),
                is_root,
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for GeneratorSelectorTypeXsdTypeContent {
    type Serializer<'x> = quick_xml_serialize::GeneratorSelectorTypeXsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::GeneratorSelectorTypeXsdTypeContentSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::GeneratorSelectorTypeXsdTypeContentSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for GeneratorSelectorTypeXsdType {
    type Deserializer = Box<quick_xml_deserialize::GeneratorSelectorTypeXsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for GeneratorSelectorTypeXsdTypeContent {
    type Deserializer = Box<quick_xml_deserialize::GeneratorSelectorTypeXsdTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct GeneratorTypeXsdType {
    pub hidden: super::BooleanXsdType,
    pub content: GeneratorTypeXsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct GeneratorTypeXsdTypeContent {
    pub name_group: GeneratorNameGroupXsdType,
    pub phase: Option<PhaseElement>,
    pub parameters: Option<super::common_structures::ParametersElement>,
    pub api_type: Option<GeneratorTypeApiTypeElement>,
    pub transport_methods: Option<GeneratorTypeTransportMethodsElement>,
    pub generator_exe: super::file::SpiritUriXsdType,
    pub vendor_extensions: Option<super::common_structures::VendorExtensionsElement>,
}
impl GeneratorTypeXsdType {
    #[must_use]
    pub fn default_hidden() -> super::BooleanXsdType {
        false
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for GeneratorTypeXsdType {
    type Serializer<'x> = quick_xml_serialize::GeneratorTypeXsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::GeneratorTypeXsdTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::GeneratorTypeXsdTypeSerializerState::Init__),
            name: name.unwrap_or("spirit:generatorType"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for GeneratorTypeXsdTypeContent {
    type Serializer<'x> = quick_xml_serialize::GeneratorTypeXsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::GeneratorTypeXsdTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::GeneratorTypeXsdTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for GeneratorTypeXsdType {
    type Deserializer = Box<quick_xml_deserialize::GeneratorTypeXsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for GeneratorTypeXsdTypeContent {
    type Deserializer = Box<quick_xml_deserialize::GeneratorTypeXsdTypeContentDeserializer>;
}
pub type GroupSelectorElement = GroupSelectorElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct GroupSelectorElementType {
    pub multiple_group_selection_operator: GroupSelectorMultipleGroupSelectionOperatorXsdType,
    pub content: GroupSelectorElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct GroupSelectorElementTypeContent {
    pub name: Vec<super::NameXsdType>,
}
impl GroupSelectorElementType {
    #[must_use]
    pub fn default_multiple_group_selection_operator()
    -> GroupSelectorMultipleGroupSelectionOperatorXsdType {
        GroupSelectorMultipleGroupSelectionOperatorXsdType::Or
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for GroupSelectorElementType {
    type Serializer<'x> = quick_xml_serialize::GroupSelectorElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::GroupSelectorElementTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::GroupSelectorElementTypeSerializerState::Init__),
            name: name.unwrap_or("spirit:groupSelector"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for GroupSelectorElementTypeContent {
    type Serializer<'x> = quick_xml_serialize::GroupSelectorElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::GroupSelectorElementTypeContentSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::GroupSelectorElementTypeContentSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for GroupSelectorElementType {
    type Deserializer = Box<quick_xml_deserialize::GroupSelectorElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for GroupSelectorElementTypeContent {
    type Deserializer = Box<quick_xml_deserialize::GroupSelectorElementTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct InstanceGeneratorTypeXsdType {
    pub hidden: super::BooleanXsdType,
    pub scope: InstanceGeneratorTypeScopeXsdType,
    pub content: InstanceGeneratorTypeXsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct InstanceGeneratorTypeXsdTypeContent {
    pub name_group: GeneratorNameGroupXsdType,
    pub phase: Option<PhaseElement>,
    pub parameters: Option<super::common_structures::ParametersElement>,
    pub api_type: Option<GeneratorTypeApiTypeElement>,
    pub transport_methods: Option<GeneratorTypeTransportMethodsElement>,
    pub generator_exe: super::file::SpiritUriXsdType,
    pub vendor_extensions: Option<super::common_structures::VendorExtensionsElement>,
    pub group: Vec<super::NameXsdType>,
}
impl InstanceGeneratorTypeXsdType {
    #[must_use]
    pub fn default_hidden() -> super::BooleanXsdType {
        false
    }
    #[must_use]
    pub fn default_scope() -> InstanceGeneratorTypeScopeXsdType {
        InstanceGeneratorTypeScopeXsdType::Instance
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for InstanceGeneratorTypeXsdType {
    type Serializer<'x> = quick_xml_serialize::InstanceGeneratorTypeXsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(
            quick_xml_serialize::InstanceGeneratorTypeXsdTypeSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::InstanceGeneratorTypeXsdTypeSerializerState::Init__,
                ),
                name: name.unwrap_or("spirit:instanceGeneratorType"),
                is_root,
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for InstanceGeneratorTypeXsdTypeContent {
    type Serializer<'x> = quick_xml_serialize::InstanceGeneratorTypeXsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::InstanceGeneratorTypeXsdTypeContentSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::InstanceGeneratorTypeXsdTypeContentSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for InstanceGeneratorTypeXsdType {
    type Deserializer = Box<quick_xml_deserialize::InstanceGeneratorTypeXsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for InstanceGeneratorTypeXsdTypeContent {
    type Deserializer = Box<quick_xml_deserialize::InstanceGeneratorTypeXsdTypeContentDeserializer>;
}
pub type PhaseElement = PhaseElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct PhaseElementType {
    pub scope: PhaseScopeTypeXsdType,
    pub content: super::FloatXsdType,
}
impl PhaseElementType {
    #[must_use]
    pub fn default_scope() -> PhaseScopeTypeXsdType {
        PhaseScopeTypeXsdType::Global
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for PhaseElementType {
    type Serializer<'x> = quick_xml_serialize::PhaseElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::PhaseElementTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::PhaseElementTypeSerializerState::Init__),
            name: name.unwrap_or("spirit:phase"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for PhaseElementType {
    type Deserializer = Box<quick_xml_deserialize::PhaseElementTypeDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub enum PhaseScopeTypeXsdType {
    Global,
    Local,
}
impl ::xsd_parser_types::quick_xml::SerializeBytes for PhaseScopeTypeXsdType {
    fn serialize_bytes(
        &self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Result<Option<::std::borrow::Cow<'_, str>>, ::xsd_parser_types::quick_xml::Error> {
        match self {
            Self::Global => Ok(Some(::std::borrow::Cow::Borrowed("global"))),
            Self::Local => Ok(Some(::std::borrow::Cow::Borrowed("local"))),
        }
    }
}
impl xsd_parser_types::quick_xml::WithSerializeToBytes for PhaseScopeTypeXsdType {}
impl ::xsd_parser_types::quick_xml::DeserializeBytes for PhaseScopeTypeXsdType {
    fn deserialize_bytes(
        helper: &mut ::xsd_parser_types::quick_xml::DeserializeHelper,
        bytes: &[u8],
    ) -> Result<Self, ::xsd_parser_types::quick_xml::Error> {
        match bytes {
            b"global" => Ok(Self::Global),
            b"local" => Ok(Self::Local),
            x => Err(::xsd_parser_types::quick_xml::Error::from(
                ::xsd_parser_types::quick_xml::ErrorKind::UnknownOrInvalidValue(
                    ::xsd_parser_types::quick_xml::RawByteStr::from_slice(x),
                ),
            )),
        }
    }
}
impl xsd_parser_types::quick_xml::WithDeserializerFromBytes for PhaseScopeTypeXsdType {}
#[derive(Clone, Debug, PartialEq)]
pub enum InstanceGeneratorTypeScopeXsdType {
    Instance,
    Entity,
}
impl ::xsd_parser_types::quick_xml::SerializeBytes for InstanceGeneratorTypeScopeXsdType {
    fn serialize_bytes(
        &self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Result<Option<::std::borrow::Cow<'_, str>>, ::xsd_parser_types::quick_xml::Error> {
        match self {
            Self::Instance => Ok(Some(::std::borrow::Cow::Borrowed("instance"))),
            Self::Entity => Ok(Some(::std::borrow::Cow::Borrowed("entity"))),
        }
    }
}
impl xsd_parser_types::quick_xml::WithSerializeToBytes for InstanceGeneratorTypeScopeXsdType {}
impl ::xsd_parser_types::quick_xml::DeserializeBytes for InstanceGeneratorTypeScopeXsdType {
    fn deserialize_bytes(
        helper: &mut ::xsd_parser_types::quick_xml::DeserializeHelper,
        bytes: &[u8],
    ) -> Result<Self, ::xsd_parser_types::quick_xml::Error> {
        match bytes {
            b"instance" => Ok(Self::Instance),
            b"entity" => Ok(Self::Entity),
            x => Err(::xsd_parser_types::quick_xml::Error::from(
                ::xsd_parser_types::quick_xml::ErrorKind::UnknownOrInvalidValue(
                    ::xsd_parser_types::quick_xml::RawByteStr::from_slice(x),
                ),
            )),
        }
    }
}
impl xsd_parser_types::quick_xml::WithDeserializerFromBytes for InstanceGeneratorTypeScopeXsdType {}
#[derive(Clone, Debug, PartialEq)]
pub struct GeneratorNameGroupXsdType {
    pub content: GeneratorNameGroupXsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct GeneratorNameGroupXsdTypeContent {
    pub name: super::NameXsdType,
    pub display_name: Option<super::StringXsdType>,
    pub description: Option<super::StringXsdType>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for GeneratorNameGroupXsdType {
    type Serializer<'x> = quick_xml_serialize::GeneratorNameGroupXsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::GeneratorNameGroupXsdTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::GeneratorNameGroupXsdTypeSerializerState::Init__),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for GeneratorNameGroupXsdTypeContent {
    type Serializer<'x> = quick_xml_serialize::GeneratorNameGroupXsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::GeneratorNameGroupXsdTypeContentSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::GeneratorNameGroupXsdTypeContentSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for GeneratorNameGroupXsdType {
    type Deserializer = Box<quick_xml_deserialize::GeneratorNameGroupXsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for GeneratorNameGroupXsdTypeContent {
    type Deserializer = Box<quick_xml_deserialize::GeneratorNameGroupXsdTypeContentDeserializer>;
}
pub type GeneratorTypeApiTypeElement = GeneratorTypeApiTypeElementType;
pub type GeneratorTypeTransportMethodsElement = GeneratorTypeTransportMethodsElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct GeneratorChainVersionedIdentifierXsdType {
    pub content: GeneratorChainVersionedIdentifierXsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct GeneratorChainVersionedIdentifierXsdTypeContent {
    pub vendor: super::NameXsdType,
    pub library: super::NameXsdType,
    pub name: super::NmtokenXsdType,
    pub version: super::NmtokenXsdType,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for GeneratorChainVersionedIdentifierXsdType {
    type Serializer<'x> =
        quick_xml_serialize::GeneratorChainVersionedIdentifierXsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::GeneratorChainVersionedIdentifierXsdTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::GeneratorChainVersionedIdentifierXsdTypeSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for GeneratorChainVersionedIdentifierXsdTypeContent
{
    type Serializer<'x> =
        quick_xml_serialize::GeneratorChainVersionedIdentifierXsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::GeneratorChainVersionedIdentifierXsdTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::GeneratorChainVersionedIdentifierXsdTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for GeneratorChainVersionedIdentifierXsdType {
    type Deserializer =
        Box<quick_xml_deserialize::GeneratorChainVersionedIdentifierXsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for GeneratorChainVersionedIdentifierXsdTypeContent
{
    type Deserializer =
        Box<quick_xml_deserialize::GeneratorChainVersionedIdentifierXsdTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct GeneratorChainContent60XsdType {
    pub content: GeneratorChainContent60XsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub enum GeneratorChainContent60XsdTypeContent {
    GeneratorChainSelector(Box<GeneratorChainGeneratorChainSelectorElement>),
    ComponentGeneratorSelector(Box<GeneratorSelectorTypeXsdType>),
    Generator(Box<GeneratorElement>),
}
impl ::xsd_parser_types::quick_xml::WithSerializer for GeneratorChainContent60XsdType {
    type Serializer<'x> = quick_xml_serialize::GeneratorChainContent60XsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::GeneratorChainContent60XsdTypeSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::GeneratorChainContent60XsdTypeSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for GeneratorChainContent60XsdTypeContent {
    type Serializer<'x> = quick_xml_serialize::GeneratorChainContent60XsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::GeneratorChainContent60XsdTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::GeneratorChainContent60XsdTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for GeneratorChainContent60XsdType {
    type Deserializer = Box<quick_xml_deserialize::GeneratorChainContent60XsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for GeneratorChainContent60XsdTypeContent {
    type Deserializer =
        Box<quick_xml_deserialize::GeneratorChainContent60XsdTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub enum GroupSelectorMultipleGroupSelectionOperatorXsdType {
    And,
    Or,
}
impl ::xsd_parser_types::quick_xml::SerializeBytes
    for GroupSelectorMultipleGroupSelectionOperatorXsdType
{
    fn serialize_bytes(
        &self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Result<Option<::std::borrow::Cow<'_, str>>, ::xsd_parser_types::quick_xml::Error> {
        match self {
            Self::And => Ok(Some(::std::borrow::Cow::Borrowed("and"))),
            Self::Or => Ok(Some(::std::borrow::Cow::Borrowed("or"))),
        }
    }
}
impl xsd_parser_types::quick_xml::WithSerializeToBytes
    for GroupSelectorMultipleGroupSelectionOperatorXsdType
{
}
impl ::xsd_parser_types::quick_xml::DeserializeBytes
    for GroupSelectorMultipleGroupSelectionOperatorXsdType
{
    fn deserialize_bytes(
        helper: &mut ::xsd_parser_types::quick_xml::DeserializeHelper,
        bytes: &[u8],
    ) -> Result<Self, ::xsd_parser_types::quick_xml::Error> {
        match bytes {
            b"and" => Ok(Self::And),
            b"or" => Ok(Self::Or),
            x => Err(::xsd_parser_types::quick_xml::Error::from(
                ::xsd_parser_types::quick_xml::ErrorKind::UnknownOrInvalidValue(
                    ::xsd_parser_types::quick_xml::RawByteStr::from_slice(x),
                ),
            )),
        }
    }
}
impl xsd_parser_types::quick_xml::WithDeserializerFromBytes
    for GroupSelectorMultipleGroupSelectionOperatorXsdType
{
}
#[derive(Clone, Debug, PartialEq)]
pub enum GeneratorTypeApiTypeElementType {
    Tgi,
    None,
}
impl ::xsd_parser_types::quick_xml::SerializeBytes for GeneratorTypeApiTypeElementType {
    fn serialize_bytes(
        &self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Result<Option<::std::borrow::Cow<'_, str>>, ::xsd_parser_types::quick_xml::Error> {
        match self {
            Self::Tgi => Ok(Some(::std::borrow::Cow::Borrowed("TGI"))),
            Self::None => Ok(Some(::std::borrow::Cow::Borrowed("none"))),
        }
    }
}
impl xsd_parser_types::quick_xml::WithSerializeToBytes for GeneratorTypeApiTypeElementType {}
impl ::xsd_parser_types::quick_xml::DeserializeBytes for GeneratorTypeApiTypeElementType {
    fn deserialize_bytes(
        helper: &mut ::xsd_parser_types::quick_xml::DeserializeHelper,
        bytes: &[u8],
    ) -> Result<Self, ::xsd_parser_types::quick_xml::Error> {
        match bytes {
            b"TGI" => Ok(Self::Tgi),
            b"none" => Ok(Self::None),
            x => Err(::xsd_parser_types::quick_xml::Error::from(
                ::xsd_parser_types::quick_xml::ErrorKind::UnknownOrInvalidValue(
                    ::xsd_parser_types::quick_xml::RawByteStr::from_slice(x),
                ),
            )),
        }
    }
}
impl xsd_parser_types::quick_xml::WithDeserializerFromBytes for GeneratorTypeApiTypeElementType {}
#[derive(Clone, Debug, PartialEq)]
pub struct GeneratorTypeTransportMethodsElementType {
    pub content: GeneratorTypeTransportMethodsElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct GeneratorTypeTransportMethodsElementTypeContent {
    pub transport_method: GeneratorTypeTransportMethodsTransportMethodElement,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for GeneratorTypeTransportMethodsElementType {
    type Serializer<'x> =
        quick_xml_serialize::GeneratorTypeTransportMethodsElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::GeneratorTypeTransportMethodsElementTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::GeneratorTypeTransportMethodsElementTypeSerializerState::Init__,
            ),
            name: name.unwrap_or("spirit:GeneratorTypeTransportMethods"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for GeneratorTypeTransportMethodsElementTypeContent
{
    type Serializer<'x> =
        quick_xml_serialize::GeneratorTypeTransportMethodsElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::GeneratorTypeTransportMethodsElementTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::GeneratorTypeTransportMethodsElementTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for GeneratorTypeTransportMethodsElementType {
    type Deserializer =
        Box<quick_xml_deserialize::GeneratorTypeTransportMethodsElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for GeneratorTypeTransportMethodsElementTypeContent
{
    type Deserializer =
        Box<quick_xml_deserialize::GeneratorTypeTransportMethodsElementTypeContentDeserializer>;
}
pub type GeneratorChainGeneratorChainSelectorElement =
    GeneratorChainGeneratorChainSelectorElementType;
pub type GeneratorTypeTransportMethodsTransportMethodElement =
    GeneratorTypeTransportMethodsTransportMethodElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct GeneratorChainGeneratorChainSelectorElementType {
    pub unique: super::BooleanXsdType,
    pub content: GeneratorChainGeneratorChainSelectorElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub enum GeneratorChainGeneratorChainSelectorElementTypeContent {
    GroupSelector(Box<GroupSelectorElement>),
    GeneratorChainRef(Box<super::identifier::LibraryRefTypeXsdType>),
}
impl GeneratorChainGeneratorChainSelectorElementType {
    #[must_use]
    pub fn default_unique() -> super::BooleanXsdType {
        false
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for GeneratorChainGeneratorChainSelectorElementType
{
    type Serializer<'x> =
        quick_xml_serialize::GeneratorChainGeneratorChainSelectorElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::GeneratorChainGeneratorChainSelectorElementTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::GeneratorChainGeneratorChainSelectorElementTypeSerializerState::Init__,
            ),
            name: name.unwrap_or("spirit:GeneratorChainGeneratorChainSelector"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for GeneratorChainGeneratorChainSelectorElementTypeContent
{
    type Serializer<'x> =
        quick_xml_serialize::GeneratorChainGeneratorChainSelectorElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::GeneratorChainGeneratorChainSelectorElementTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::GeneratorChainGeneratorChainSelectorElementTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for GeneratorChainGeneratorChainSelectorElementType
{
    type Deserializer =
        Box<quick_xml_deserialize::GeneratorChainGeneratorChainSelectorElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for GeneratorChainGeneratorChainSelectorElementTypeContent
{
    type Deserializer = Box<
        quick_xml_deserialize::GeneratorChainGeneratorChainSelectorElementTypeContentDeserializer,
    >;
}
#[derive(Clone, Debug, PartialEq)]
pub enum GeneratorTypeTransportMethodsTransportMethodElementType {
    File,
}
impl ::xsd_parser_types::quick_xml::SerializeBytes
    for GeneratorTypeTransportMethodsTransportMethodElementType
{
    fn serialize_bytes(
        &self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Result<Option<::std::borrow::Cow<'_, str>>, ::xsd_parser_types::quick_xml::Error> {
        match self {
            Self::File => Ok(Some(::std::borrow::Cow::Borrowed("file"))),
        }
    }
}
impl xsd_parser_types::quick_xml::WithSerializeToBytes
    for GeneratorTypeTransportMethodsTransportMethodElementType
{
}
impl ::xsd_parser_types::quick_xml::DeserializeBytes
    for GeneratorTypeTransportMethodsTransportMethodElementType
{
    fn deserialize_bytes(
        helper: &mut ::xsd_parser_types::quick_xml::DeserializeHelper,
        bytes: &[u8],
    ) -> Result<Self, ::xsd_parser_types::quick_xml::Error> {
        match bytes {
            b"file" => Ok(Self::File),
            x => Err(::xsd_parser_types::quick_xml::Error::from(
                ::xsd_parser_types::quick_xml::ErrorKind::UnknownOrInvalidValue(
                    ::xsd_parser_types::quick_xml::RawByteStr::from_slice(x),
                ),
            )),
        }
    }
}
impl xsd_parser_types::quick_xml::WithDeserializerFromBytes
    for GeneratorTypeTransportMethodsTransportMethodElementType
{
}
