// @generated by ipxact-codegen; do not edit by hand.
// Source schema: crates/ipxact/schema/1685-2014/index.xsd

#![allow(dead_code, unused_mut, unused_variables, clippy::all)]

pub mod quick_xml_deserialize;
pub mod quick_xml_serialize;
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractorPortTypeXsdType {
    pub id: Option<super::Id>,
    pub content: AbstractorPortTypeXsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractorPortTypeXsdTypeContent {
    pub name_group_port: PortNameGroupPortXsdType,
    pub content_94: PortContent94XsdType,
    pub content_97: AbstractorPortContent97XsdType,
    pub content_100: AbstractorPortContent100XsdType,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for AbstractorPortTypeXsdType {
    type Serializer<'x> = quick_xml_serialize::AbstractorPortTypeXsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::AbstractorPortTypeXsdTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::AbstractorPortTypeXsdTypeSerializerState::Init__),
            name: name.unwrap_or("ipxact:abstractorPortType"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for AbstractorPortTypeXsdTypeContent {
    type Serializer<'x> = quick_xml_serialize::AbstractorPortTypeXsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::AbstractorPortTypeXsdTypeContentSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::AbstractorPortTypeXsdTypeContentSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for AbstractorPortTypeXsdType {
    type Deserializer = Box<quick_xml_deserialize::AbstractorPortTypeXsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for AbstractorPortTypeXsdTypeContent {
    type Deserializer = Box<quick_xml_deserialize::AbstractorPortTypeXsdTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractorPortWireTypeXsdType {
    pub all_logical_directions_allowed: super::BooleanXsdType,
    pub content: AbstractorPortWireTypeXsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractorPortWireTypeXsdTypeContent {
    pub direction: ComponentPortDirectionTypeXsdType,
    pub vectors: Option<super::common_structures::VectorsElement>,
    pub wire_type_defs: Option<WireTypeDefsElement>,
    pub drivers: Option<super::signal_drivers::DriversElement>,
}
impl AbstractorPortWireTypeXsdType {
    #[must_use]
    pub fn default_all_logical_directions_allowed() -> super::BooleanXsdType {
        false
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for AbstractorPortWireTypeXsdType {
    type Serializer<'x> = quick_xml_serialize::AbstractorPortWireTypeXsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(
            quick_xml_serialize::AbstractorPortWireTypeXsdTypeSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::AbstractorPortWireTypeXsdTypeSerializerState::Init__,
                ),
                name: name.unwrap_or("ipxact:abstractorPortWireType"),
                is_root,
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for AbstractorPortWireTypeXsdTypeContent {
    type Serializer<'x> = quick_xml_serialize::AbstractorPortWireTypeXsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractorPortWireTypeXsdTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractorPortWireTypeXsdTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for AbstractorPortWireTypeXsdType {
    type Deserializer = Box<quick_xml_deserialize::AbstractorPortWireTypeXsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for AbstractorPortWireTypeXsdTypeContent {
    type Deserializer =
        Box<quick_xml_deserialize::AbstractorPortWireTypeXsdTypeContentDeserializer>;
}
pub type ArraysElement = super::common_structures::ConfigurableArraysXsdType;
pub type BusWidthElement = super::simple_types::UnsignedIntExpressionXsdType;
#[derive(Clone, Debug, PartialEq)]
pub enum ComponentPortDirectionTypeXsdType {
    In,
    Out,
    Inout,
    Phantom,
}
impl ::xsd_parser_types::quick_xml::SerializeBytes for ComponentPortDirectionTypeXsdType {
    fn serialize_bytes(
        &self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Result<Option<::std::borrow::Cow<'_, str>>, ::xsd_parser_types::quick_xml::Error> {
        match self {
            Self::In => Ok(Some(::std::borrow::Cow::Borrowed("in"))),
            Self::Out => Ok(Some(::std::borrow::Cow::Borrowed("out"))),
            Self::Inout => Ok(Some(::std::borrow::Cow::Borrowed("inout"))),
            Self::Phantom => Ok(Some(::std::borrow::Cow::Borrowed("phantom"))),
        }
    }
}
impl xsd_parser_types::quick_xml::WithSerializeToBytes for ComponentPortDirectionTypeXsdType {}
impl ::xsd_parser_types::quick_xml::DeserializeBytes for ComponentPortDirectionTypeXsdType {
    fn deserialize_bytes(
        helper: &mut ::xsd_parser_types::quick_xml::DeserializeHelper,
        bytes: &[u8],
    ) -> Result<Self, ::xsd_parser_types::quick_xml::Error> {
        match bytes {
            b"in" => Ok(Self::In),
            b"out" => Ok(Self::Out),
            b"inout" => Ok(Self::Inout),
            b"phantom" => Ok(Self::Phantom),
            x => Err(::xsd_parser_types::quick_xml::Error::from(
                ::xsd_parser_types::quick_xml::ErrorKind::UnknownOrInvalidValue(
                    ::xsd_parser_types::quick_xml::RawByteStr::from_slice(x),
                ),
            )),
        }
    }
}
impl xsd_parser_types::quick_xml::WithDeserializerFromBytes for ComponentPortDirectionTypeXsdType {}
pub type InitiativeElement = InitiativeTypeXsdType;
#[derive(Clone, Debug, PartialEq)]
pub enum InitiativeTypeXsdType {
    Requires,
    Provides,
    Both,
    Phantom,
}
impl ::xsd_parser_types::quick_xml::SerializeBytes for InitiativeTypeXsdType {
    fn serialize_bytes(
        &self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Result<Option<::std::borrow::Cow<'_, str>>, ::xsd_parser_types::quick_xml::Error> {
        match self {
            Self::Requires => Ok(Some(::std::borrow::Cow::Borrowed("requires"))),
            Self::Provides => Ok(Some(::std::borrow::Cow::Borrowed("provides"))),
            Self::Both => Ok(Some(::std::borrow::Cow::Borrowed("both"))),
            Self::Phantom => Ok(Some(::std::borrow::Cow::Borrowed("phantom"))),
        }
    }
}
impl xsd_parser_types::quick_xml::WithSerializeToBytes for InitiativeTypeXsdType {}
impl ::xsd_parser_types::quick_xml::DeserializeBytes for InitiativeTypeXsdType {
    fn deserialize_bytes(
        helper: &mut ::xsd_parser_types::quick_xml::DeserializeHelper,
        bytes: &[u8],
    ) -> Result<Self, ::xsd_parser_types::quick_xml::Error> {
        match bytes {
            b"requires" => Ok(Self::Requires),
            b"provides" => Ok(Self::Provides),
            b"both" => Ok(Self::Both),
            b"phantom" => Ok(Self::Phantom),
            x => Err(::xsd_parser_types::quick_xml::Error::from(
                ::xsd_parser_types::quick_xml::ErrorKind::UnknownOrInvalidValue(
                    ::xsd_parser_types::quick_xml::RawByteStr::from_slice(x),
                ),
            )),
        }
    }
}
impl xsd_parser_types::quick_xml::WithDeserializerFromBytes for InitiativeTypeXsdType {}
pub type KindElement = KindElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct KindElementType {
    pub custom: Option<super::StringXsdType>,
    pub content: KindTypeXsdType,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for KindElementType {
    type Serializer<'x> = quick_xml_serialize::KindElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::KindElementTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::KindElementTypeSerializerState::Init__),
            name: name.unwrap_or("ipxact:kind"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for KindElementType {
    type Deserializer = Box<quick_xml_deserialize::KindElementTypeDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub enum KindTypeXsdType {
    TlmPort,
    TlmSocket,
    SimpleSocket,
    MultiSocket,
    Custom,
}
impl ::xsd_parser_types::quick_xml::SerializeBytes for KindTypeXsdType {
    fn serialize_bytes(
        &self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Result<Option<::std::borrow::Cow<'_, str>>, ::xsd_parser_types::quick_xml::Error> {
        match self {
            Self::TlmPort => Ok(Some(::std::borrow::Cow::Borrowed("tlm_port"))),
            Self::TlmSocket => Ok(Some(::std::borrow::Cow::Borrowed("tlm_socket"))),
            Self::SimpleSocket => Ok(Some(::std::borrow::Cow::Borrowed("simple_socket"))),
            Self::MultiSocket => Ok(Some(::std::borrow::Cow::Borrowed("multi_socket"))),
            Self::Custom => Ok(Some(::std::borrow::Cow::Borrowed("custom"))),
        }
    }
}
impl xsd_parser_types::quick_xml::WithSerializeToBytes for KindTypeXsdType {}
impl ::xsd_parser_types::quick_xml::DeserializeBytes for KindTypeXsdType {
    fn deserialize_bytes(
        helper: &mut ::xsd_parser_types::quick_xml::DeserializeHelper,
        bytes: &[u8],
    ) -> Result<Self, ::xsd_parser_types::quick_xml::Error> {
        match bytes {
            b"tlm_port" => Ok(Self::TlmPort),
            b"tlm_socket" => Ok(Self::TlmSocket),
            b"simple_socket" => Ok(Self::SimpleSocket),
            b"multi_socket" => Ok(Self::MultiSocket),
            b"custom" => Ok(Self::Custom),
            x => Err(::xsd_parser_types::quick_xml::Error::from(
                ::xsd_parser_types::quick_xml::ErrorKind::UnknownOrInvalidValue(
                    ::xsd_parser_types::quick_xml::RawByteStr::from_slice(x),
                ),
            )),
        }
    }
}
impl xsd_parser_types::quick_xml::WithDeserializerFromBytes for KindTypeXsdType {}
pub type PayloadElement = PayloadElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct PayloadElementType {
    pub content: PayloadElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct PayloadElementTypeContent {
    pub name: Option<super::StringXsdType>,
    pub type_: PayloadTypeElement,
    pub extension: Option<PayloadExtensionElement>,
    pub vendor_extensions: Option<super::common_structures::VendorExtensionsElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for PayloadElementType {
    type Serializer<'x> = quick_xml_serialize::PayloadElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::PayloadElementTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::PayloadElementTypeSerializerState::Init__),
            name: name.unwrap_or("ipxact:payload"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for PayloadElementTypeContent {
    type Serializer<'x> = quick_xml_serialize::PayloadElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::PayloadElementTypeContentSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::PayloadElementTypeContentSerializerState::Init__),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for PayloadElementType {
    type Deserializer = Box<quick_xml_deserialize::PayloadElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for PayloadElementTypeContent {
    type Deserializer = Box<quick_xml_deserialize::PayloadElementTypeContentDeserializer>;
}
pub type PortElement = PortTypeXsdType;
#[derive(Clone, Debug, PartialEq)]
pub struct PortAccessTypeXsdType {
    pub content: PortAccessTypeXsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct PortAccessTypeXsdTypeContent {
    pub port_access_type: Option<PortAccessTypeElement>,
    pub access_handles: Option<PortAccessTypeAccessHandlesElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for PortAccessTypeXsdType {
    type Serializer<'x> = quick_xml_serialize::PortAccessTypeXsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::PortAccessTypeXsdTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::PortAccessTypeXsdTypeSerializerState::Init__),
            name: name.unwrap_or("ipxact:portAccessType"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for PortAccessTypeXsdTypeContent {
    type Serializer<'x> = quick_xml_serialize::PortAccessTypeXsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::PortAccessTypeXsdTypeContentSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::PortAccessTypeXsdTypeContentSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for PortAccessTypeXsdType {
    type Deserializer = Box<quick_xml_deserialize::PortAccessTypeXsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for PortAccessTypeXsdTypeContent {
    type Deserializer = Box<quick_xml_deserialize::PortAccessTypeXsdTypeContentDeserializer>;
}
pub type PortAccessTypeElement = SimplePortAccessTypeXsdType;
#[derive(Clone, Debug, PartialEq)]
pub struct PortTransactionalTypeXsdType {
    pub all_logical_initiatives_allowed: super::BooleanXsdType,
    pub content: PortTransactionalTypeXsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct PortTransactionalTypeXsdTypeContent {
    pub initiative: InitiativeElement,
    pub kind: Option<KindElement>,
    pub bus_width: Option<BusWidthElement>,
    pub protocol: Option<ProtocolElement>,
    pub trans_type_defs: Option<TransTypeDefsElement>,
    pub connection: Option<PortTransactionalTypeConnectionElement>,
}
impl PortTransactionalTypeXsdType {
    #[must_use]
    pub fn default_all_logical_initiatives_allowed() -> super::BooleanXsdType {
        false
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for PortTransactionalTypeXsdType {
    type Serializer<'x> = quick_xml_serialize::PortTransactionalTypeXsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(
            quick_xml_serialize::PortTransactionalTypeXsdTypeSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::PortTransactionalTypeXsdTypeSerializerState::Init__,
                ),
                name: name.unwrap_or("ipxact:portTransactionalType"),
                is_root,
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for PortTransactionalTypeXsdTypeContent {
    type Serializer<'x> = quick_xml_serialize::PortTransactionalTypeXsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::PortTransactionalTypeXsdTypeContentSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::PortTransactionalTypeXsdTypeContentSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for PortTransactionalTypeXsdType {
    type Deserializer = Box<quick_xml_deserialize::PortTransactionalTypeXsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for PortTransactionalTypeXsdTypeContent {
    type Deserializer = Box<quick_xml_deserialize::PortTransactionalTypeXsdTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct PortTypeXsdType {
    pub id: Option<super::Id>,
    pub content: PortTypeXsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct PortTypeXsdTypeContent {
    pub name_group_port: PortNameGroupPortXsdType,
    pub is_present: Option<super::common_structures::IsPresentElement>,
    pub content_94: PortContent94XsdType,
    pub arrays: Option<ArraysElement>,
    pub access: Option<PortAccessTypeXsdType>,
    pub vendor_extensions: Option<super::common_structures::VendorExtensionsElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for PortTypeXsdType {
    type Serializer<'x> = quick_xml_serialize::PortTypeXsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::PortTypeXsdTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::PortTypeXsdTypeSerializerState::Init__),
            name: name.unwrap_or("ipxact:portType"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for PortTypeXsdTypeContent {
    type Serializer<'x> = quick_xml_serialize::PortTypeXsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::PortTypeXsdTypeContentSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::PortTypeXsdTypeContentSerializerState::Init__),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for PortTypeXsdType {
    type Deserializer = Box<quick_xml_deserialize::PortTypeXsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for PortTypeXsdTypeContent {
    type Deserializer = Box<quick_xml_deserialize::PortTypeXsdTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct PortWireTypeXsdType {
    pub all_logical_directions_allowed: super::BooleanXsdType,
    pub content: PortWireTypeXsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct PortWireTypeXsdTypeContent {
    pub direction: ComponentPortDirectionTypeXsdType,
    pub vectors: Option<super::common_structures::VectorsElement>,
    pub wire_type_defs: Option<WireTypeDefsElement>,
    pub drivers: Option<super::signal_drivers::DriversElement>,
    pub constraint_sets: Option<super::constraints::ConstraintSetsElement>,
}
impl PortWireTypeXsdType {
    #[must_use]
    pub fn default_all_logical_directions_allowed() -> super::BooleanXsdType {
        false
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for PortWireTypeXsdType {
    type Serializer<'x> = quick_xml_serialize::PortWireTypeXsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::PortWireTypeXsdTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::PortWireTypeXsdTypeSerializerState::Init__),
            name: name.unwrap_or("ipxact:portWireType"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for PortWireTypeXsdTypeContent {
    type Serializer<'x> = quick_xml_serialize::PortWireTypeXsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::PortWireTypeXsdTypeContentSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::PortWireTypeXsdTypeContentSerializerState::Init__),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for PortWireTypeXsdType {
    type Deserializer = Box<quick_xml_deserialize::PortWireTypeXsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for PortWireTypeXsdTypeContent {
    type Deserializer = Box<quick_xml_deserialize::PortWireTypeXsdTypeContentDeserializer>;
}
pub type ProtocolElement = ProtocolElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct ProtocolElementType {
    pub content: ProtocolElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct ProtocolElementTypeContent {
    pub protocol_type: ProtocolProtocolTypeElement,
    pub payload: Option<PayloadElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for ProtocolElementType {
    type Serializer<'x> = quick_xml_serialize::ProtocolElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::ProtocolElementTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::ProtocolElementTypeSerializerState::Init__),
            name: name.unwrap_or("ipxact:protocol"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for ProtocolElementTypeContent {
    type Serializer<'x> = quick_xml_serialize::ProtocolElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::ProtocolElementTypeContentSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::ProtocolElementTypeContentSerializerState::Init__),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for ProtocolElementType {
    type Deserializer = Box<quick_xml_deserialize::ProtocolElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for ProtocolElementTypeContent {
    type Deserializer = Box<quick_xml_deserialize::ProtocolElementTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub enum ProtocolTypeTypeXsdType {
    Tlm,
    Custom,
}
impl ::xsd_parser_types::quick_xml::SerializeBytes for ProtocolTypeTypeXsdType {
    fn serialize_bytes(
        &self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Result<Option<::std::borrow::Cow<'_, str>>, ::xsd_parser_types::quick_xml::Error> {
        match self {
            Self::Tlm => Ok(Some(::std::borrow::Cow::Borrowed("tlm"))),
            Self::Custom => Ok(Some(::std::borrow::Cow::Borrowed("custom"))),
        }
    }
}
impl xsd_parser_types::quick_xml::WithSerializeToBytes for ProtocolTypeTypeXsdType {}
impl ::xsd_parser_types::quick_xml::DeserializeBytes for ProtocolTypeTypeXsdType {
    fn deserialize_bytes(
        helper: &mut ::xsd_parser_types::quick_xml::DeserializeHelper,
        bytes: &[u8],
    ) -> Result<Self, ::xsd_parser_types::quick_xml::Error> {
        match bytes {
            b"tlm" => Ok(Self::Tlm),
            b"custom" => Ok(Self::Custom),
            x => Err(::xsd_parser_types::quick_xml::Error::from(
                ::xsd_parser_types::quick_xml::ErrorKind::UnknownOrInvalidValue(
                    ::xsd_parser_types::quick_xml::RawByteStr::from_slice(x),
                ),
            )),
        }
    }
}
impl xsd_parser_types::quick_xml::WithDeserializerFromBytes for ProtocolTypeTypeXsdType {}
pub type ServiceTypeDefElement = ServiceTypeDefElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct ServiceTypeDefElementType {
    pub id: Option<super::Id>,
    pub content: ServiceTypeDefElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct ServiceTypeDefElementTypeContent {
    pub type_name: ServiceTypeDefTypeNameElement,
    pub type_definition: Vec<ServiceTypeDefTypeDefinitionElement>,
    pub type_parameters: Option<TypeParametersElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for ServiceTypeDefElementType {
    type Serializer<'x> = quick_xml_serialize::ServiceTypeDefElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::ServiceTypeDefElementTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::ServiceTypeDefElementTypeSerializerState::Init__),
            name: name.unwrap_or("ipxact:serviceTypeDef"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for ServiceTypeDefElementTypeContent {
    type Serializer<'x> = quick_xml_serialize::ServiceTypeDefElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::ServiceTypeDefElementTypeContentSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::ServiceTypeDefElementTypeContentSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for ServiceTypeDefElementType {
    type Deserializer = Box<quick_xml_deserialize::ServiceTypeDefElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for ServiceTypeDefElementTypeContent {
    type Deserializer = Box<quick_xml_deserialize::ServiceTypeDefElementTypeContentDeserializer>;
}
pub type ServiceTypeDefsElement = ServiceTypeDefsElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct ServiceTypeDefsElementType {
    pub content: ServiceTypeDefsElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct ServiceTypeDefsElementTypeContent {
    pub service_type_def: Vec<ServiceTypeDefElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for ServiceTypeDefsElementType {
    type Serializer<'x> = quick_xml_serialize::ServiceTypeDefsElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::ServiceTypeDefsElementTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::ServiceTypeDefsElementTypeSerializerState::Init__),
            name: name.unwrap_or("ipxact:serviceTypeDefs"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for ServiceTypeDefsElementTypeContent {
    type Serializer<'x> = quick_xml_serialize::ServiceTypeDefsElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::ServiceTypeDefsElementTypeContentSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::ServiceTypeDefsElementTypeContentSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for ServiceTypeDefsElementType {
    type Deserializer = Box<quick_xml_deserialize::ServiceTypeDefsElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for ServiceTypeDefsElementTypeContent {
    type Deserializer = Box<quick_xml_deserialize::ServiceTypeDefsElementTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub enum SimplePortAccessTypeXsdType {
    Ref,
    Ptr,
}
impl ::xsd_parser_types::quick_xml::SerializeBytes for SimplePortAccessTypeXsdType {
    fn serialize_bytes(
        &self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Result<Option<::std::borrow::Cow<'_, str>>, ::xsd_parser_types::quick_xml::Error> {
        match self {
            Self::Ref => Ok(Some(::std::borrow::Cow::Borrowed("ref"))),
            Self::Ptr => Ok(Some(::std::borrow::Cow::Borrowed("ptr"))),
        }
    }
}
impl xsd_parser_types::quick_xml::WithSerializeToBytes for SimplePortAccessTypeXsdType {}
impl ::xsd_parser_types::quick_xml::DeserializeBytes for SimplePortAccessTypeXsdType {
    fn deserialize_bytes(
        helper: &mut ::xsd_parser_types::quick_xml::DeserializeHelper,
        bytes: &[u8],
    ) -> Result<Self, ::xsd_parser_types::quick_xml::Error> {
        match bytes {
            b"ref" => Ok(Self::Ref),
            b"ptr" => Ok(Self::Ptr),
            x => Err(::xsd_parser_types::quick_xml::Error::from(
                ::xsd_parser_types::quick_xml::ErrorKind::UnknownOrInvalidValue(
                    ::xsd_parser_types::quick_xml::RawByteStr::from_slice(x),
                ),
            )),
        }
    }
}
impl xsd_parser_types::quick_xml::WithDeserializerFromBytes for SimplePortAccessTypeXsdType {}
pub type TransTypeDefElement = TransTypeDefElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct TransTypeDefElementType {
    pub id: Option<super::Id>,
    pub content: TransTypeDefElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct TransTypeDefElementTypeContent {
    pub type_name: Option<TransTypeDefTypeNameElement>,
    pub type_definition: Vec<TransTypeDefTypeDefinitionElement>,
    pub type_parameters: Option<TypeParametersElement>,
    pub view_ref: Vec<TransTypeDefViewRefElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for TransTypeDefElementType {
    type Serializer<'x> = quick_xml_serialize::TransTypeDefElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::TransTypeDefElementTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::TransTypeDefElementTypeSerializerState::Init__),
            name: name.unwrap_or("ipxact:transTypeDef"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for TransTypeDefElementTypeContent {
    type Serializer<'x> = quick_xml_serialize::TransTypeDefElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::TransTypeDefElementTypeContentSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::TransTypeDefElementTypeContentSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for TransTypeDefElementType {
    type Deserializer = Box<quick_xml_deserialize::TransTypeDefElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for TransTypeDefElementTypeContent {
    type Deserializer = Box<quick_xml_deserialize::TransTypeDefElementTypeContentDeserializer>;
}
pub type TransTypeDefsElement = TransTypeDefsElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct TransTypeDefsElementType {
    pub content: TransTypeDefsElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct TransTypeDefsElementTypeContent {
    pub trans_type_def: Vec<TransTypeDefElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for TransTypeDefsElementType {
    type Serializer<'x> = quick_xml_serialize::TransTypeDefsElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::TransTypeDefsElementTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::TransTypeDefsElementTypeSerializerState::Init__),
            name: name.unwrap_or("ipxact:transTypeDefs"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for TransTypeDefsElementTypeContent {
    type Serializer<'x> = quick_xml_serialize::TransTypeDefsElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::TransTypeDefsElementTypeContentSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::TransTypeDefsElementTypeContentSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for TransTypeDefsElementType {
    type Deserializer = Box<quick_xml_deserialize::TransTypeDefsElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for TransTypeDefsElementTypeContent {
    type Deserializer = Box<quick_xml_deserialize::TransTypeDefsElementTypeContentDeserializer>;
}
pub type TypeParameterElement = super::common_structures::ModuleParameterTypeXsdType;
pub type TypeParametersElement = TypeParametersElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct TypeParametersElementType {
    pub content: TypeParametersElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct TypeParametersElementTypeContent {
    pub type_parameter: Vec<TypeParameterElement>,
    pub service_type_def: Vec<ServiceTypeDefElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for TypeParametersElementType {
    type Serializer<'x> = quick_xml_serialize::TypeParametersElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::TypeParametersElementTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::TypeParametersElementTypeSerializerState::Init__),
            name: name.unwrap_or("ipxact:typeParameters"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for TypeParametersElementTypeContent {
    type Serializer<'x> = quick_xml_serialize::TypeParametersElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::TypeParametersElementTypeContentSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::TypeParametersElementTypeContentSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for TypeParametersElementType {
    type Deserializer = Box<quick_xml_deserialize::TypeParametersElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for TypeParametersElementTypeContent {
    type Deserializer = Box<quick_xml_deserialize::TypeParametersElementTypeContentDeserializer>;
}
pub type WireTypeDefElement = WireTypeDefElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct WireTypeDefElementType {
    pub id: Option<super::Id>,
    pub content: WireTypeDefElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct WireTypeDefElementTypeContent {
    pub type_name: Option<WireTypeDefTypeNameElement>,
    pub type_definition: Vec<WireTypeDefTypeDefinitionElement>,
    pub view_ref: Vec<WireTypeDefViewRefElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for WireTypeDefElementType {
    type Serializer<'x> = quick_xml_serialize::WireTypeDefElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::WireTypeDefElementTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::WireTypeDefElementTypeSerializerState::Init__),
            name: name.unwrap_or("ipxact:wireTypeDef"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for WireTypeDefElementTypeContent {
    type Serializer<'x> = quick_xml_serialize::WireTypeDefElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::WireTypeDefElementTypeContentSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::WireTypeDefElementTypeContentSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for WireTypeDefElementType {
    type Deserializer = Box<quick_xml_deserialize::WireTypeDefElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for WireTypeDefElementTypeContent {
    type Deserializer = Box<quick_xml_deserialize::WireTypeDefElementTypeContentDeserializer>;
}
pub type WireTypeDefsElement = WireTypeDefsElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct WireTypeDefsElementType {
    pub content: WireTypeDefsElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct WireTypeDefsElementTypeContent {
    pub wire_type_def: Vec<WireTypeDefElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for WireTypeDefsElementType {
    type Serializer<'x> = quick_xml_serialize::WireTypeDefsElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::WireTypeDefsElementTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::WireTypeDefsElementTypeSerializerState::Init__),
            name: name.unwrap_or("ipxact:wireTypeDefs"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for WireTypeDefsElementTypeContent {
    type Serializer<'x> = quick_xml_serialize::WireTypeDefsElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::WireTypeDefsElementTypeContentSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::WireTypeDefsElementTypeContentSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for WireTypeDefsElementType {
    type Deserializer = Box<quick_xml_deserialize::WireTypeDefsElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for WireTypeDefsElementTypeContent {
    type Deserializer = Box<quick_xml_deserialize::WireTypeDefsElementTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct PortNameGroupPortXsdType {
    pub content: PortNameGroupPortXsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct PortNameGroupPortXsdTypeContent {
    pub name: super::simple_types::PortNameXsdType,
    pub display_name: Option<super::common_structures::DisplayNameElement>,
    pub description: Option<super::common_structures::DescriptionElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for PortNameGroupPortXsdType {
    type Serializer<'x> = quick_xml_serialize::PortNameGroupPortXsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::PortNameGroupPortXsdTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::PortNameGroupPortXsdTypeSerializerState::Init__),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for PortNameGroupPortXsdTypeContent {
    type Serializer<'x> = quick_xml_serialize::PortNameGroupPortXsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::PortNameGroupPortXsdTypeContentSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::PortNameGroupPortXsdTypeContentSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for PortNameGroupPortXsdType {
    type Deserializer = Box<quick_xml_deserialize::PortNameGroupPortXsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for PortNameGroupPortXsdTypeContent {
    type Deserializer = Box<quick_xml_deserialize::PortNameGroupPortXsdTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct PortContent94XsdType {
    pub content: PortContent94XsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub enum PortContent94XsdTypeContent {
    Wire(Box<PortWireTypeXsdType>),
    Transactional(Box<PortTransactionalTypeXsdType>),
}
impl ::xsd_parser_types::quick_xml::WithSerializer for PortContent94XsdType {
    type Serializer<'x> = quick_xml_serialize::PortContent94XsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::PortContent94XsdTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::PortContent94XsdTypeSerializerState::Init__),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for PortContent94XsdTypeContent {
    type Serializer<'x> = quick_xml_serialize::PortContent94XsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::PortContent94XsdTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::PortContent94XsdTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for PortContent94XsdType {
    type Deserializer = Box<quick_xml_deserialize::PortContent94XsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for PortContent94XsdTypeContent {
    type Deserializer = Box<quick_xml_deserialize::PortContent94XsdTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractorPortContent97XsdType {
    pub content: AbstractorPortContent97XsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractorPortContent97XsdTypeContent {
    pub name_group_port: AbstractorPortNameGroupPortXsdType,
    pub is_present: Option<super::common_structures::IsPresentElement>,
    pub content_98: AbstractorPortContent98XsdType,
    pub content_99: AbstractorPortContent99XsdType,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for AbstractorPortContent97XsdType {
    type Serializer<'x> = quick_xml_serialize::AbstractorPortContent97XsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::AbstractorPortContent97XsdTypeSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::AbstractorPortContent97XsdTypeSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for AbstractorPortContent97XsdTypeContent {
    type Serializer<'x> = quick_xml_serialize::AbstractorPortContent97XsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractorPortContent97XsdTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractorPortContent97XsdTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for AbstractorPortContent97XsdType {
    type Deserializer = Box<quick_xml_deserialize::AbstractorPortContent97XsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for AbstractorPortContent97XsdTypeContent {
    type Deserializer =
        Box<quick_xml_deserialize::AbstractorPortContent97XsdTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractorPortContent100XsdType {
    pub content: AbstractorPortContent100XsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractorPortContent100XsdTypeContent {
    pub vendor_extensions: Option<super::common_structures::VendorExtensionsElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for AbstractorPortContent100XsdType {
    type Serializer<'x> = quick_xml_serialize::AbstractorPortContent100XsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::AbstractorPortContent100XsdTypeSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::AbstractorPortContent100XsdTypeSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for AbstractorPortContent100XsdTypeContent {
    type Serializer<'x> = quick_xml_serialize::AbstractorPortContent100XsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractorPortContent100XsdTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractorPortContent100XsdTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for AbstractorPortContent100XsdType {
    type Deserializer = Box<quick_xml_deserialize::AbstractorPortContent100XsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for AbstractorPortContent100XsdTypeContent {
    type Deserializer =
        Box<quick_xml_deserialize::AbstractorPortContent100XsdTypeContentDeserializer>;
}
pub type PayloadTypeElement = PayloadTypeElementType;
pub type PayloadExtensionElement = PayloadExtensionElementType;
pub type PortAccessTypeAccessHandlesElement = PortAccessTypeAccessHandlesElementType;
pub type PortTransactionalTypeConnectionElement = PortTransactionalTypeConnectionElementType;
pub type ProtocolProtocolTypeElement = ProtocolProtocolTypeElementType;
pub type ServiceTypeDefTypeNameElement = ServiceTypeDefTypeNameElementType;
pub type ServiceTypeDefTypeDefinitionElement = ServiceTypeDefTypeDefinitionElementType;
pub type TransTypeDefTypeNameElement = TransTypeDefTypeNameElementType;
pub type TransTypeDefTypeDefinitionElement = TransTypeDefTypeDefinitionElementType;
pub type TransTypeDefViewRefElement = TransTypeDefViewRefElementType;
pub type WireTypeDefTypeNameElement = WireTypeDefTypeNameElementType;
pub type WireTypeDefTypeDefinitionElement = WireTypeDefTypeDefinitionElementType;
pub type WireTypeDefViewRefElement = WireTypeDefViewRefElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractorPortNameGroupPortXsdType {
    pub content: AbstractorPortNameGroupPortXsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractorPortNameGroupPortXsdTypeContent {
    pub name: super::simple_types::PortNameXsdType,
    pub display_name: Option<super::common_structures::DisplayNameElement>,
    pub description: Option<super::common_structures::DescriptionElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for AbstractorPortNameGroupPortXsdType {
    type Serializer<'x> = quick_xml_serialize::AbstractorPortNameGroupPortXsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::AbstractorPortNameGroupPortXsdTypeSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::AbstractorPortNameGroupPortXsdTypeSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for AbstractorPortNameGroupPortXsdTypeContent {
    type Serializer<'x> =
        quick_xml_serialize::AbstractorPortNameGroupPortXsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractorPortNameGroupPortXsdTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractorPortNameGroupPortXsdTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for AbstractorPortNameGroupPortXsdType {
    type Deserializer = Box<quick_xml_deserialize::AbstractorPortNameGroupPortXsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for AbstractorPortNameGroupPortXsdTypeContent {
    type Deserializer =
        Box<quick_xml_deserialize::AbstractorPortNameGroupPortXsdTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractorPortContent98XsdType {
    pub content: AbstractorPortContent98XsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub enum AbstractorPortContent98XsdTypeContent {
    Wire(Box<AbstractorPortWireTypeXsdType>),
    Transactional(Box<PortTransactionalTypeXsdType>),
}
impl ::xsd_parser_types::quick_xml::WithSerializer for AbstractorPortContent98XsdType {
    type Serializer<'x> = quick_xml_serialize::AbstractorPortContent98XsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::AbstractorPortContent98XsdTypeSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::AbstractorPortContent98XsdTypeSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for AbstractorPortContent98XsdTypeContent {
    type Serializer<'x> = quick_xml_serialize::AbstractorPortContent98XsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractorPortContent98XsdTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractorPortContent98XsdTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for AbstractorPortContent98XsdType {
    type Deserializer = Box<quick_xml_deserialize::AbstractorPortContent98XsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for AbstractorPortContent98XsdTypeContent {
    type Deserializer =
        Box<quick_xml_deserialize::AbstractorPortContent98XsdTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractorPortContent99XsdType {
    pub content: AbstractorPortContent99XsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractorPortContent99XsdTypeContent {
    pub access: Option<PortAccessTypeXsdType>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for AbstractorPortContent99XsdType {
    type Serializer<'x> = quick_xml_serialize::AbstractorPortContent99XsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::AbstractorPortContent99XsdTypeSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::AbstractorPortContent99XsdTypeSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for AbstractorPortContent99XsdTypeContent {
    type Serializer<'x> = quick_xml_serialize::AbstractorPortContent99XsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractorPortContent99XsdTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractorPortContent99XsdTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for AbstractorPortContent99XsdType {
    type Deserializer = Box<quick_xml_deserialize::AbstractorPortContent99XsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for AbstractorPortContent99XsdTypeContent {
    type Deserializer =
        Box<quick_xml_deserialize::AbstractorPortContent99XsdTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub enum PayloadTypeElementType {
    Generic,
    Specific,
}
impl ::xsd_parser_types::quick_xml::SerializeBytes for PayloadTypeElementType {
    fn serialize_bytes(
        &self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Result<Option<::std::borrow::Cow<'_, str>>, ::xsd_parser_types::quick_xml::Error> {
        match self {
            Self::Generic => Ok(Some(::std::borrow::Cow::Borrowed("generic"))),
            Self::Specific => Ok(Some(::std::borrow::Cow::Borrowed("specific"))),
        }
    }
}
impl xsd_parser_types::quick_xml::WithSerializeToBytes for PayloadTypeElementType {}
impl ::xsd_parser_types::quick_xml::DeserializeBytes for PayloadTypeElementType {
    fn deserialize_bytes(
        helper: &mut ::xsd_parser_types::quick_xml::DeserializeHelper,
        bytes: &[u8],
    ) -> Result<Self, ::xsd_parser_types::quick_xml::Error> {
        match bytes {
            b"generic" => Ok(Self::Generic),
            b"specific" => Ok(Self::Specific),
            x => Err(::xsd_parser_types::quick_xml::Error::from(
                ::xsd_parser_types::quick_xml::ErrorKind::UnknownOrInvalidValue(
                    ::xsd_parser_types::quick_xml::RawByteStr::from_slice(x),
                ),
            )),
        }
    }
}
impl xsd_parser_types::quick_xml::WithDeserializerFromBytes for PayloadTypeElementType {}
#[derive(Clone, Debug, PartialEq)]
pub struct PayloadExtensionElementType {
    pub mandatory: super::BooleanXsdType,
    pub content: super::StringXsdType,
}
impl PayloadExtensionElementType {
    #[must_use]
    pub fn default_mandatory() -> super::BooleanXsdType {
        false
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for PayloadExtensionElementType {
    type Serializer<'x> = quick_xml_serialize::PayloadExtensionElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::PayloadExtensionElementTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::PayloadExtensionElementTypeSerializerState::Init__,
            ),
            name: name.unwrap_or("ipxact:PayloadExtension"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for PayloadExtensionElementType {
    type Deserializer = Box<quick_xml_deserialize::PayloadExtensionElementTypeDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct PortAccessTypeAccessHandlesElementType {
    pub content: Vec<PortAccessTypeAccessHandlesElementTypeContent>,
}
#[derive(Clone, Debug, PartialEq)]
pub struct PortAccessTypeAccessHandlesElementTypeContent {
    pub access_handle: super::common_structures::LeafAccessHandleXsdType,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for PortAccessTypeAccessHandlesElementType {
    type Serializer<'x> = quick_xml_serialize::PortAccessTypeAccessHandlesElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::PortAccessTypeAccessHandlesElementTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::PortAccessTypeAccessHandlesElementTypeSerializerState::Init__,
            ),
            name: name.unwrap_or("ipxact:PortAccessTypeAccessHandles"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for PortAccessTypeAccessHandlesElementTypeContent
{
    type Serializer<'x> =
        quick_xml_serialize::PortAccessTypeAccessHandlesElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::PortAccessTypeAccessHandlesElementTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::PortAccessTypeAccessHandlesElementTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for PortAccessTypeAccessHandlesElementType {
    type Deserializer =
        Box<quick_xml_deserialize::PortAccessTypeAccessHandlesElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for PortAccessTypeAccessHandlesElementTypeContent
{
    type Deserializer =
        Box<quick_xml_deserialize::PortAccessTypeAccessHandlesElementTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct PortTransactionalTypeConnectionElementType {
    pub content: PortTransactionalTypeConnectionElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct PortTransactionalTypeConnectionElementTypeContent {
    pub max_connections: Option<super::simple_types::UnsignedIntExpressionXsdType>,
    pub min_connections: Option<super::simple_types::UnsignedIntExpressionXsdType>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for PortTransactionalTypeConnectionElementType {
    type Serializer<'x> =
        quick_xml_serialize::PortTransactionalTypeConnectionElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::PortTransactionalTypeConnectionElementTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::PortTransactionalTypeConnectionElementTypeSerializerState::Init__,
            ),
            name: name.unwrap_or("ipxact:PortTransactionalTypeConnection"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for PortTransactionalTypeConnectionElementTypeContent
{
    type Serializer<'x> =
        quick_xml_serialize::PortTransactionalTypeConnectionElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::PortTransactionalTypeConnectionElementTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::PortTransactionalTypeConnectionElementTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for PortTransactionalTypeConnectionElementType
{
    type Deserializer =
        Box<quick_xml_deserialize::PortTransactionalTypeConnectionElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for PortTransactionalTypeConnectionElementTypeContent
{
    type Deserializer =
        Box<quick_xml_deserialize::PortTransactionalTypeConnectionElementTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct ProtocolProtocolTypeElementType {
    pub custom: Option<super::StringXsdType>,
    pub content: ProtocolTypeTypeXsdType,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for ProtocolProtocolTypeElementType {
    type Serializer<'x> = quick_xml_serialize::ProtocolProtocolTypeElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(
            quick_xml_serialize::ProtocolProtocolTypeElementTypeSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::ProtocolProtocolTypeElementTypeSerializerState::Init__,
                ),
                name: name.unwrap_or("ipxact:ProtocolProtocolType"),
                is_root,
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for ProtocolProtocolTypeElementType {
    type Deserializer = Box<quick_xml_deserialize::ProtocolProtocolTypeElementTypeDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct ServiceTypeDefTypeNameElementType {
    pub implicit: super::BooleanXsdType,
    pub content: super::StringXsdType,
}
impl ServiceTypeDefTypeNameElementType {
    #[must_use]
    pub fn default_implicit() -> super::BooleanXsdType {
        false
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for ServiceTypeDefTypeNameElementType {
    type Serializer<'x> = quick_xml_serialize::ServiceTypeDefTypeNameElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(
            quick_xml_serialize::ServiceTypeDefTypeNameElementTypeSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::ServiceTypeDefTypeNameElementTypeSerializerState::Init__,
                ),
                name: name.unwrap_or("ipxact:ServiceTypeDefTypeName"),
                is_root,
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for ServiceTypeDefTypeNameElementType {
    type Deserializer = Box<quick_xml_deserialize::ServiceTypeDefTypeNameElementTypeDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct ServiceTypeDefTypeDefinitionElementType {
    pub id: Option<super::Id>,
    pub content: super::StringXsdType,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for ServiceTypeDefTypeDefinitionElementType {
    type Serializer<'x> =
        quick_xml_serialize::ServiceTypeDefTypeDefinitionElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::ServiceTypeDefTypeDefinitionElementTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::ServiceTypeDefTypeDefinitionElementTypeSerializerState::Init__,
            ),
            name: name.unwrap_or("ipxact:ServiceTypeDefTypeDefinition"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for ServiceTypeDefTypeDefinitionElementType {
    type Deserializer =
        Box<quick_xml_deserialize::ServiceTypeDefTypeDefinitionElementTypeDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct TransTypeDefTypeNameElementType {
    pub exact: super::BooleanXsdType,
    pub content: super::StringXsdType,
}
impl TransTypeDefTypeNameElementType {
    #[must_use]
    pub fn default_exact() -> super::BooleanXsdType {
        true
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for TransTypeDefTypeNameElementType {
    type Serializer<'x> = quick_xml_serialize::TransTypeDefTypeNameElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(
            quick_xml_serialize::TransTypeDefTypeNameElementTypeSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::TransTypeDefTypeNameElementTypeSerializerState::Init__,
                ),
                name: name.unwrap_or("ipxact:TransTypeDefTypeName"),
                is_root,
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for TransTypeDefTypeNameElementType {
    type Deserializer = Box<quick_xml_deserialize::TransTypeDefTypeNameElementTypeDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct TransTypeDefTypeDefinitionElementType {
    pub id: Option<super::Id>,
    pub content: super::StringXsdType,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for TransTypeDefTypeDefinitionElementType {
    type Serializer<'x> = quick_xml_serialize::TransTypeDefTypeDefinitionElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::TransTypeDefTypeDefinitionElementTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::TransTypeDefTypeDefinitionElementTypeSerializerState::Init__,
            ),
            name: name.unwrap_or("ipxact:TransTypeDefTypeDefinition"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for TransTypeDefTypeDefinitionElementType {
    type Deserializer =
        Box<quick_xml_deserialize::TransTypeDefTypeDefinitionElementTypeDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct TransTypeDefViewRefElementType {
    pub id: Option<super::Id>,
    pub content: super::NmtokenXsdType,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for TransTypeDefViewRefElementType {
    type Serializer<'x> = quick_xml_serialize::TransTypeDefViewRefElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(
            quick_xml_serialize::TransTypeDefViewRefElementTypeSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::TransTypeDefViewRefElementTypeSerializerState::Init__,
                ),
                name: name.unwrap_or("ipxact:TransTypeDefViewRef"),
                is_root,
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for TransTypeDefViewRefElementType {
    type Deserializer = Box<quick_xml_deserialize::TransTypeDefViewRefElementTypeDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct WireTypeDefTypeNameElementType {
    pub constrained: super::BooleanXsdType,
    pub content: super::StringXsdType,
}
impl WireTypeDefTypeNameElementType {
    #[must_use]
    pub fn default_constrained() -> super::BooleanXsdType {
        false
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for WireTypeDefTypeNameElementType {
    type Serializer<'x> = quick_xml_serialize::WireTypeDefTypeNameElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(
            quick_xml_serialize::WireTypeDefTypeNameElementTypeSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::WireTypeDefTypeNameElementTypeSerializerState::Init__,
                ),
                name: name.unwrap_or("ipxact:WireTypeDefTypeName"),
                is_root,
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for WireTypeDefTypeNameElementType {
    type Deserializer = Box<quick_xml_deserialize::WireTypeDefTypeNameElementTypeDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct WireTypeDefTypeDefinitionElementType {
    pub id: Option<super::Id>,
    pub content: super::StringXsdType,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for WireTypeDefTypeDefinitionElementType {
    type Serializer<'x> = quick_xml_serialize::WireTypeDefTypeDefinitionElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::WireTypeDefTypeDefinitionElementTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::WireTypeDefTypeDefinitionElementTypeSerializerState::Init__,
            ),
            name: name.unwrap_or("ipxact:WireTypeDefTypeDefinition"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for WireTypeDefTypeDefinitionElementType {
    type Deserializer =
        Box<quick_xml_deserialize::WireTypeDefTypeDefinitionElementTypeDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct WireTypeDefViewRefElementType {
    pub id: Option<super::Id>,
    pub content: super::NmtokenXsdType,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for WireTypeDefViewRefElementType {
    type Serializer<'x> = quick_xml_serialize::WireTypeDefViewRefElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(
            quick_xml_serialize::WireTypeDefViewRefElementTypeSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::WireTypeDefViewRefElementTypeSerializerState::Init__,
                ),
                name: name.unwrap_or("ipxact:WireTypeDefViewRef"),
                is_root,
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for WireTypeDefViewRefElementType {
    type Deserializer = Box<quick_xml_deserialize::WireTypeDefViewRefElementTypeDeserializer>;
}
