// @generated by ipxact-codegen; do not edit by hand.
// Source schema: crates/ipxact/schema/1.4/index.xsd

#![allow(dead_code, unused_mut, unused_variables, clippy::all)]

pub mod quick_xml_deserialize;
pub mod quick_xml_serialize;
pub type AbstractionDefinitionElement = AbstractionDefinitionElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionElementType {
    pub content: AbstractionDefinitionElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionElementTypeContent {
    pub versioned_identifier: AbstractionDefinitionVersionedIdentifierXsdType,
    pub bus_type: super::identifier::LibraryRefTypeXsdType,
    pub extends: Option<super::identifier::LibraryRefTypeXsdType>,
    pub ports: AbstractionDefinitionPortsElement,
    pub description: Option<super::StringXsdType>,
    pub vendor_extensions: Option<super::common_structures::VendorExtensionsElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for AbstractionDefinitionElementType {
    type Serializer<'x> = quick_xml_serialize::AbstractionDefinitionElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(
            quick_xml_serialize::AbstractionDefinitionElementTypeSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::AbstractionDefinitionElementTypeSerializerState::Init__,
                ),
                name: name.unwrap_or("spirit:abstractionDefinition"),
                is_root,
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for AbstractionDefinitionElementTypeContent {
    type Serializer<'x> =
        quick_xml_serialize::AbstractionDefinitionElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionElementTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionElementTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for AbstractionDefinitionElementType {
    type Deserializer = Box<quick_xml_deserialize::AbstractionDefinitionElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for AbstractionDefinitionElementTypeContent {
    type Deserializer =
        Box<quick_xml_deserialize::AbstractionDefinitionElementTypeContentDeserializer>;
}
pub type PresenceElement = PresenceElementType;
#[derive(Clone, Debug, PartialEq)]
pub enum PresenceElementType {
    Required,
    Illegal,
    Optional,
}
impl ::xsd_parser_types::quick_xml::SerializeBytes for PresenceElementType {
    fn serialize_bytes(
        &self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Result<Option<::std::borrow::Cow<'_, str>>, ::xsd_parser_types::quick_xml::Error> {
        match self {
            Self::Required => Ok(Some(::std::borrow::Cow::Borrowed("required"))),
            Self::Illegal => Ok(Some(::std::borrow::Cow::Borrowed("illegal"))),
            Self::Optional => Ok(Some(::std::borrow::Cow::Borrowed("optional"))),
        }
    }
}
impl xsd_parser_types::quick_xml::WithSerializeToBytes for PresenceElementType {}
impl ::xsd_parser_types::quick_xml::DeserializeBytes for PresenceElementType {
    fn deserialize_bytes(
        helper: &mut ::xsd_parser_types::quick_xml::DeserializeHelper,
        bytes: &[u8],
    ) -> Result<Self, ::xsd_parser_types::quick_xml::Error> {
        match bytes {
            b"required" => Ok(Self::Required),
            b"illegal" => Ok(Self::Illegal),
            b"optional" => Ok(Self::Optional),
            x => Err(::xsd_parser_types::quick_xml::Error::from(
                ::xsd_parser_types::quick_xml::ErrorKind::UnknownOrInvalidValue(
                    ::xsd_parser_types::quick_xml::RawByteStr::from_slice(x),
                ),
            )),
        }
    }
}
impl xsd_parser_types::quick_xml::WithDeserializerFromBytes for PresenceElementType {}
#[derive(Clone, Debug, PartialEq)]
pub struct ServiceTypeXsdType {
    pub content: ServiceTypeXsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct ServiceTypeXsdTypeContent {
    pub initiative: ServiceTypeInitiativeElement,
    pub type_name: Vec<ServiceTypeTypeNameElement>,
    pub vendor_extensions: Option<super::common_structures::VendorExtensionsElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for ServiceTypeXsdType {
    type Serializer<'x> = quick_xml_serialize::ServiceTypeXsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::ServiceTypeXsdTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::ServiceTypeXsdTypeSerializerState::Init__),
            name: name.unwrap_or("spirit:serviceType"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for ServiceTypeXsdTypeContent {
    type Serializer<'x> = quick_xml_serialize::ServiceTypeXsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::ServiceTypeXsdTypeContentSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::ServiceTypeXsdTypeContentSerializerState::Init__),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for ServiceTypeXsdType {
    type Deserializer = Box<quick_xml_deserialize::ServiceTypeXsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for ServiceTypeXsdTypeContent {
    type Deserializer = Box<quick_xml_deserialize::ServiceTypeXsdTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionVersionedIdentifierXsdType {
    pub content: AbstractionDefinitionVersionedIdentifierXsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionVersionedIdentifierXsdTypeContent {
    pub vendor: super::NameXsdType,
    pub library: super::NameXsdType,
    pub name: super::NmtokenXsdType,
    pub version: super::NmtokenXsdType,
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionVersionedIdentifierXsdType
{
    type Serializer<'x> =
        quick_xml_serialize::AbstractionDefinitionVersionedIdentifierXsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionVersionedIdentifierXsdTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionVersionedIdentifierXsdTypeSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionVersionedIdentifierXsdTypeContent
{
    type Serializer<'x> =
        quick_xml_serialize::AbstractionDefinitionVersionedIdentifierXsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionVersionedIdentifierXsdTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionVersionedIdentifierXsdTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionVersionedIdentifierXsdType
{
    type Deserializer =
        Box<quick_xml_deserialize::AbstractionDefinitionVersionedIdentifierXsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionVersionedIdentifierXsdTypeContent
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionVersionedIdentifierXsdTypeContentDeserializer,
    >;
}
pub type AbstractionDefinitionPortsElement = AbstractionDefinitionPortsElementType;
pub type ServiceTypeInitiativeElement = ServiceTypeInitiativeElementType;
pub type ServiceTypeTypeNameElement = ServiceTypeTypeNameElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsElementType {
    pub content: AbstractionDefinitionPortsElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsElementTypeContent {
    pub port: Vec<AbstractionDefinitionPortsPortElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for AbstractionDefinitionPortsElementType {
    type Serializer<'x> = quick_xml_serialize::AbstractionDefinitionPortsElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::AbstractionDefinitionPortsElementTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsElementTypeSerializerState::Init__,
            ),
            name: name.unwrap_or("spirit:AbstractionDefinitionPorts"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsElementTypeContent
{
    type Serializer<'x> =
        quick_xml_serialize::AbstractionDefinitionPortsElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionPortsElementTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsElementTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for AbstractionDefinitionPortsElementType {
    type Deserializer =
        Box<quick_xml_deserialize::AbstractionDefinitionPortsElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsElementTypeContent
{
    type Deserializer =
        Box<quick_xml_deserialize::AbstractionDefinitionPortsElementTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub enum ServiceTypeInitiativeElementType {
    Requires,
    Provides,
    Both,
}
impl ::xsd_parser_types::quick_xml::SerializeBytes for ServiceTypeInitiativeElementType {
    fn serialize_bytes(
        &self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Result<Option<::std::borrow::Cow<'_, str>>, ::xsd_parser_types::quick_xml::Error> {
        match self {
            Self::Requires => Ok(Some(::std::borrow::Cow::Borrowed("requires"))),
            Self::Provides => Ok(Some(::std::borrow::Cow::Borrowed("provides"))),
            Self::Both => Ok(Some(::std::borrow::Cow::Borrowed("both"))),
        }
    }
}
impl xsd_parser_types::quick_xml::WithSerializeToBytes for ServiceTypeInitiativeElementType {}
impl ::xsd_parser_types::quick_xml::DeserializeBytes for ServiceTypeInitiativeElementType {
    fn deserialize_bytes(
        helper: &mut ::xsd_parser_types::quick_xml::DeserializeHelper,
        bytes: &[u8],
    ) -> Result<Self, ::xsd_parser_types::quick_xml::Error> {
        match bytes {
            b"requires" => Ok(Self::Requires),
            b"provides" => Ok(Self::Provides),
            b"both" => Ok(Self::Both),
            x => Err(::xsd_parser_types::quick_xml::Error::from(
                ::xsd_parser_types::quick_xml::ErrorKind::UnknownOrInvalidValue(
                    ::xsd_parser_types::quick_xml::RawByteStr::from_slice(x),
                ),
            )),
        }
    }
}
impl xsd_parser_types::quick_xml::WithDeserializerFromBytes for ServiceTypeInitiativeElementType {}
#[derive(Clone, Debug, PartialEq)]
pub struct ServiceTypeTypeNameElementType {
    pub implicit: super::BooleanXsdType,
    pub content: super::AnyUriXsdType,
}
impl ServiceTypeTypeNameElementType {
    #[must_use]
    pub fn default_implicit() -> super::BooleanXsdType {
        false
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for ServiceTypeTypeNameElementType {
    type Serializer<'x> = quick_xml_serialize::ServiceTypeTypeNameElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(
            quick_xml_serialize::ServiceTypeTypeNameElementTypeSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::ServiceTypeTypeNameElementTypeSerializerState::Init__,
                ),
                name: name.unwrap_or("spirit:ServiceTypeTypeName"),
                is_root,
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for ServiceTypeTypeNameElementType {
    type Deserializer = Box<quick_xml_deserialize::ServiceTypeTypeNameElementTypeDeserializer>;
}
pub type AbstractionDefinitionPortsPortElement = AbstractionDefinitionPortsPortElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortElementType {
    pub content: AbstractionDefinitionPortsPortElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortElementTypeContent {
    pub logical_name: super::NameXsdType,
    pub display_name: Option<super::StringXsdType>,
    pub description: Option<super::StringXsdType>,
    pub content_168: AbstractionDefinitionPortsPortContent168XsdType,
    pub vendor_extensions: Option<super::common_structures::VendorExtensionsElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for AbstractionDefinitionPortsPortElementType {
    type Serializer<'x> =
        quick_xml_serialize::AbstractionDefinitionPortsPortElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortElementTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortElementTypeSerializerState::Init__,
            ),
            name: name.unwrap_or("spirit:AbstractionDefinitionPortsPort"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortElementTypeContent
{
    type Serializer<'x> =
        quick_xml_serialize::AbstractionDefinitionPortsPortElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortElementTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortElementTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for AbstractionDefinitionPortsPortElementType {
    type Deserializer =
        Box<quick_xml_deserialize::AbstractionDefinitionPortsPortElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortElementTypeContent
{
    type Deserializer =
        Box<quick_xml_deserialize::AbstractionDefinitionPortsPortElementTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortContent168XsdType {
    pub content: AbstractionDefinitionPortsPortContent168XsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub enum AbstractionDefinitionPortsPortContent168XsdTypeContent {
    Wire(Box<AbstractionDefinitionPortsPortWireElement>),
    Transactional(Box<AbstractionDefinitionPortsPortTransactionalElement>),
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortContent168XsdType
{
    type Serializer<'x> =
        quick_xml_serialize::AbstractionDefinitionPortsPortContent168XsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortContent168XsdTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortContent168XsdTypeSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortContent168XsdTypeContent
{
    type Serializer<'x> =
        quick_xml_serialize::AbstractionDefinitionPortsPortContent168XsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortContent168XsdTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortContent168XsdTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortContent168XsdType
{
    type Deserializer =
        Box<quick_xml_deserialize::AbstractionDefinitionPortsPortContent168XsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortContent168XsdTypeContent
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortContent168XsdTypeContentDeserializer,
    >;
}
pub type AbstractionDefinitionPortsPortWireElement = AbstractionDefinitionPortsPortWireElementType;
pub type AbstractionDefinitionPortsPortTransactionalElement =
    AbstractionDefinitionPortsPortTransactionalElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortWireElementType {
    pub content: AbstractionDefinitionPortsPortWireElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortWireElementTypeContent {
    pub qualifier: Option<AbstractionDefinitionPortsPortWireQualifierElement>,
    pub on_system: Vec<AbstractionDefinitionPortsPortWireOnSystemElement>,
    pub on_master: Option<AbstractionDefinitionPortsPortWireOnMasterElement>,
    pub on_slave: Option<AbstractionDefinitionPortsPortWireOnSlaveElement>,
    pub content_163: Option<AbstractionDefinitionPortsPortWireContent163XsdType>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortWireElementType
{
    type Serializer<'x> =
        quick_xml_serialize::AbstractionDefinitionPortsPortWireElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortWireElementTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortWireElementTypeSerializerState::Init__,
            ),
            name: name.unwrap_or("spirit:AbstractionDefinitionPortsPortWire"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortWireElementTypeContent
{
    type Serializer<'x> =
        quick_xml_serialize::AbstractionDefinitionPortsPortWireElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortWireElementTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortWireElementTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortWireElementType
{
    type Deserializer =
        Box<quick_xml_deserialize::AbstractionDefinitionPortsPortWireElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortWireElementTypeContent
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortWireElementTypeContentDeserializer,
    >;
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortTransactionalElementType {
    pub content: AbstractionDefinitionPortsPortTransactionalElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortTransactionalElementTypeContent {
    pub qualifier: Option<AbstractionDefinitionPortsPortTransactionalQualifierElement>,
    pub on_system: Vec<AbstractionDefinitionPortsPortTransactionalOnSystemElement>,
    pub on_master: Option<AbstractionDefinitionPortsPortTransactionalOnMasterElement>,
    pub on_slave: Option<AbstractionDefinitionPortsPortTransactionalOnSlaveElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortTransactionalElementType
{
    type Serializer<'x> =
        quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalElementTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalElementTypeSerializerState::Init__,
            ),
            name: name.unwrap_or("spirit:AbstractionDefinitionPortsPortTransactional"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortTransactionalElementTypeContent
{
    type Serializer<'x> = quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalElementTypeContentSerializer<
        'x,
    >;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalElementTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalElementTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortTransactionalElementType
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortTransactionalElementTypeDeserializer,
    >;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortTransactionalElementTypeContent
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortTransactionalElementTypeContentDeserializer,
    >;
}
pub type AbstractionDefinitionPortsPortWireQualifierElement =
    AbstractionDefinitionPortsPortWireQualifierElementType;
pub type AbstractionDefinitionPortsPortWireOnSystemElement =
    AbstractionDefinitionPortsPortWireOnSystemElementType;
pub type AbstractionDefinitionPortsPortWireOnMasterElement =
    AbstractionDefinitionPortsPortWireOnMasterElementType;
pub type AbstractionDefinitionPortsPortWireOnSlaveElement =
    AbstractionDefinitionPortsPortWireOnSlaveElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortWireContent163XsdType {
    pub content: AbstractionDefinitionPortsPortWireContent163XsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub enum AbstractionDefinitionPortsPortWireContent163XsdTypeContent {
    DefaultValue(Box<super::simple_types::ScaledNonNegativeIntegerXsdType>),
    RequiresDriver(Box<super::signal_drivers::RequiresDriverElement>),
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortWireContent163XsdType
{
    type Serializer<'x> =
        quick_xml_serialize::AbstractionDefinitionPortsPortWireContent163XsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortWireContent163XsdTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortWireContent163XsdTypeSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortWireContent163XsdTypeContent
{
    type Serializer<'x> =
        quick_xml_serialize::AbstractionDefinitionPortsPortWireContent163XsdTypeContentSerializer<
            'x,
        >;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortWireContent163XsdTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortWireContent163XsdTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortWireContent163XsdType
{
    type Deserializer =
        Box<quick_xml_deserialize::AbstractionDefinitionPortsPortWireContent163XsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortWireContent163XsdTypeContent
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortWireContent163XsdTypeContentDeserializer,
    >;
}
pub type AbstractionDefinitionPortsPortTransactionalQualifierElement =
    AbstractionDefinitionPortsPortTransactionalQualifierElementType;
pub type AbstractionDefinitionPortsPortTransactionalOnSystemElement =
    AbstractionDefinitionPortsPortTransactionalOnSystemElementType;
pub type AbstractionDefinitionPortsPortTransactionalOnMasterElement =
    AbstractionDefinitionPortsPortTransactionalOnMasterElementType;
pub type AbstractionDefinitionPortsPortTransactionalOnSlaveElement =
    AbstractionDefinitionPortsPortTransactionalOnSlaveElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortWireQualifierElementType {
    pub content: AbstractionDefinitionPortsPortWireQualifierElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub enum AbstractionDefinitionPortsPortWireQualifierElementTypeContent {
    Content157(Box<AbstractionDefinitionPortsPortWireQualifierContent157XsdType>),
    IsClock(Option<Box<super::BooleanXsdType>>),
    IsReset(Option<Box<super::BooleanXsdType>>),
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortWireQualifierElementType
{
    type Serializer<'x> =
        quick_xml_serialize::AbstractionDefinitionPortsPortWireQualifierElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortWireQualifierElementTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortWireQualifierElementTypeSerializerState::Init__,
            ),
            name: name.unwrap_or("spirit:AbstractionDefinitionPortsPortWireQualifier"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortWireQualifierElementTypeContent
{
    type Serializer<'x> = quick_xml_serialize::AbstractionDefinitionPortsPortWireQualifierElementTypeContentSerializer<
        'x,
    >;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortWireQualifierElementTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortWireQualifierElementTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortWireQualifierElementType
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortWireQualifierElementTypeDeserializer,
    >;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortWireQualifierElementTypeContent
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortWireQualifierElementTypeContentDeserializer,
    >;
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortWireOnSystemElementType {
    pub content: AbstractionDefinitionPortsPortWireOnSystemElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortWireOnSystemElementTypeContent {
    pub group: super::NameXsdType,
    pub wire_port: AbstractionDefinitionPortsPortWireOnSystemWirePortXsdType,
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortWireOnSystemElementType
{
    type Serializer<'x> =
        quick_xml_serialize::AbstractionDefinitionPortsPortWireOnSystemElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortWireOnSystemElementTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortWireOnSystemElementTypeSerializerState::Init__,
            ),
            name: name.unwrap_or("spirit:AbstractionDefinitionPortsPortWireOnSystem"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortWireOnSystemElementTypeContent
{
    type Serializer<'x> =
        quick_xml_serialize::AbstractionDefinitionPortsPortWireOnSystemElementTypeContentSerializer<
            'x,
        >;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortWireOnSystemElementTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortWireOnSystemElementTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortWireOnSystemElementType
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortWireOnSystemElementTypeDeserializer,
    >;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortWireOnSystemElementTypeContent
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortWireOnSystemElementTypeContentDeserializer,
    >;
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortWireOnMasterElementType {
    pub content: AbstractionDefinitionPortsPortWireOnMasterElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortWireOnMasterElementTypeContent {
    pub presence: Option<PresenceElement>,
    pub width: Option<super::PositiveIntegerXsdType>,
    pub direction: Option<DirectionElement>,
    pub content_160: Option<AbstractionDefinitionPortsPortWireOnMasterContent160XsdType>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortWireOnMasterElementType
{
    type Serializer<'x> =
        quick_xml_serialize::AbstractionDefinitionPortsPortWireOnMasterElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortWireOnMasterElementTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortWireOnMasterElementTypeSerializerState::Init__,
            ),
            name: name.unwrap_or("spirit:AbstractionDefinitionPortsPortWireOnMaster"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortWireOnMasterElementTypeContent
{
    type Serializer<'x> =
        quick_xml_serialize::AbstractionDefinitionPortsPortWireOnMasterElementTypeContentSerializer<
            'x,
        >;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortWireOnMasterElementTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortWireOnMasterElementTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortWireOnMasterElementType
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortWireOnMasterElementTypeDeserializer,
    >;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortWireOnMasterElementTypeContent
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortWireOnMasterElementTypeContentDeserializer,
    >;
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortWireOnSlaveElementType {
    pub content: AbstractionDefinitionPortsPortWireOnSlaveElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortWireOnSlaveElementTypeContent {
    pub presence: Option<PresenceElement>,
    pub width: Option<super::PositiveIntegerXsdType>,
    pub direction: Option<DirectionElement>,
    pub content_161: Option<AbstractionDefinitionPortsPortWireOnSlaveContent161XsdType>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortWireOnSlaveElementType
{
    type Serializer<'x> =
        quick_xml_serialize::AbstractionDefinitionPortsPortWireOnSlaveElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortWireOnSlaveElementTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortWireOnSlaveElementTypeSerializerState::Init__,
            ),
            name: name.unwrap_or("spirit:AbstractionDefinitionPortsPortWireOnSlave"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortWireOnSlaveElementTypeContent
{
    type Serializer<'x> =
        quick_xml_serialize::AbstractionDefinitionPortsPortWireOnSlaveElementTypeContentSerializer<
            'x,
        >;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortWireOnSlaveElementTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortWireOnSlaveElementTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortWireOnSlaveElementType
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortWireOnSlaveElementTypeDeserializer,
    >;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortWireOnSlaveElementTypeContent
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortWireOnSlaveElementTypeContentDeserializer,
    >;
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortTransactionalQualifierElementType {
    pub content: AbstractionDefinitionPortsPortTransactionalQualifierElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortTransactionalQualifierElementTypeContent {
    pub is_address: Option<super::BooleanXsdType>,
    pub is_data: Option<super::BooleanXsdType>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortTransactionalQualifierElementType
{
    type Serializer<'x> = quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalQualifierElementTypeSerializer<
        'x,
    >;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalQualifierElementTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalQualifierElementTypeSerializerState::Init__,
            ),
            name: name
                .unwrap_or(
                    "spirit:AbstractionDefinitionPortsPortTransactionalQualifier",
                ),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortTransactionalQualifierElementTypeContent
{
    type Serializer<'x> = quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalQualifierElementTypeContentSerializer<
        'x,
    >;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalQualifierElementTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalQualifierElementTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortTransactionalQualifierElementType
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortTransactionalQualifierElementTypeDeserializer,
    >;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortTransactionalQualifierElementTypeContent
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortTransactionalQualifierElementTypeContentDeserializer,
    >;
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortTransactionalOnSystemElementType {
    pub content: AbstractionDefinitionPortsPortTransactionalOnSystemElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortTransactionalOnSystemElementTypeContent {
    pub group: super::NameXsdType,
    pub transactional_port:
        AbstractionDefinitionPortsPortTransactionalOnSystemTransactionalPortXsdType,
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortTransactionalOnSystemElementType
{
    type Serializer<'x> = quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnSystemElementTypeSerializer<
        'x,
    >;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnSystemElementTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnSystemElementTypeSerializerState::Init__,
            ),
            name: name
                .unwrap_or("spirit:AbstractionDefinitionPortsPortTransactionalOnSystem"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortTransactionalOnSystemElementTypeContent
{
    type Serializer<'x> = quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnSystemElementTypeContentSerializer<
        'x,
    >;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnSystemElementTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnSystemElementTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortTransactionalOnSystemElementType
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortTransactionalOnSystemElementTypeDeserializer,
    >;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortTransactionalOnSystemElementTypeContent
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortTransactionalOnSystemElementTypeContentDeserializer,
    >;
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortTransactionalOnMasterElementType {
    pub content: AbstractionDefinitionPortsPortTransactionalOnMasterElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortTransactionalOnMasterElementTypeContent {
    pub presence: Option<PresenceElement>,
    pub service: ServiceTypeXsdType,
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortTransactionalOnMasterElementType
{
    type Serializer<'x> = quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnMasterElementTypeSerializer<
        'x,
    >;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnMasterElementTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnMasterElementTypeSerializerState::Init__,
            ),
            name: name
                .unwrap_or("spirit:AbstractionDefinitionPortsPortTransactionalOnMaster"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortTransactionalOnMasterElementTypeContent
{
    type Serializer<'x> = quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnMasterElementTypeContentSerializer<
        'x,
    >;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnMasterElementTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnMasterElementTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortTransactionalOnMasterElementType
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortTransactionalOnMasterElementTypeDeserializer,
    >;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortTransactionalOnMasterElementTypeContent
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortTransactionalOnMasterElementTypeContentDeserializer,
    >;
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortTransactionalOnSlaveElementType {
    pub content: AbstractionDefinitionPortsPortTransactionalOnSlaveElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortTransactionalOnSlaveElementTypeContent {
    pub presence: Option<PresenceElement>,
    pub service: ServiceTypeXsdType,
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortTransactionalOnSlaveElementType
{
    type Serializer<'x> = quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnSlaveElementTypeSerializer<
        'x,
    >;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnSlaveElementTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnSlaveElementTypeSerializerState::Init__,
            ),
            name: name
                .unwrap_or("spirit:AbstractionDefinitionPortsPortTransactionalOnSlave"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortTransactionalOnSlaveElementTypeContent
{
    type Serializer<'x> = quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnSlaveElementTypeContentSerializer<
        'x,
    >;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnSlaveElementTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnSlaveElementTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortTransactionalOnSlaveElementType
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortTransactionalOnSlaveElementTypeDeserializer,
    >;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortTransactionalOnSlaveElementTypeContent
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortTransactionalOnSlaveElementTypeContentDeserializer,
    >;
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortWireQualifierContent157XsdType {
    pub content: AbstractionDefinitionPortsPortWireQualifierContent157XsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortWireQualifierContent157XsdTypeContent {
    pub is_address: Option<super::BooleanXsdType>,
    pub is_data: Option<super::BooleanXsdType>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortWireQualifierContent157XsdType
{
    type Serializer<'x> =
        quick_xml_serialize::AbstractionDefinitionPortsPortWireQualifierContent157XsdTypeSerializer<
            'x,
        >;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortWireQualifierContent157XsdTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortWireQualifierContent157XsdTypeSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortWireQualifierContent157XsdTypeContent
{
    type Serializer<'x> = quick_xml_serialize::AbstractionDefinitionPortsPortWireQualifierContent157XsdTypeContentSerializer<
        'x,
    >;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortWireQualifierContent157XsdTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortWireQualifierContent157XsdTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortWireQualifierContent157XsdType
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortWireQualifierContent157XsdTypeDeserializer,
    >;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortWireQualifierContent157XsdTypeContent
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortWireQualifierContent157XsdTypeContentDeserializer,
    >;
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortWireOnSystemWirePortXsdType {
    pub content: AbstractionDefinitionPortsPortWireOnSystemWirePortXsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortWireOnSystemWirePortXsdTypeContent {
    pub presence: Option<PresenceElement>,
    pub width: Option<super::PositiveIntegerXsdType>,
    pub direction: Option<DirectionElement>,
    pub content_159: Option<AbstractionDefinitionPortsPortWireOnSystemContent159XsdType>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortWireOnSystemWirePortXsdType
{
    type Serializer<'x> =
        quick_xml_serialize::AbstractionDefinitionPortsPortWireOnSystemWirePortXsdTypeSerializer<
            'x,
        >;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortWireOnSystemWirePortXsdTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortWireOnSystemWirePortXsdTypeSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortWireOnSystemWirePortXsdTypeContent
{
    type Serializer<'x> = quick_xml_serialize::AbstractionDefinitionPortsPortWireOnSystemWirePortXsdTypeContentSerializer<
        'x,
    >;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortWireOnSystemWirePortXsdTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortWireOnSystemWirePortXsdTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortWireOnSystemWirePortXsdType
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortWireOnSystemWirePortXsdTypeDeserializer,
    >;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortWireOnSystemWirePortXsdTypeContent
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortWireOnSystemWirePortXsdTypeContentDeserializer,
    >;
}
pub type DirectionElement = DirectionElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortWireOnMasterContent160XsdType {
    pub content: AbstractionDefinitionPortsPortWireOnMasterContent160XsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortWireOnMasterContent160XsdTypeContent {
    pub mode_constraints: super::constraints::AbstractionDefPortConstraintsTypeXsdType,
    pub mirrored_mode_constraints:
        Option<super::constraints::AbstractionDefPortConstraintsTypeXsdType>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortWireOnMasterContent160XsdType
{
    type Serializer<'x> =
        quick_xml_serialize::AbstractionDefinitionPortsPortWireOnMasterContent160XsdTypeSerializer<
            'x,
        >;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortWireOnMasterContent160XsdTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortWireOnMasterContent160XsdTypeSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortWireOnMasterContent160XsdTypeContent
{
    type Serializer<'x> = quick_xml_serialize::AbstractionDefinitionPortsPortWireOnMasterContent160XsdTypeContentSerializer<
        'x,
    >;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortWireOnMasterContent160XsdTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortWireOnMasterContent160XsdTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortWireOnMasterContent160XsdType
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortWireOnMasterContent160XsdTypeDeserializer,
    >;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortWireOnMasterContent160XsdTypeContent
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortWireOnMasterContent160XsdTypeContentDeserializer,
    >;
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortWireOnSlaveContent161XsdType {
    pub content: AbstractionDefinitionPortsPortWireOnSlaveContent161XsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortWireOnSlaveContent161XsdTypeContent {
    pub mode_constraints: super::constraints::AbstractionDefPortConstraintsTypeXsdType,
    pub mirrored_mode_constraints:
        Option<super::constraints::AbstractionDefPortConstraintsTypeXsdType>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortWireOnSlaveContent161XsdType
{
    type Serializer<'x> =
        quick_xml_serialize::AbstractionDefinitionPortsPortWireOnSlaveContent161XsdTypeSerializer<
            'x,
        >;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortWireOnSlaveContent161XsdTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortWireOnSlaveContent161XsdTypeSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortWireOnSlaveContent161XsdTypeContent
{
    type Serializer<'x> = quick_xml_serialize::AbstractionDefinitionPortsPortWireOnSlaveContent161XsdTypeContentSerializer<
        'x,
    >;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortWireOnSlaveContent161XsdTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortWireOnSlaveContent161XsdTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortWireOnSlaveContent161XsdType
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortWireOnSlaveContent161XsdTypeDeserializer,
    >;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortWireOnSlaveContent161XsdTypeContent
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortWireOnSlaveContent161XsdTypeContentDeserializer,
    >;
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortTransactionalOnSystemTransactionalPortXsdType {
    pub content: AbstractionDefinitionPortsPortTransactionalOnSystemTransactionalPortXsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortTransactionalOnSystemTransactionalPortXsdTypeContent {
    pub presence: Option<PresenceElement>,
    pub service: ServiceTypeXsdType,
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortTransactionalOnSystemTransactionalPortXsdType
{
    type Serializer<'x> = quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnSystemTransactionalPortXsdTypeSerializer<
        'x,
    >;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnSystemTransactionalPortXsdTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnSystemTransactionalPortXsdTypeSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortTransactionalOnSystemTransactionalPortXsdTypeContent
{
    type Serializer<'x> = quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnSystemTransactionalPortXsdTypeContentSerializer<
        'x,
    >;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnSystemTransactionalPortXsdTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortTransactionalOnSystemTransactionalPortXsdTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortTransactionalOnSystemTransactionalPortXsdType
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortTransactionalOnSystemTransactionalPortXsdTypeDeserializer,
    >;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortTransactionalOnSystemTransactionalPortXsdTypeContent
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortTransactionalOnSystemTransactionalPortXsdTypeContentDeserializer,
    >;
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortWireOnSystemContent159XsdType {
    pub content: AbstractionDefinitionPortsPortWireOnSystemContent159XsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct AbstractionDefinitionPortsPortWireOnSystemContent159XsdTypeContent {
    pub mode_constraints: super::constraints::AbstractionDefPortConstraintsTypeXsdType,
    pub mirrored_mode_constraints:
        Option<super::constraints::AbstractionDefPortConstraintsTypeXsdType>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortWireOnSystemContent159XsdType
{
    type Serializer<'x> =
        quick_xml_serialize::AbstractionDefinitionPortsPortWireOnSystemContent159XsdTypeSerializer<
            'x,
        >;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortWireOnSystemContent159XsdTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortWireOnSystemContent159XsdTypeSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for AbstractionDefinitionPortsPortWireOnSystemContent159XsdTypeContent
{
    type Serializer<'x> = quick_xml_serialize::AbstractionDefinitionPortsPortWireOnSystemContent159XsdTypeContentSerializer<
        'x,
    >;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::AbstractionDefinitionPortsPortWireOnSystemContent159XsdTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::AbstractionDefinitionPortsPortWireOnSystemContent159XsdTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortWireOnSystemContent159XsdType
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortWireOnSystemContent159XsdTypeDeserializer,
    >;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for AbstractionDefinitionPortsPortWireOnSystemContent159XsdTypeContent
{
    type Deserializer = Box<
        quick_xml_deserialize::AbstractionDefinitionPortsPortWireOnSystemContent159XsdTypeContentDeserializer,
    >;
}
#[derive(Clone, Debug, PartialEq)]
pub enum DirectionElementType {
    In,
    Out,
    Inout,
}
impl ::xsd_parser_types::quick_xml::SerializeBytes for DirectionElementType {
    fn serialize_bytes(
        &self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Result<Option<::std::borrow::Cow<'_, str>>, ::xsd_parser_types::quick_xml::Error> {
        match self {
            Self::In => Ok(Some(::std::borrow::Cow::Borrowed("in"))),
            Self::Out => Ok(Some(::std::borrow::Cow::Borrowed("out"))),
            Self::Inout => Ok(Some(::std::borrow::Cow::Borrowed("inout"))),
        }
    }
}
impl xsd_parser_types::quick_xml::WithSerializeToBytes for DirectionElementType {}
impl ::xsd_parser_types::quick_xml::DeserializeBytes for DirectionElementType {
    fn deserialize_bytes(
        helper: &mut ::xsd_parser_types::quick_xml::DeserializeHelper,
        bytes: &[u8],
    ) -> Result<Self, ::xsd_parser_types::quick_xml::Error> {
        match bytes {
            b"in" => Ok(Self::In),
            b"out" => Ok(Self::Out),
            b"inout" => Ok(Self::Inout),
            x => Err(::xsd_parser_types::quick_xml::Error::from(
                ::xsd_parser_types::quick_xml::ErrorKind::UnknownOrInvalidValue(
                    ::xsd_parser_types::quick_xml::RawByteStr::from_slice(x),
                ),
            )),
        }
    }
}
impl xsd_parser_types::quick_xml::WithDeserializerFromBytes for DirectionElementType {}
