// @generated by ipxact-codegen; do not edit by hand.
// Source schema: crates/ipxact/schema/1685-2014/index.xsd

#![allow(dead_code, unused_mut, unused_variables, clippy::all)]

pub mod quick_xml_deserialize;
pub mod quick_xml_serialize;
use xsd_parser_types::xml::AnyAttributes;
#[derive(Clone, Debug, PartialEq)]
pub enum DataTypeTypeXsdType {
    Int,
    UnsignedInt,
    Long,
    UnsignedLong,
    Float,
    Double,
    Char,
    Void,
}
impl ::xsd_parser_types::quick_xml::SerializeBytes for DataTypeTypeXsdType {
    fn serialize_bytes(
        &self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Result<Option<::std::borrow::Cow<'_, str>>, ::xsd_parser_types::quick_xml::Error> {
        match self {
            Self::Int => Ok(Some(::std::borrow::Cow::Borrowed("int"))),
            Self::UnsignedInt => Ok(Some(::std::borrow::Cow::Borrowed("unsigned int"))),
            Self::Long => Ok(Some(::std::borrow::Cow::Borrowed("long"))),
            Self::UnsignedLong => Ok(Some(::std::borrow::Cow::Borrowed("unsigned long"))),
            Self::Float => Ok(Some(::std::borrow::Cow::Borrowed("float"))),
            Self::Double => Ok(Some(::std::borrow::Cow::Borrowed("double"))),
            Self::Char => Ok(Some(::std::borrow::Cow::Borrowed("char *"))),
            Self::Void => Ok(Some(::std::borrow::Cow::Borrowed("void *"))),
        }
    }
}
impl xsd_parser_types::quick_xml::WithSerializeToBytes for DataTypeTypeXsdType {}
impl ::xsd_parser_types::quick_xml::DeserializeBytes for DataTypeTypeXsdType {
    fn deserialize_bytes(
        helper: &mut ::xsd_parser_types::quick_xml::DeserializeHelper,
        bytes: &[u8],
    ) -> Result<Self, ::xsd_parser_types::quick_xml::Error> {
        match bytes {
            b"int" => Ok(Self::Int),
            b"unsigned int" => Ok(Self::UnsignedInt),
            b"long" => Ok(Self::Long),
            b"unsigned long" => Ok(Self::UnsignedLong),
            b"float" => Ok(Self::Float),
            b"double" => Ok(Self::Double),
            b"char *" => Ok(Self::Char),
            b"void *" => Ok(Self::Void),
            x => Err(::xsd_parser_types::quick_xml::Error::from(
                ::xsd_parser_types::quick_xml::ErrorKind::UnknownOrInvalidValue(
                    ::xsd_parser_types::quick_xml::RawByteStr::from_slice(x),
                ),
            )),
        }
    }
}
impl xsd_parser_types::quick_xml::WithDeserializerFromBytes for DataTypeTypeXsdType {}
pub type DependencyElement = DependencyElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct DependencyElementType {
    pub id: Option<super::Id>,
    pub content: super::StringXsdType,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for DependencyElementType {
    type Serializer<'x> = quick_xml_serialize::DependencyElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::DependencyElementTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::DependencyElementTypeSerializerState::Init__),
            name: name.unwrap_or("ipxact:dependency"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for DependencyElementType {
    type Deserializer = Box<quick_xml_deserialize::DependencyElementTypeDeserializer>;
}
pub type ExecutableImageElement = ExecutableImageElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct ExecutableImageElementType {
    pub image_id: super::TokenXsdType,
    pub image_type: Option<super::NameXsdType>,
    pub id: Option<super::Id>,
    pub content: ExecutableImageElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct ExecutableImageElementTypeContent {
    pub name_group: ExecutableImageNameGroupXsdType,
    pub parameters: Option<super::common_structures::ParametersElement>,
    pub language_tools: Option<ExecutableImageLanguageToolsElement>,
    pub file_set_ref_group: Option<ExecutableImageFileSetRefGroupElement>,
    pub vendor_extensions: Option<super::common_structures::VendorExtensionsElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for ExecutableImageElementType {
    type Serializer<'x> = quick_xml_serialize::ExecutableImageElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::ExecutableImageElementTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::ExecutableImageElementTypeSerializerState::Init__),
            name: name.unwrap_or("ipxact:executableImage"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for ExecutableImageElementTypeContent {
    type Serializer<'x> = quick_xml_serialize::ExecutableImageElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::ExecutableImageElementTypeContentSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::ExecutableImageElementTypeContentSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for ExecutableImageElementType {
    type Deserializer = Box<quick_xml_deserialize::ExecutableImageElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for ExecutableImageElementTypeContent {
    type Deserializer = Box<quick_xml_deserialize::ExecutableImageElementTypeContentDeserializer>;
}
pub type FileElement = FileElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct FileElementType {
    pub file_id: Option<super::TokenXsdType>,
    pub any_attribute: AnyAttributes,
    pub id: Option<super::Id>,
    pub content: FileElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct FileElementTypeContent {
    pub name: super::simple_types::StringUriExpressionXsdType,
    pub is_present: Option<super::common_structures::IsPresentElement>,
    pub file_type: Vec<super::file_type::FileTypeElement>,
    pub is_structural: Option<super::BooleanXsdType>,
    pub is_include_file: Option<FileIsIncludeFileElement>,
    pub logical_name: Option<FileLogicalNameElement>,
    pub exported_name: Vec<FileExportedNameElement>,
    pub build_command: Option<FileBuildCommandElement>,
    pub dependency: Vec<DependencyElement>,
    pub define: Vec<super::common_structures::NameValuePairTypeXsdType>,
    pub image_type: Vec<FileImageTypeElement>,
    pub description: Option<super::StringXsdType>,
    pub vendor_extensions: Option<super::common_structures::VendorExtensionsElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for FileElementType {
    type Serializer<'x> = quick_xml_serialize::FileElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::FileElementTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::FileElementTypeSerializerState::Init__),
            name: name.unwrap_or("ipxact:file"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for FileElementTypeContent {
    type Serializer<'x> = quick_xml_serialize::FileElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::FileElementTypeContentSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::FileElementTypeContentSerializerState::Init__),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for FileElementType {
    type Deserializer = Box<quick_xml_deserialize::FileElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for FileElementTypeContent {
    type Deserializer = Box<quick_xml_deserialize::FileElementTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct FileBuilderTypeXsdType {
    pub id: Option<super::Id>,
    pub content: FileBuilderTypeXsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct FileBuilderTypeXsdTypeContent {
    pub file_type: super::file_type::FileTypeElement,
    pub command: Option<super::simple_types::StringExpressionXsdType>,
    pub flags: Option<super::simple_types::StringExpressionXsdType>,
    pub replace_default_flags: Option<super::simple_types::UnsignedBitExpressionXsdType>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for FileBuilderTypeXsdType {
    type Serializer<'x> = quick_xml_serialize::FileBuilderTypeXsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::FileBuilderTypeXsdTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::FileBuilderTypeXsdTypeSerializerState::Init__),
            name: name.unwrap_or("ipxact:fileBuilderType"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for FileBuilderTypeXsdTypeContent {
    type Serializer<'x> = quick_xml_serialize::FileBuilderTypeXsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::FileBuilderTypeXsdTypeContentSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::FileBuilderTypeXsdTypeContentSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for FileBuilderTypeXsdType {
    type Deserializer = Box<quick_xml_deserialize::FileBuilderTypeXsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for FileBuilderTypeXsdTypeContent {
    type Deserializer = Box<quick_xml_deserialize::FileBuilderTypeXsdTypeContentDeserializer>;
}
pub type FileSetElement = FileSetTypeXsdType;
pub type FileSetRefElement = FileSetRefElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct FileSetRefElementType {
    pub id: Option<super::Id>,
    pub content: FileSetRefElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct FileSetRefElementTypeContent {
    pub local_name: super::NameXsdType,
    pub is_present: Option<super::common_structures::IsPresentElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for FileSetRefElementType {
    type Serializer<'x> = quick_xml_serialize::FileSetRefElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::FileSetRefElementTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::FileSetRefElementTypeSerializerState::Init__),
            name: name.unwrap_or("ipxact:fileSetRef"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for FileSetRefElementTypeContent {
    type Serializer<'x> = quick_xml_serialize::FileSetRefElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::FileSetRefElementTypeContentSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::FileSetRefElementTypeContentSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for FileSetRefElementType {
    type Deserializer = Box<quick_xml_deserialize::FileSetRefElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for FileSetRefElementTypeContent {
    type Deserializer = Box<quick_xml_deserialize::FileSetRefElementTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct FileSetTypeXsdType {
    pub id: Option<super::Id>,
    pub content: FileSetTypeXsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct FileSetTypeXsdTypeContent {
    pub name_group: FileSetNameGroupXsdType,
    pub group: Vec<FileSetTypeGroupElement>,
    pub file: Vec<FileElement>,
    pub default_file_builder: Vec<FileBuilderTypeXsdType>,
    pub dependency: Vec<DependencyElement>,
    pub function: Vec<FileSetTypeFunctionElement>,
    pub vendor_extensions: Option<super::common_structures::VendorExtensionsElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for FileSetTypeXsdType {
    type Serializer<'x> = quick_xml_serialize::FileSetTypeXsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::FileSetTypeXsdTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::FileSetTypeXsdTypeSerializerState::Init__),
            name: name.unwrap_or("ipxact:fileSetType"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for FileSetTypeXsdTypeContent {
    type Serializer<'x> = quick_xml_serialize::FileSetTypeXsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::FileSetTypeXsdTypeContentSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::FileSetTypeXsdTypeContentSerializerState::Init__),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for FileSetTypeXsdType {
    type Deserializer = Box<quick_xml_deserialize::FileSetTypeXsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for FileSetTypeXsdTypeContent {
    type Deserializer = Box<quick_xml_deserialize::FileSetTypeXsdTypeContentDeserializer>;
}
pub type FileSetsElement = FileSetsElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct FileSetsElementType {
    pub content: FileSetsElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct FileSetsElementTypeContent {
    pub file_set: Vec<FileSetElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for FileSetsElementType {
    type Serializer<'x> = quick_xml_serialize::FileSetsElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::FileSetsElementTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::FileSetsElementTypeSerializerState::Init__),
            name: name.unwrap_or("ipxact:fileSets"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for FileSetsElementTypeContent {
    type Serializer<'x> = quick_xml_serialize::FileSetsElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::FileSetsElementTypeContentSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::FileSetsElementTypeContentSerializerState::Init__),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for FileSetsElementType {
    type Deserializer = Box<quick_xml_deserialize::FileSetsElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for FileSetsElementTypeContent {
    type Deserializer = Box<quick_xml_deserialize::FileSetsElementTypeContentDeserializer>;
}
pub type GeneratorRefElement = GeneratorRefElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct GeneratorRefElementType {
    pub id: Option<super::Id>,
    pub content: super::StringXsdType,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for GeneratorRefElementType {
    type Serializer<'x> = quick_xml_serialize::GeneratorRefElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::GeneratorRefElementTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::GeneratorRefElementTypeSerializerState::Init__),
            name: name.unwrap_or("ipxact:generatorRef"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for GeneratorRefElementType {
    type Deserializer = Box<quick_xml_deserialize::GeneratorRefElementTypeDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct IpxactUriXsdType {
    pub content: super::StringXsdType,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for IpxactUriXsdType {
    type Serializer<'x> = quick_xml_serialize::IpxactUriXsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::IpxactUriXsdTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::IpxactUriXsdTypeSerializerState::Init__),
            name: name.unwrap_or("ipxact:ipxactURI"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for IpxactUriXsdType {
    type Deserializer = Box<quick_xml_deserialize::IpxactUriXsdTypeDeserializer>;
}
pub type LinkerCommandFileElement = LinkerCommandFileElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct LinkerCommandFileElementType {
    pub content: LinkerCommandFileElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct LinkerCommandFileElementTypeContent {
    pub name: super::simple_types::StringUriExpressionXsdType,
    pub command_line_switch: super::simple_types::StringExpressionXsdType,
    pub enable: super::simple_types::UnsignedBitExpressionXsdType,
    pub generator_ref: Vec<GeneratorRefElement>,
    pub vendor_extensions: Option<super::common_structures::VendorExtensionsElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for LinkerCommandFileElementType {
    type Serializer<'x> = quick_xml_serialize::LinkerCommandFileElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(
            quick_xml_serialize::LinkerCommandFileElementTypeSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::LinkerCommandFileElementTypeSerializerState::Init__,
                ),
                name: name.unwrap_or("ipxact:linkerCommandFile"),
                is_root,
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for LinkerCommandFileElementTypeContent {
    type Serializer<'x> = quick_xml_serialize::LinkerCommandFileElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::LinkerCommandFileElementTypeContentSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::LinkerCommandFileElementTypeContentSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for LinkerCommandFileElementType {
    type Deserializer = Box<quick_xml_deserialize::LinkerCommandFileElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for LinkerCommandFileElementTypeContent {
    type Deserializer = Box<quick_xml_deserialize::LinkerCommandFileElementTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub enum ReturnTypeTypeXsdType {
    Void,
    Int,
}
impl ::xsd_parser_types::quick_xml::SerializeBytes for ReturnTypeTypeXsdType {
    fn serialize_bytes(
        &self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Result<Option<::std::borrow::Cow<'_, str>>, ::xsd_parser_types::quick_xml::Error> {
        match self {
            Self::Void => Ok(Some(::std::borrow::Cow::Borrowed("void"))),
            Self::Int => Ok(Some(::std::borrow::Cow::Borrowed("int"))),
        }
    }
}
impl xsd_parser_types::quick_xml::WithSerializeToBytes for ReturnTypeTypeXsdType {}
impl ::xsd_parser_types::quick_xml::DeserializeBytes for ReturnTypeTypeXsdType {
    fn deserialize_bytes(
        helper: &mut ::xsd_parser_types::quick_xml::DeserializeHelper,
        bytes: &[u8],
    ) -> Result<Self, ::xsd_parser_types::quick_xml::Error> {
        match bytes {
            b"void" => Ok(Self::Void),
            b"int" => Ok(Self::Int),
            x => Err(::xsd_parser_types::quick_xml::Error::from(
                ::xsd_parser_types::quick_xml::ErrorKind::UnknownOrInvalidValue(
                    ::xsd_parser_types::quick_xml::RawByteStr::from_slice(x),
                ),
            )),
        }
    }
}
impl xsd_parser_types::quick_xml::WithDeserializerFromBytes for ReturnTypeTypeXsdType {}
#[derive(Clone, Debug, PartialEq)]
pub struct ExecutableImageNameGroupXsdType {
    pub content: ExecutableImageNameGroupXsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct ExecutableImageNameGroupXsdTypeContent {
    pub name: super::NameXsdType,
    pub display_name: Option<super::common_structures::DisplayNameElement>,
    pub description: Option<super::common_structures::DescriptionElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for ExecutableImageNameGroupXsdType {
    type Serializer<'x> = quick_xml_serialize::ExecutableImageNameGroupXsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::ExecutableImageNameGroupXsdTypeSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::ExecutableImageNameGroupXsdTypeSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for ExecutableImageNameGroupXsdTypeContent {
    type Serializer<'x> = quick_xml_serialize::ExecutableImageNameGroupXsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::ExecutableImageNameGroupXsdTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::ExecutableImageNameGroupXsdTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for ExecutableImageNameGroupXsdType {
    type Deserializer = Box<quick_xml_deserialize::ExecutableImageNameGroupXsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for ExecutableImageNameGroupXsdTypeContent {
    type Deserializer =
        Box<quick_xml_deserialize::ExecutableImageNameGroupXsdTypeContentDeserializer>;
}
pub type ExecutableImageLanguageToolsElement = ExecutableImageLanguageToolsElementType;
pub type ExecutableImageFileSetRefGroupElement = ExecutableImageFileSetRefGroupElementType;
pub type FileIsIncludeFileElement = FileIsIncludeFileElementType;
pub type FileLogicalNameElement = FileLogicalNameElementType;
pub type FileExportedNameElement = FileExportedNameElementType;
pub type FileBuildCommandElement = FileBuildCommandElementType;
pub type FileImageTypeElement = FileImageTypeElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct FileSetNameGroupXsdType {
    pub content: FileSetNameGroupXsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct FileSetNameGroupXsdTypeContent {
    pub name: super::NameXsdType,
    pub display_name: Option<super::common_structures::DisplayNameElement>,
    pub description: Option<super::common_structures::DescriptionElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for FileSetNameGroupXsdType {
    type Serializer<'x> = quick_xml_serialize::FileSetNameGroupXsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::FileSetNameGroupXsdTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::FileSetNameGroupXsdTypeSerializerState::Init__),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for FileSetNameGroupXsdTypeContent {
    type Serializer<'x> = quick_xml_serialize::FileSetNameGroupXsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::FileSetNameGroupXsdTypeContentSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::FileSetNameGroupXsdTypeContentSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for FileSetNameGroupXsdType {
    type Deserializer = Box<quick_xml_deserialize::FileSetNameGroupXsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for FileSetNameGroupXsdTypeContent {
    type Deserializer = Box<quick_xml_deserialize::FileSetNameGroupXsdTypeContentDeserializer>;
}
pub type FileSetTypeGroupElement = FileSetTypeGroupElementType;
pub type FileSetTypeFunctionElement = FileSetTypeFunctionElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct ExecutableImageLanguageToolsElementType {
    pub content: ExecutableImageLanguageToolsElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct ExecutableImageLanguageToolsElementTypeContent {
    pub file_builder: Vec<ExecutableImageLanguageToolsFileBuilderElement>,
    pub content_80: Option<ExecutableImageLanguageToolsContent80XsdType>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for ExecutableImageLanguageToolsElementType {
    type Serializer<'x> =
        quick_xml_serialize::ExecutableImageLanguageToolsElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::ExecutableImageLanguageToolsElementTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::ExecutableImageLanguageToolsElementTypeSerializerState::Init__,
            ),
            name: name.unwrap_or("ipxact:ExecutableImageLanguageTools"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for ExecutableImageLanguageToolsElementTypeContent
{
    type Serializer<'x> =
        quick_xml_serialize::ExecutableImageLanguageToolsElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::ExecutableImageLanguageToolsElementTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::ExecutableImageLanguageToolsElementTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for ExecutableImageLanguageToolsElementType {
    type Deserializer =
        Box<quick_xml_deserialize::ExecutableImageLanguageToolsElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for ExecutableImageLanguageToolsElementTypeContent
{
    type Deserializer =
        Box<quick_xml_deserialize::ExecutableImageLanguageToolsElementTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct ExecutableImageFileSetRefGroupElementType {
    pub content: ExecutableImageFileSetRefGroupElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct ExecutableImageFileSetRefGroupElementTypeContent {
    pub file_set_ref: Vec<FileSetRefElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for ExecutableImageFileSetRefGroupElementType {
    type Serializer<'x> =
        quick_xml_serialize::ExecutableImageFileSetRefGroupElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::ExecutableImageFileSetRefGroupElementTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::ExecutableImageFileSetRefGroupElementTypeSerializerState::Init__,
            ),
            name: name.unwrap_or("ipxact:ExecutableImageFileSetRefGroup"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for ExecutableImageFileSetRefGroupElementTypeContent
{
    type Serializer<'x> =
        quick_xml_serialize::ExecutableImageFileSetRefGroupElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::ExecutableImageFileSetRefGroupElementTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::ExecutableImageFileSetRefGroupElementTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for ExecutableImageFileSetRefGroupElementType {
    type Deserializer =
        Box<quick_xml_deserialize::ExecutableImageFileSetRefGroupElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for ExecutableImageFileSetRefGroupElementTypeContent
{
    type Deserializer =
        Box<quick_xml_deserialize::ExecutableImageFileSetRefGroupElementTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct FileIsIncludeFileElementType {
    pub external_declarations: super::BooleanXsdType,
    pub content: super::BooleanXsdType,
}
impl FileIsIncludeFileElementType {
    #[must_use]
    pub fn default_external_declarations() -> super::BooleanXsdType {
        false
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for FileIsIncludeFileElementType {
    type Serializer<'x> = quick_xml_serialize::FileIsIncludeFileElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(
            quick_xml_serialize::FileIsIncludeFileElementTypeSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::FileIsIncludeFileElementTypeSerializerState::Init__,
                ),
                name: name.unwrap_or("ipxact:FileIsIncludeFile"),
                is_root,
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for FileIsIncludeFileElementType {
    type Deserializer = Box<quick_xml_deserialize::FileIsIncludeFileElementTypeDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct FileLogicalNameElementType {
    pub default: super::BooleanXsdType,
    pub content: super::NameXsdType,
}
impl FileLogicalNameElementType {
    #[must_use]
    pub fn default_default() -> super::BooleanXsdType {
        false
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for FileLogicalNameElementType {
    type Serializer<'x> = quick_xml_serialize::FileLogicalNameElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::FileLogicalNameElementTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::FileLogicalNameElementTypeSerializerState::Init__),
            name: name.unwrap_or("ipxact:FileLogicalName"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for FileLogicalNameElementType {
    type Deserializer = Box<quick_xml_deserialize::FileLogicalNameElementTypeDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct FileExportedNameElementType {
    pub id: Option<super::Id>,
    pub content: super::NameXsdType,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for FileExportedNameElementType {
    type Serializer<'x> = quick_xml_serialize::FileExportedNameElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::FileExportedNameElementTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::FileExportedNameElementTypeSerializerState::Init__,
            ),
            name: name.unwrap_or("ipxact:FileExportedName"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for FileExportedNameElementType {
    type Deserializer = Box<quick_xml_deserialize::FileExportedNameElementTypeDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct FileBuildCommandElementType {
    pub content: FileBuildCommandElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct FileBuildCommandElementTypeContent {
    pub command: Option<super::simple_types::StringExpressionXsdType>,
    pub flags: Option<FileBuildCommandFlagsElement>,
    pub replace_default_flags: Option<super::simple_types::UnsignedBitExpressionXsdType>,
    pub target_name: Option<super::simple_types::StringUriExpressionXsdType>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for FileBuildCommandElementType {
    type Serializer<'x> = quick_xml_serialize::FileBuildCommandElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::FileBuildCommandElementTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::FileBuildCommandElementTypeSerializerState::Init__,
            ),
            name: name.unwrap_or("ipxact:FileBuildCommand"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for FileBuildCommandElementTypeContent {
    type Serializer<'x> = quick_xml_serialize::FileBuildCommandElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::FileBuildCommandElementTypeContentSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::FileBuildCommandElementTypeContentSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for FileBuildCommandElementType {
    type Deserializer = Box<quick_xml_deserialize::FileBuildCommandElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for FileBuildCommandElementTypeContent {
    type Deserializer = Box<quick_xml_deserialize::FileBuildCommandElementTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct FileImageTypeElementType {
    pub id: Option<super::Id>,
    pub content: super::StringXsdType,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for FileImageTypeElementType {
    type Serializer<'x> = quick_xml_serialize::FileImageTypeElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::FileImageTypeElementTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::FileImageTypeElementTypeSerializerState::Init__),
            name: name.unwrap_or("ipxact:FileImageType"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for FileImageTypeElementType {
    type Deserializer = Box<quick_xml_deserialize::FileImageTypeElementTypeDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct FileSetTypeGroupElementType {
    pub id: Option<super::Id>,
    pub content: super::NameXsdType,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for FileSetTypeGroupElementType {
    type Serializer<'x> = quick_xml_serialize::FileSetTypeGroupElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::FileSetTypeGroupElementTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::FileSetTypeGroupElementTypeSerializerState::Init__,
            ),
            name: name.unwrap_or("ipxact:FileSetTypeGroup"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for FileSetTypeGroupElementType {
    type Deserializer = Box<quick_xml_deserialize::FileSetTypeGroupElementTypeDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct FileSetTypeFunctionElementType {
    pub replicate: super::BooleanXsdType,
    pub id: Option<super::Id>,
    pub content: FileSetTypeFunctionElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct FileSetTypeFunctionElementTypeContent {
    pub entry_point: Option<super::NameXsdType>,
    pub file_ref: super::TokenXsdType,
    pub return_type: Option<ReturnTypeTypeXsdType>,
    pub argument: Vec<FileSetTypeFunctionArgumentElement>,
    pub disabled: Option<super::simple_types::UnsignedBitExpressionXsdType>,
    pub source_file: Vec<FileSetTypeFunctionSourceFileElement>,
}
impl FileSetTypeFunctionElementType {
    #[must_use]
    pub fn default_replicate() -> super::BooleanXsdType {
        false
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for FileSetTypeFunctionElementType {
    type Serializer<'x> = quick_xml_serialize::FileSetTypeFunctionElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(
            quick_xml_serialize::FileSetTypeFunctionElementTypeSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::FileSetTypeFunctionElementTypeSerializerState::Init__,
                ),
                name: name.unwrap_or("ipxact:FileSetTypeFunction"),
                is_root,
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for FileSetTypeFunctionElementTypeContent {
    type Serializer<'x> = quick_xml_serialize::FileSetTypeFunctionElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::FileSetTypeFunctionElementTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::FileSetTypeFunctionElementTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for FileSetTypeFunctionElementType {
    type Deserializer = Box<quick_xml_deserialize::FileSetTypeFunctionElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for FileSetTypeFunctionElementTypeContent {
    type Deserializer =
        Box<quick_xml_deserialize::FileSetTypeFunctionElementTypeContentDeserializer>;
}
pub type ExecutableImageLanguageToolsFileBuilderElement =
    ExecutableImageLanguageToolsFileBuilderElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct ExecutableImageLanguageToolsContent80XsdType {
    pub content: ExecutableImageLanguageToolsContent80XsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct ExecutableImageLanguageToolsContent80XsdTypeContent {
    pub linker: super::simple_types::StringExpressionXsdType,
    pub content_81: ExecutableImageLanguageToolsContent81XsdType,
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for ExecutableImageLanguageToolsContent80XsdType
{
    type Serializer<'x> =
        quick_xml_serialize::ExecutableImageLanguageToolsContent80XsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::ExecutableImageLanguageToolsContent80XsdTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::ExecutableImageLanguageToolsContent80XsdTypeSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for ExecutableImageLanguageToolsContent80XsdTypeContent
{
    type Serializer<'x> =
        quick_xml_serialize::ExecutableImageLanguageToolsContent80XsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::ExecutableImageLanguageToolsContent80XsdTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::ExecutableImageLanguageToolsContent80XsdTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for ExecutableImageLanguageToolsContent80XsdType
{
    type Deserializer =
        Box<quick_xml_deserialize::ExecutableImageLanguageToolsContent80XsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for ExecutableImageLanguageToolsContent80XsdTypeContent
{
    type Deserializer =
        Box<quick_xml_deserialize::ExecutableImageLanguageToolsContent80XsdTypeContentDeserializer>;
}
pub type FileBuildCommandFlagsElement = FileBuildCommandFlagsElementType;
pub type FileSetTypeFunctionArgumentElement = FileSetTypeFunctionArgumentElementType;
pub type FileSetTypeFunctionSourceFileElement = FileSetTypeFunctionSourceFileElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct ExecutableImageLanguageToolsFileBuilderElementType {
    pub id: Option<super::Id>,
    pub content: ExecutableImageLanguageToolsFileBuilderElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct ExecutableImageLanguageToolsFileBuilderElementTypeContent {
    pub file_type: super::file_type::FileTypeElement,
    pub command: super::simple_types::StringExpressionXsdType,
    pub flags: Option<super::simple_types::StringExpressionXsdType>,
    pub replace_default_flags: Option<super::simple_types::UnsignedBitExpressionXsdType>,
    pub vendor_extensions: Option<super::common_structures::VendorExtensionsElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for ExecutableImageLanguageToolsFileBuilderElementType
{
    type Serializer<'x> =
        quick_xml_serialize::ExecutableImageLanguageToolsFileBuilderElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::ExecutableImageLanguageToolsFileBuilderElementTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::ExecutableImageLanguageToolsFileBuilderElementTypeSerializerState::Init__,
            ),
            name: name.unwrap_or("ipxact:ExecutableImageLanguageToolsFileBuilder"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for ExecutableImageLanguageToolsFileBuilderElementTypeContent
{
    type Serializer<'x> =
        quick_xml_serialize::ExecutableImageLanguageToolsFileBuilderElementTypeContentSerializer<
            'x,
        >;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::ExecutableImageLanguageToolsFileBuilderElementTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::ExecutableImageLanguageToolsFileBuilderElementTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for ExecutableImageLanguageToolsFileBuilderElementType
{
    type Deserializer =
        Box<quick_xml_deserialize::ExecutableImageLanguageToolsFileBuilderElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for ExecutableImageLanguageToolsFileBuilderElementTypeContent
{
    type Deserializer = Box<
        quick_xml_deserialize::ExecutableImageLanguageToolsFileBuilderElementTypeContentDeserializer,
    >;
}
#[derive(Clone, Debug, PartialEq)]
pub struct ExecutableImageLanguageToolsContent81XsdType {
    pub content: ExecutableImageLanguageToolsContent81XsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub enum ExecutableImageLanguageToolsContent81XsdTypeContent {
    Content82(Box<ExecutableImageLanguageToolsContent82XsdType>),
    LinkerCommandFile(Box<LinkerCommandFileElement>),
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for ExecutableImageLanguageToolsContent81XsdType
{
    type Serializer<'x> =
        quick_xml_serialize::ExecutableImageLanguageToolsContent81XsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::ExecutableImageLanguageToolsContent81XsdTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::ExecutableImageLanguageToolsContent81XsdTypeSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for ExecutableImageLanguageToolsContent81XsdTypeContent
{
    type Serializer<'x> =
        quick_xml_serialize::ExecutableImageLanguageToolsContent81XsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::ExecutableImageLanguageToolsContent81XsdTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::ExecutableImageLanguageToolsContent81XsdTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for ExecutableImageLanguageToolsContent81XsdType
{
    type Deserializer =
        Box<quick_xml_deserialize::ExecutableImageLanguageToolsContent81XsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for ExecutableImageLanguageToolsContent81XsdTypeContent
{
    type Deserializer =
        Box<quick_xml_deserialize::ExecutableImageLanguageToolsContent81XsdTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct FileBuildCommandFlagsElementType {
    pub any_attribute: AnyAttributes,
    pub append: Option<super::BooleanXsdType>,
    pub content: super::simple_types::SimpleBaseExpressionXsdType,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for FileBuildCommandFlagsElementType {
    type Serializer<'x> = quick_xml_serialize::FileBuildCommandFlagsElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(
            quick_xml_serialize::FileBuildCommandFlagsElementTypeSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::FileBuildCommandFlagsElementTypeSerializerState::Init__,
                ),
                name: name.unwrap_or("ipxact:FileBuildCommandFlags"),
                is_root,
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for FileBuildCommandFlagsElementType {
    type Deserializer = Box<quick_xml_deserialize::FileBuildCommandFlagsElementTypeDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct FileSetTypeFunctionArgumentElementType {
    pub id: Option<super::Id>,
    pub data_type: DataTypeTypeXsdType,
    pub content: FileSetTypeFunctionArgumentElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct FileSetTypeFunctionArgumentElementTypeContent {
    pub name_group_string: super::common_structures::NameValuePairNameGroupStringXsdType,
    pub value: super::common_structures::ValueElement,
    pub vendor_extensions: Option<super::common_structures::VendorExtensionsElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for FileSetTypeFunctionArgumentElementType {
    type Serializer<'x> = quick_xml_serialize::FileSetTypeFunctionArgumentElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::FileSetTypeFunctionArgumentElementTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::FileSetTypeFunctionArgumentElementTypeSerializerState::Init__,
            ),
            name: name.unwrap_or("ipxact:FileSetTypeFunctionArgument"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for FileSetTypeFunctionArgumentElementTypeContent
{
    type Serializer<'x> =
        quick_xml_serialize::FileSetTypeFunctionArgumentElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::FileSetTypeFunctionArgumentElementTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::FileSetTypeFunctionArgumentElementTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for FileSetTypeFunctionArgumentElementType {
    type Deserializer =
        Box<quick_xml_deserialize::FileSetTypeFunctionArgumentElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for FileSetTypeFunctionArgumentElementTypeContent
{
    type Deserializer =
        Box<quick_xml_deserialize::FileSetTypeFunctionArgumentElementTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct FileSetTypeFunctionSourceFileElementType {
    pub id: Option<super::Id>,
    pub content: FileSetTypeFunctionSourceFileElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct FileSetTypeFunctionSourceFileElementTypeContent {
    pub source_name: IpxactUriXsdType,
    pub file_type: super::file_type::FileTypeElement,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for FileSetTypeFunctionSourceFileElementType {
    type Serializer<'x> =
        quick_xml_serialize::FileSetTypeFunctionSourceFileElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::FileSetTypeFunctionSourceFileElementTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::FileSetTypeFunctionSourceFileElementTypeSerializerState::Init__,
            ),
            name: name.unwrap_or("ipxact:FileSetTypeFunctionSourceFile"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for FileSetTypeFunctionSourceFileElementTypeContent
{
    type Serializer<'x> =
        quick_xml_serialize::FileSetTypeFunctionSourceFileElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::FileSetTypeFunctionSourceFileElementTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::FileSetTypeFunctionSourceFileElementTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for FileSetTypeFunctionSourceFileElementType {
    type Deserializer =
        Box<quick_xml_deserialize::FileSetTypeFunctionSourceFileElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for FileSetTypeFunctionSourceFileElementTypeContent
{
    type Deserializer =
        Box<quick_xml_deserialize::FileSetTypeFunctionSourceFileElementTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct ExecutableImageLanguageToolsContent82XsdType {
    pub content: ExecutableImageLanguageToolsContent82XsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct ExecutableImageLanguageToolsContent82XsdTypeContent {
    pub linker_flags: super::simple_types::StringExpressionXsdType,
    pub linker_command_file: Option<LinkerCommandFileElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for ExecutableImageLanguageToolsContent82XsdType
{
    type Serializer<'x> =
        quick_xml_serialize::ExecutableImageLanguageToolsContent82XsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::ExecutableImageLanguageToolsContent82XsdTypeSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::ExecutableImageLanguageToolsContent82XsdTypeSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer
    for ExecutableImageLanguageToolsContent82XsdTypeContent
{
    type Serializer<'x> =
        quick_xml_serialize::ExecutableImageLanguageToolsContent82XsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::ExecutableImageLanguageToolsContent82XsdTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::ExecutableImageLanguageToolsContent82XsdTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for ExecutableImageLanguageToolsContent82XsdType
{
    type Deserializer =
        Box<quick_xml_deserialize::ExecutableImageLanguageToolsContent82XsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer
    for ExecutableImageLanguageToolsContent82XsdTypeContent
{
    type Deserializer =
        Box<quick_xml_deserialize::ExecutableImageLanguageToolsContent82XsdTypeContentDeserializer>;
}
