// @generated by ipxact-codegen; do not edit by hand.
// Source schema: crates/ipxact/schema/1685-2022/index.xsd

#![allow(dead_code, unused_mut, unused_variables, clippy::all)]

pub mod quick_xml_deserialize;
pub mod quick_xml_serialize;
pub type DesignElement = DesignElementType;
#[derive(Clone, Debug, PartialEq)]
pub struct DesignElementType {
    pub id: Option<super::Id>,
    pub content: DesignElementTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct DesignElementTypeContent {
    pub document_name_group: DesignDocumentNameGroupXsdType,
    pub component_instances: Option<super::sub_instances::ComponentInstancesElement>,
    pub interconnections: Option<super::sub_instances::InterconnectionsElement>,
    pub ad_hoc_connections: Option<super::sub_instances::AdHocConnectionsElement>,
    pub choices: Option<super::auto_configure::ChoicesElement>,
    pub parameters: Option<super::common_structures::ParametersElement>,
    pub assertions: Option<super::common_structures::AssertionsElement>,
    pub vendor_extensions: Option<super::common_structures::VendorExtensionsElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for DesignElementType {
    type Serializer<'x> = quick_xml_serialize::DesignElementTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        Ok(quick_xml_serialize::DesignElementTypeSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::DesignElementTypeSerializerState::Init__),
            name: name.unwrap_or("ipxact:design"),
            is_root,
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for DesignElementTypeContent {
    type Serializer<'x> = quick_xml_serialize::DesignElementTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::DesignElementTypeContentSerializer {
            value: self,
            state: Box::new(quick_xml_serialize::DesignElementTypeContentSerializerState::Init__),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for DesignElementType {
    type Deserializer = Box<quick_xml_deserialize::DesignElementTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for DesignElementTypeContent {
    type Deserializer = Box<quick_xml_deserialize::DesignElementTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct DesignDocumentNameGroupXsdType {
    pub content: DesignDocumentNameGroupXsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct DesignDocumentNameGroupXsdTypeContent {
    pub versioned_identifier: DesignVersionedIdentifierXsdType,
    pub display_name: Option<super::StringXsdType>,
    pub short_description: Option<super::common_structures::ShortDescriptionElement>,
    pub description: Option<super::common_structures::DescriptionElement>,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for DesignDocumentNameGroupXsdType {
    type Serializer<'x> = quick_xml_serialize::DesignDocumentNameGroupXsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::DesignDocumentNameGroupXsdTypeSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::DesignDocumentNameGroupXsdTypeSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for DesignDocumentNameGroupXsdTypeContent {
    type Serializer<'x> = quick_xml_serialize::DesignDocumentNameGroupXsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::DesignDocumentNameGroupXsdTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::DesignDocumentNameGroupXsdTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for DesignDocumentNameGroupXsdType {
    type Deserializer = Box<quick_xml_deserialize::DesignDocumentNameGroupXsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for DesignDocumentNameGroupXsdTypeContent {
    type Deserializer =
        Box<quick_xml_deserialize::DesignDocumentNameGroupXsdTypeContentDeserializer>;
}
#[derive(Clone, Debug, PartialEq)]
pub struct DesignVersionedIdentifierXsdType {
    pub content: DesignVersionedIdentifierXsdTypeContent,
}
#[derive(Clone, Debug, PartialEq)]
pub struct DesignVersionedIdentifierXsdTypeContent {
    pub vendor: super::NameXsdType,
    pub library: super::NameXsdType,
    pub name: super::NmtokenXsdType,
    pub version: super::NmtokenXsdType,
}
impl ::xsd_parser_types::quick_xml::WithSerializer for DesignVersionedIdentifierXsdType {
    type Serializer<'x> = quick_xml_serialize::DesignVersionedIdentifierXsdTypeSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(
            quick_xml_serialize::DesignVersionedIdentifierXsdTypeSerializer {
                value: self,
                state: Box::new(
                    quick_xml_serialize::DesignVersionedIdentifierXsdTypeSerializerState::Init__,
                ),
            },
        )
    }
}
impl ::xsd_parser_types::quick_xml::WithSerializer for DesignVersionedIdentifierXsdTypeContent {
    type Serializer<'x> =
        quick_xml_serialize::DesignVersionedIdentifierXsdTypeContentSerializer<'x>;
    fn serializer<'ser>(
        &'ser self,
        name: Option<&'ser str>,
        is_root: bool,
    ) -> Result<Self::Serializer<'ser>, ::xsd_parser_types::quick_xml::Error> {
        let _name = name;
        let _is_root = is_root;
        Ok(quick_xml_serialize::DesignVersionedIdentifierXsdTypeContentSerializer {
            value: self,
            state: Box::new(
                quick_xml_serialize::DesignVersionedIdentifierXsdTypeContentSerializerState::Init__,
            ),
        })
    }
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for DesignVersionedIdentifierXsdType {
    type Deserializer = Box<quick_xml_deserialize::DesignVersionedIdentifierXsdTypeDeserializer>;
}
impl ::xsd_parser_types::quick_xml::WithDeserializer for DesignVersionedIdentifierXsdTypeContent {
    type Deserializer =
        Box<quick_xml_deserialize::DesignVersionedIdentifierXsdTypeContentDeserializer>;
}
