// @generated by ipxact-codegen; do not edit by hand.
// Source schema: crates/ipxact/schema/1.4/index.xsd

#![allow(dead_code, unused_mut, unused_variables, clippy::all)]

use xsd_parser_types::{quick_xml::Serializer as _, xml::AnyElement};
#[derive(Debug)]
pub struct AnyTypeXsdTypeSerializer<'ser> {
    pub(super) value: &'ser super::AnyTypeXsdType,
    pub(super) state: Box<AnyTypeXsdTypeSerializerState<'ser>>,
    pub(super) name: &'ser str,
    pub(super) is_root: bool,
}
#[derive(Debug)]
pub(super) enum AnyTypeXsdTypeSerializerState<'ser> {
    Init__,
    Content__(
        <super::AnyTypeXsdTypeContent as ::xsd_parser_types::quick_xml::WithSerializer>::Serializer<
            'ser,
        >,
    ),
    End__,
    Done__,
    Phantom__(&'ser ()),
}
impl<'ser> AnyTypeXsdTypeSerializer<'ser> {
    fn next_event(
        &mut self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Result<
        Option<::xsd_parser_types::quick_xml::Event<'ser>>,
        ::xsd_parser_types::quick_xml::Error,
    > {
        loop {
            match &mut *self.state {
                AnyTypeXsdTypeSerializerState::Init__ => {
                    *self.state = AnyTypeXsdTypeSerializerState::Content__(
                        ::xsd_parser_types::quick_xml::WithSerializer::serializer(
                            &self.value.content,
                            None,
                            false,
                        )?,
                    );
                    let mut bytes = ::xsd_parser_types::quick_xml::BytesStart::new(self.name);
                    bytes.extend_attributes(self.value.any_attribute.attributes());
                    return Ok(Some(::xsd_parser_types::quick_xml::Event::Start(bytes)));
                }
                AnyTypeXsdTypeSerializerState::Content__(x) => match x.next(helper).transpose()? {
                    Some(event) => return Ok(Some(event)),
                    None => *self.state = AnyTypeXsdTypeSerializerState::End__,
                },
                AnyTypeXsdTypeSerializerState::End__ => {
                    *self.state = AnyTypeXsdTypeSerializerState::Done__;
                    return Ok(Some(::xsd_parser_types::quick_xml::Event::End(
                        ::xsd_parser_types::quick_xml::BytesEnd::new(self.name),
                    )));
                }
                AnyTypeXsdTypeSerializerState::Done__ => return Ok(None),
                AnyTypeXsdTypeSerializerState::Phantom__(_) => unreachable!(),
            }
        }
    }
}
impl<'ser> ::xsd_parser_types::quick_xml::Serializer<'ser> for AnyTypeXsdTypeSerializer<'ser> {
    fn next(
        &mut self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Option<
        Result<::xsd_parser_types::quick_xml::Event<'ser>, ::xsd_parser_types::quick_xml::Error>,
    > {
        match self.next_event(helper) {
            Ok(Some(event)) => Some(Ok(event)),
            Ok(None) => None,
            Err(error) => {
                *self.state = AnyTypeXsdTypeSerializerState::Done__;
                Some(Err(error))
            }
        }
    }
}
#[derive(Debug)]
pub struct AnyTypeXsdTypeContentSerializer<'ser> {
    pub(super) value: &'ser super::AnyTypeXsdTypeContent,
    pub(super) state: Box<AnyTypeXsdTypeContentSerializerState<'ser>>,
}
#[derive(Debug)]
pub(super) enum AnyTypeXsdTypeContentSerializerState<'ser> {
    Init__,
    Any(::xsd_parser_types::quick_xml::IterSerializer<'ser, &'ser [AnyElement], AnyElement>),
    Done__,
    Phantom__(&'ser ()),
}
impl<'ser> AnyTypeXsdTypeContentSerializer<'ser> {
    fn next_event(
        &mut self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Result<
        Option<::xsd_parser_types::quick_xml::Event<'ser>>,
        ::xsd_parser_types::quick_xml::Error,
    > {
        loop {
            match &mut *self.state {
                AnyTypeXsdTypeContentSerializerState::Init__ => {
                    *self.state = AnyTypeXsdTypeContentSerializerState::Any(
                        ::xsd_parser_types::quick_xml::IterSerializer::new(
                            &self.value.any[..],
                            None,
                            false,
                        ),
                    );
                }
                AnyTypeXsdTypeContentSerializerState::Any(x) => {
                    match x.next(helper).transpose()? {
                        Some(event) => return Ok(Some(event)),
                        None => {
                            *self.state = AnyTypeXsdTypeContentSerializerState::Done__;
                        }
                    }
                }
                AnyTypeXsdTypeContentSerializerState::Done__ => return Ok(None),
                AnyTypeXsdTypeContentSerializerState::Phantom__(_) => unreachable!(),
            }
        }
    }
}
impl<'ser> ::xsd_parser_types::quick_xml::Serializer<'ser>
    for AnyTypeXsdTypeContentSerializer<'ser>
{
    fn next(
        &mut self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Option<
        Result<::xsd_parser_types::quick_xml::Event<'ser>, ::xsd_parser_types::quick_xml::Error>,
    > {
        match self.next_event(helper) {
            Ok(Some(event)) => Some(Ok(event)),
            Ok(None) => None,
            Err(error) => {
                *self.state = AnyTypeXsdTypeContentSerializerState::Done__;
                Some(Err(error))
            }
        }
    }
}
