// @generated by ipxact-codegen; do not edit by hand.
// Source schema: crates/ipxact/schema/1685-2014/index.xsd

#![allow(dead_code, unused_mut, unused_variables, clippy::all)]

use xsd_parser_types::quick_xml::Serializer as _;
#[derive(Debug)]
pub struct DesignElementTypeSerializer<'ser> {
    pub(super) value: &'ser super::DesignElementType,
    pub(super) state: Box<DesignElementTypeSerializerState<'ser>>,
    pub(super) name: &'ser str,
    pub(super) is_root: bool,
}
#[derive(Debug)]
pub(super) enum DesignElementTypeSerializerState<'ser> {
    Init__,
    Content__(
        <super::DesignElementTypeContent as ::xsd_parser_types::quick_xml::WithSerializer>::Serializer<
            'ser,
        >,
    ),
    End__,
    Done__,
    Phantom__(&'ser ()),
}
impl<'ser> DesignElementTypeSerializer<'ser> {
    fn next_event(
        &mut self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Result<
        Option<::xsd_parser_types::quick_xml::Event<'ser>>,
        ::xsd_parser_types::quick_xml::Error,
    > {
        loop {
            match &mut *self.state {
                DesignElementTypeSerializerState::Init__ => {
                    *self.state = DesignElementTypeSerializerState::Content__(
                        ::xsd_parser_types::quick_xml::WithSerializer::serializer(
                            &self.value.content,
                            None,
                            false,
                        )?,
                    );
                    let mut bytes = ::xsd_parser_types::quick_xml::BytesStart::new(self.name);
                    helper.begin_ns_scope();
                    if self.is_root {
                        helper.write_xmlns(
                            &mut bytes,
                            Some(&super::super::PREFIX_IPXACT),
                            &super::super::NS_IPXACT,
                        );
                    }
                    helper.write_attrib_opt(&mut bytes, "id", &self.value.id)?;
                    return Ok(Some(::xsd_parser_types::quick_xml::Event::Start(bytes)));
                }
                DesignElementTypeSerializerState::Content__(x) => {
                    match x.next(helper).transpose()? {
                        Some(event) => return Ok(Some(event)),
                        None => *self.state = DesignElementTypeSerializerState::End__,
                    }
                }
                DesignElementTypeSerializerState::End__ => {
                    *self.state = DesignElementTypeSerializerState::Done__;
                    helper.end_ns_scope();
                    return Ok(Some(::xsd_parser_types::quick_xml::Event::End(
                        ::xsd_parser_types::quick_xml::BytesEnd::new(self.name),
                    )));
                }
                DesignElementTypeSerializerState::Done__ => return Ok(None),
                DesignElementTypeSerializerState::Phantom__(_) => unreachable!(),
            }
        }
    }
}
impl<'ser> ::xsd_parser_types::quick_xml::Serializer<'ser> for DesignElementTypeSerializer<'ser> {
    fn next(
        &mut self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Option<
        Result<::xsd_parser_types::quick_xml::Event<'ser>, ::xsd_parser_types::quick_xml::Error>,
    > {
        match self.next_event(helper) {
            Ok(Some(event)) => Some(Ok(event)),
            Ok(None) => None,
            Err(error) => {
                *self.state = DesignElementTypeSerializerState::Done__;
                Some(Err(error))
            }
        }
    }
}
#[derive(Debug)]
pub struct DesignElementTypeContentSerializer<'ser> {
    pub(super) value: &'ser super::DesignElementTypeContent,
    pub(super) state: Box<DesignElementTypeContentSerializerState<'ser>>,
}
#[derive(Debug)]
pub(super) enum DesignElementTypeContentSerializerState<'ser> {
    Init__,
    VersionedIdentifier(
        <super::DesignVersionedIdentifierXsdType as ::xsd_parser_types::quick_xml::WithSerializer>::Serializer<
            'ser,
        >,
    ),
    ComponentInstances(
        ::xsd_parser_types::quick_xml::IterSerializer<
            'ser,
            Option<&'ser super::super::sub_instances::ComponentInstancesElement>,
            super::super::sub_instances::ComponentInstancesElement,
        >,
    ),
    Interconnections(
        ::xsd_parser_types::quick_xml::IterSerializer<
            'ser,
            Option<&'ser super::super::sub_instances::InterconnectionsElement>,
            super::super::sub_instances::InterconnectionsElement,
        >,
    ),
    AdHocConnections(
        ::xsd_parser_types::quick_xml::IterSerializer<
            'ser,
            Option<&'ser super::super::sub_instances::AdHocConnectionsElement>,
            super::super::sub_instances::AdHocConnectionsElement,
        >,
    ),
    Description(
        ::xsd_parser_types::quick_xml::IterSerializer<
            'ser,
            Option<&'ser super::super::common_structures::DescriptionElement>,
            super::super::common_structures::DescriptionElement,
        >,
    ),
    Parameters(
        ::xsd_parser_types::quick_xml::IterSerializer<
            'ser,
            Option<&'ser super::super::common_structures::ParametersElement>,
            super::super::common_structures::ParametersElement,
        >,
    ),
    Assertions(
        ::xsd_parser_types::quick_xml::IterSerializer<
            'ser,
            Option<&'ser super::super::common_structures::AssertionsElement>,
            super::super::common_structures::AssertionsElement,
        >,
    ),
    VendorExtensions(
        ::xsd_parser_types::quick_xml::IterSerializer<
            'ser,
            Option<&'ser super::super::common_structures::VendorExtensionsElement>,
            super::super::common_structures::VendorExtensionsElement,
        >,
    ),
    Done__,
    Phantom__(&'ser ()),
}
impl<'ser> DesignElementTypeContentSerializer<'ser> {
    fn next_event(
        &mut self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Result<
        Option<::xsd_parser_types::quick_xml::Event<'ser>>,
        ::xsd_parser_types::quick_xml::Error,
    > {
        loop {
            match &mut *self.state {
                DesignElementTypeContentSerializerState::Init__ => {
                    *self.state = DesignElementTypeContentSerializerState::VersionedIdentifier(
                        ::xsd_parser_types::quick_xml::WithSerializer::serializer(
                            &self.value.versioned_identifier,
                            Some("versionedIdentifier"),
                            false,
                        )?,
                    );
                }
                DesignElementTypeContentSerializerState::VersionedIdentifier(x) => {
                    match x.next(helper).transpose()? {
                        Some(event) => return Ok(Some(event)),
                        None => {
                            *self.state =
                                DesignElementTypeContentSerializerState::ComponentInstances(
                                    ::xsd_parser_types::quick_xml::IterSerializer::new(
                                        self.value.component_instances.as_ref(),
                                        Some("ipxact:componentInstances"),
                                        false,
                                    ),
                                );
                        }
                    }
                }
                DesignElementTypeContentSerializerState::ComponentInstances(x) => {
                    match x.next(helper).transpose()? {
                        Some(event) => return Ok(Some(event)),
                        None => {
                            *self.state = DesignElementTypeContentSerializerState::Interconnections(
                                ::xsd_parser_types::quick_xml::IterSerializer::new(
                                    self.value.interconnections.as_ref(),
                                    Some("ipxact:interconnections"),
                                    false,
                                ),
                            );
                        }
                    }
                }
                DesignElementTypeContentSerializerState::Interconnections(x) => {
                    match x.next(helper).transpose()? {
                        Some(event) => return Ok(Some(event)),
                        None => {
                            *self.state = DesignElementTypeContentSerializerState::AdHocConnections(
                                ::xsd_parser_types::quick_xml::IterSerializer::new(
                                    self.value.ad_hoc_connections.as_ref(),
                                    Some("ipxact:adHocConnections"),
                                    false,
                                ),
                            );
                        }
                    }
                }
                DesignElementTypeContentSerializerState::AdHocConnections(x) => {
                    match x.next(helper).transpose()? {
                        Some(event) => return Ok(Some(event)),
                        None => {
                            *self.state = DesignElementTypeContentSerializerState::Description(
                                ::xsd_parser_types::quick_xml::IterSerializer::new(
                                    self.value.description.as_ref(),
                                    Some("ipxact:description"),
                                    false,
                                ),
                            );
                        }
                    }
                }
                DesignElementTypeContentSerializerState::Description(x) => {
                    match x.next(helper).transpose()? {
                        Some(event) => return Ok(Some(event)),
                        None => {
                            *self.state = DesignElementTypeContentSerializerState::Parameters(
                                ::xsd_parser_types::quick_xml::IterSerializer::new(
                                    self.value.parameters.as_ref(),
                                    Some("ipxact:parameters"),
                                    false,
                                ),
                            );
                        }
                    }
                }
                DesignElementTypeContentSerializerState::Parameters(x) => {
                    match x.next(helper).transpose()? {
                        Some(event) => return Ok(Some(event)),
                        None => {
                            *self.state = DesignElementTypeContentSerializerState::Assertions(
                                ::xsd_parser_types::quick_xml::IterSerializer::new(
                                    self.value.assertions.as_ref(),
                                    Some("ipxact:assertions"),
                                    false,
                                ),
                            );
                        }
                    }
                }
                DesignElementTypeContentSerializerState::Assertions(x) => {
                    match x.next(helper).transpose()? {
                        Some(event) => return Ok(Some(event)),
                        None => {
                            *self.state = DesignElementTypeContentSerializerState::VendorExtensions(
                                ::xsd_parser_types::quick_xml::IterSerializer::new(
                                    self.value.vendor_extensions.as_ref(),
                                    Some("ipxact:vendorExtensions"),
                                    false,
                                ),
                            );
                        }
                    }
                }
                DesignElementTypeContentSerializerState::VendorExtensions(x) => {
                    match x.next(helper).transpose()? {
                        Some(event) => return Ok(Some(event)),
                        None => {
                            *self.state = DesignElementTypeContentSerializerState::Done__;
                        }
                    }
                }
                DesignElementTypeContentSerializerState::Done__ => return Ok(None),
                DesignElementTypeContentSerializerState::Phantom__(_) => unreachable!(),
            }
        }
    }
}
impl<'ser> ::xsd_parser_types::quick_xml::Serializer<'ser>
    for DesignElementTypeContentSerializer<'ser>
{
    fn next(
        &mut self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Option<
        Result<::xsd_parser_types::quick_xml::Event<'ser>, ::xsd_parser_types::quick_xml::Error>,
    > {
        match self.next_event(helper) {
            Ok(Some(event)) => Some(Ok(event)),
            Ok(None) => None,
            Err(error) => {
                *self.state = DesignElementTypeContentSerializerState::Done__;
                Some(Err(error))
            }
        }
    }
}
#[derive(Debug)]
pub struct DesignVersionedIdentifierXsdTypeSerializer<'ser> {
    pub(super) value: &'ser super::DesignVersionedIdentifierXsdType,
    pub(super) state: Box<DesignVersionedIdentifierXsdTypeSerializerState<'ser>>,
}
#[derive(Debug)]
pub(super) enum DesignVersionedIdentifierXsdTypeSerializerState<'ser> {
    Init__,
    Content__(
        <super::DesignVersionedIdentifierXsdTypeContent as ::xsd_parser_types::quick_xml::WithSerializer>::Serializer<
            'ser,
        >,
    ),
    Done__,
    Phantom__(&'ser ()),
}
impl<'ser> DesignVersionedIdentifierXsdTypeSerializer<'ser> {
    fn next_event(
        &mut self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Result<
        Option<::xsd_parser_types::quick_xml::Event<'ser>>,
        ::xsd_parser_types::quick_xml::Error,
    > {
        loop {
            match &mut *self.state {
                DesignVersionedIdentifierXsdTypeSerializerState::Init__ => {
                    *self.state = DesignVersionedIdentifierXsdTypeSerializerState::Content__(
                        ::xsd_parser_types::quick_xml::WithSerializer::serializer(
                            &self.value.content,
                            None,
                            false,
                        )?,
                    );
                }
                DesignVersionedIdentifierXsdTypeSerializerState::Content__(x) => {
                    match x.next(helper).transpose()? {
                        Some(event) => return Ok(Some(event)),
                        None => {
                            *self.state = DesignVersionedIdentifierXsdTypeSerializerState::Done__;
                        }
                    }
                }
                DesignVersionedIdentifierXsdTypeSerializerState::Done__ => {
                    return Ok(None);
                }
                DesignVersionedIdentifierXsdTypeSerializerState::Phantom__(_) => {
                    unreachable!()
                }
            }
        }
    }
}
impl<'ser> ::xsd_parser_types::quick_xml::Serializer<'ser>
    for DesignVersionedIdentifierXsdTypeSerializer<'ser>
{
    fn next(
        &mut self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Option<
        Result<::xsd_parser_types::quick_xml::Event<'ser>, ::xsd_parser_types::quick_xml::Error>,
    > {
        match self.next_event(helper) {
            Ok(Some(event)) => Some(Ok(event)),
            Ok(None) => None,
            Err(error) => {
                *self.state = DesignVersionedIdentifierXsdTypeSerializerState::Done__;
                Some(Err(error))
            }
        }
    }
}
#[derive(Debug)]
pub struct DesignVersionedIdentifierXsdTypeContentSerializer<'ser> {
    pub(super) value: &'ser super::DesignVersionedIdentifierXsdTypeContent,
    pub(super) state: Box<DesignVersionedIdentifierXsdTypeContentSerializerState<'ser>>,
}
#[derive(Debug)]
pub(super) enum DesignVersionedIdentifierXsdTypeContentSerializerState<'ser> {
    Init__,
    Vendor(
        <super::super::NameXsdType as ::xsd_parser_types::quick_xml::WithSerializer>::Serializer<
            'ser,
        >,
    ),
    Library(
        <super::super::NameXsdType as ::xsd_parser_types::quick_xml::WithSerializer>::Serializer<
            'ser,
        >,
    ),
    Name(
        <super::super::NmtokenXsdType as ::xsd_parser_types::quick_xml::WithSerializer>::Serializer<
            'ser,
        >,
    ),
    Version(
        <super::super::NmtokenXsdType as ::xsd_parser_types::quick_xml::WithSerializer>::Serializer<
            'ser,
        >,
    ),
    Done__,
    Phantom__(&'ser ()),
}
impl<'ser> DesignVersionedIdentifierXsdTypeContentSerializer<'ser> {
    fn next_event(
        &mut self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Result<
        Option<::xsd_parser_types::quick_xml::Event<'ser>>,
        ::xsd_parser_types::quick_xml::Error,
    > {
        loop {
            match &mut *self.state {
                DesignVersionedIdentifierXsdTypeContentSerializerState::Init__ => {
                    *self.state = DesignVersionedIdentifierXsdTypeContentSerializerState::Vendor(
                        ::xsd_parser_types::quick_xml::WithSerializer::serializer(
                            &self.value.vendor,
                            Some("ipxact:vendor"),
                            false,
                        )?,
                    );
                }
                DesignVersionedIdentifierXsdTypeContentSerializerState::Vendor(x) => {
                    match x.next(helper).transpose()? {
                        Some(event) => return Ok(Some(event)),
                        None => {
                            *self.state =
                                DesignVersionedIdentifierXsdTypeContentSerializerState::Library(
                                    ::xsd_parser_types::quick_xml::WithSerializer::serializer(
                                        &self.value.library,
                                        Some("ipxact:library"),
                                        false,
                                    )?,
                                );
                        }
                    }
                }
                DesignVersionedIdentifierXsdTypeContentSerializerState::Library(x) => {
                    match x.next(helper).transpose()? {
                        Some(event) => return Ok(Some(event)),
                        None => {
                            *self.state =
                                DesignVersionedIdentifierXsdTypeContentSerializerState::Name(
                                    ::xsd_parser_types::quick_xml::WithSerializer::serializer(
                                        &self.value.name,
                                        Some("ipxact:name"),
                                        false,
                                    )?,
                                );
                        }
                    }
                }
                DesignVersionedIdentifierXsdTypeContentSerializerState::Name(x) => {
                    match x.next(helper).transpose()? {
                        Some(event) => return Ok(Some(event)),
                        None => {
                            *self.state =
                                DesignVersionedIdentifierXsdTypeContentSerializerState::Version(
                                    ::xsd_parser_types::quick_xml::WithSerializer::serializer(
                                        &self.value.version,
                                        Some("ipxact:version"),
                                        false,
                                    )?,
                                );
                        }
                    }
                }
                DesignVersionedIdentifierXsdTypeContentSerializerState::Version(x) => {
                    match x.next(helper).transpose()? {
                        Some(event) => return Ok(Some(event)),
                        None => {
                            *self.state =
                                DesignVersionedIdentifierXsdTypeContentSerializerState::Done__;
                        }
                    }
                }
                DesignVersionedIdentifierXsdTypeContentSerializerState::Done__ => {
                    return Ok(None);
                }
                DesignVersionedIdentifierXsdTypeContentSerializerState::Phantom__(_) => {
                    unreachable!()
                }
            }
        }
    }
}
impl<'ser> ::xsd_parser_types::quick_xml::Serializer<'ser>
    for DesignVersionedIdentifierXsdTypeContentSerializer<'ser>
{
    fn next(
        &mut self,
        helper: &mut ::xsd_parser_types::quick_xml::SerializeHelper,
    ) -> Option<
        Result<::xsd_parser_types::quick_xml::Event<'ser>, ::xsd_parser_types::quick_xml::Error>,
    > {
        match self.next_event(helper) {
            Ok(Some(event)) => Some(Ok(event)),
            Ok(None) => None,
            Err(error) => {
                *self.state = DesignVersionedIdentifierXsdTypeContentSerializerState::Done__;
                Some(Err(error))
            }
        }
    }
}
